// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Jérôme Bastian Winkel

package architecture

import (
	"go/ast"
	"go/token"
	"os"
	"strings"
	"testing"
)

// licenceHeader is the first line every hand-written source file carries.
const licenceHeader = "// SPDX-License-Identifier: BUSL-1.1"

// TestEverySourceFileCarriesItsLicence keeps the claim in licensing-editions.md §3 true.
//
// The header is what tells anyone holding a single file which terms it came under - a file
// travels: into an issue, into a paste, into a fork. BSL 1.1 converts to Apache-2.0 three years
// after publication (ADR-0013), and the identifier is what makes that datable for the person
// holding the copy rather than a claim they would have to take on trust.
//
// Generated files are exempt, and deliberately: the generator writes their first line, so a header
// added by hand would be removed at the next `make generate` - and a rule that is undone by a build
// step is a rule nobody can keep.
func TestEverySourceFileCarriesItsLicence(t *testing.T) {
	var checked int

	forEachGoFile(t, []string{"../../core", "../../infrastructure", "../../presentation", "../../cmd", "../../db", "../../tools", "../../test"},
		func(path string, _ *ast.File, _ *token.FileSet) {
			source, err := os.ReadFile(path)
			if err != nil {
				t.Errorf("%s is not readable: %v", rel(path), err)
				return
			}
			content := string(source)
			if strings.Contains(content, "Code generated by") || strings.Contains(content, "DO NOT EDIT") {
				return
			}

			checked++
			if !strings.HasPrefix(content, licenceHeader) {
				t.Errorf("%s does not begin with %s (licensing-editions.md §3)", rel(path), licenceHeader)
			}
		})

	if checked == 0 {
		// A test that read nothing passes for the wrong reason.
		t.Fatal("no source file was read - the walk no longer finds anything")
	}
	t.Logf("%d hand-written source files carry the licence header", checked)
}
