# Code generated by tools/sdkgen from api/openapi.yaml - DO NOT EDIT.
#
# The Python client for the Hubtask API (P-03, ADR-0057). Regenerated by `make generate`; the
# specification is the source and this is the result (ADR-0004). One method per operation, over
# urllib and nothing else.
#
# SPDX-License-Identifier: BUSL-1.1
from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable

from .types import *  # noqa: F401,F403 - the named schemas, for the annotations below


class ProblemError(Exception):
    """A refusal: the status and the problem document (RFC 9457) the server answered."""

    def __init__(self, status: int, problem: dict[str, Any]) -> None:
        self.status = status
        self.problem = problem
        code = problem.get("code", "")
        detail = problem.get("detail_code")
        super().__init__(f"hubtask: {status} {code} ({detail})" if detail else f"hubtask: {status} {code}")


class Client:
    """The client. `base_url` is the API root, `https://<host>/api/v1`; `token` is the bearer
    or a callable answering the current one; `timeout` bounds every request in seconds."""

    def __init__(
        self,
        base_url: str,
        token: str | Callable[[], str | None] | None = None,
        *,
        timeout: float = 30.0,
        headers: dict[str, str] | None = None,
        opener: urllib.request.OpenerDirector | None = None,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.timeout = timeout
        self.headers = dict(headers or {})
        self.opener = opener or urllib.request.build_opener()

    def _call(
        self,
        method: str,
        template: str,
        path: dict[str, Any],
        query: dict[str, Any] | None,
        headers: dict[str, str | None],
        body: Any,
        body_kind: str,
        content_type: str | None,
        answer: str,
    ) -> Any:
        url = template
        for name, value in path.items():
            url = url.replace("{" + name + "}", urllib.parse.quote(str(value), safe=""))
        params = [(k, str(v)) for k, v in (query or {}).items() if v is not None]
        if params:
            url += "?" + urllib.parse.urlencode(params)
        sent: dict[str, str] = dict(self.headers)
        if answer == "json":
            sent["Accept"] = "application/json, application/problem+json"
        token = self.token() if callable(self.token) else self.token
        if token:
            sent["Authorization"] = f"Bearer {token}"
        for key, value in headers.items():
            if value is not None:
                sent[key] = value
        data: bytes | None = None
        if body_kind == "json":
            sent["Content-Type"] = content_type or "application/json"
            data = json.dumps(body).encode("utf-8")
        elif body_kind == "raw":
            if content_type:
                sent["Content-Type"] = content_type
            data = body if isinstance(body, (bytes, bytearray)) else str(body).encode("utf-8")
        request = urllib.request.Request(self.base_url + url, data=data, method=method, headers=sent)
        try:
            response = self.opener.open(request, timeout=self.timeout)
        except urllib.error.HTTPError as refused:
            raw = refused.read()
            problem: dict[str, Any] = {"status": refused.code, "code": ""}
            try:
                parsed = json.loads(raw) if raw else {}
                if isinstance(parsed, dict):
                    problem.update(parsed)
            except ValueError:
                pass  # not a problem document; the status is the whole answer
            problem.setdefault("status", refused.code)
            raise ProblemError(refused.code, problem) from None
        with response:
            if answer == "raw":
                return response.read()
            payload = response.read()
        if answer == "void" or response.status == 204 or not payload:
            return None
        return json.loads(payload)

    def list_templates(self, *, query: dict[str, Any] | None = None) -> "TemplatePage":
        """GET /templates"""
        return self._call("GET", "/templates", {}, query, {}, None, "none", None, "json")

    def create_template(self, body: "TemplateInput", *, idempotency_key: str | None = None) -> "Template":
        """POST /templates"""
        return self._call("POST", "/templates", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_template(self, template_id: str) -> "Template":
        """GET /templates/{templateId}"""
        return self._call("GET", "/templates/{templateId}", {"templateId": template_id}, None, {}, None, "none", None, "json")

    def update_template(self, template_id: str, body: "TemplateUpdate", *, if_match: str | None = None) -> "Template":
        """PATCH /templates/{templateId}"""
        return self._call("PATCH", "/templates/{templateId}", {"templateId": template_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_template(self, template_id: str, *, if_match: str | None = None) -> None:
        """DELETE /templates/{templateId}"""
        return self._call("DELETE", "/templates/{templateId}", {"templateId": template_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def instantiate_template(self, template_id: str, body: "TemplateInstantiation", *, idempotency_key: str | None = None) -> "TemplateInstance":
        """POST /templates/{templateId}:instantiate"""
        return self._call("POST", "/templates/{templateId}:instantiate", {"templateId": template_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def list_saved_views(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """GET /views"""
        return self._call("GET", "/views", {}, query, {}, None, "none", None, "json")

    def create_saved_view(self, body: "SavedViewCreate", *, idempotency_key: str | None = None) -> "SavedView":
        """POST /views"""
        return self._call("POST", "/views", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_saved_view(self, view_id: str) -> "SavedView":
        """GET /views/{viewId}"""
        return self._call("GET", "/views/{viewId}", {"viewId": view_id}, None, {}, None, "none", None, "json")

    def update_saved_view(self, view_id: str, body: "SavedViewUpdate", *, if_match: str | None = None) -> "SavedView":
        """PATCH /views/{viewId}"""
        return self._call("PATCH", "/views/{viewId}", {"viewId": view_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_saved_view(self, view_id: str, *, if_match: str | None = None) -> None:
        """DELETE /views/{viewId}"""
        return self._call("DELETE", "/views/{viewId}", {"viewId": view_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def share_saved_view(self, view_id: str, body: "SavedViewShare", *, idempotency_key: str | None = None, if_match: str | None = None) -> "SavedView":
        """POST /views/{viewId}:share"""
        return self._call("POST", "/views/{viewId}:share", {"viewId": view_id}, None, {"Idempotency-Key": idempotency_key, "If-Match": if_match}, body, "json", "application/json", "json")

    def export_view(self, view_id: str, body: "ViewExport", *, idempotency_key: str | None = None) -> bytes:
        """POST /views/{viewId}:export"""
        return self._call("POST", "/views/{viewId}:export", {"viewId": view_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "raw")

    def list_jumble_entries(self, *, query: dict[str, Any] | None = None) -> "JumbleEntryPage":
        """The jumble, newest first"""
        return self._call("GET", "/jumble/entries", {}, query, {}, None, "none", None, "json")

    def submit_jumble_entry(self, body: "JumbleEntrySubmit", *, idempotency_key: str | None = None) -> "JumbleEntry":
        """Put something in the jumble"""
        return self._call("POST", "/jumble/entries", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def convert_jumble_entry(self, entry_id: str, body: "JumbleEntryConvert", *, idempotency_key: str | None = None) -> "JumbleEntry":
        """Turn an entry into work"""
        return self._call("POST", "/jumble/entries/{entryId}:convert", {"entryId": entry_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def suggest_from_jumble_entry(self, entry_id: str, *, idempotency_key: str | None = None) -> None:
        """Ask AI what this entry should become"""
        return self._call("POST", "/jumble/entries/{entryId}:suggest", {"entryId": entry_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "void")

    def dismiss_jumble_entry(self, entry_id: str, *, idempotency_key: str | None = None) -> "JumbleEntry":
        """Decide against an entry"""
        return self._call("POST", "/jumble/entries/{entryId}:dismiss", {"entryId": entry_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_rules(self, *, query: dict[str, Any] | None = None) -> "AutomationRulePage":
        """The workspace's automation rules"""
        return self._call("GET", "/automation/rules", {}, query, {}, None, "none", None, "json")

    def create_rule(self, body: "AutomationRuleCreate", *, idempotency_key: str | None = None) -> "AutomationRule":
        """Write a rule"""
        return self._call("POST", "/automation/rules", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_rule(self, rule_id: str) -> "AutomationRule":
        """One rule, as it stands"""
        return self._call("GET", "/automation/rules/{ruleId}", {"ruleId": rule_id}, None, {}, None, "none", None, "json")

    def update_rule(self, rule_id: str, body: "AutomationRuleUpdate") -> "AutomationRule":
        """Change what a rule does"""
        return self._call("PATCH", "/automation/rules/{ruleId}", {"ruleId": rule_id}, None, {}, body, "json", "application/merge-patch+json", "json")

    def delete_rule(self, rule_id: str) -> None:
        """Remove a rule"""
        return self._call("DELETE", "/automation/rules/{ruleId}", {"ruleId": rule_id}, None, {}, None, "none", None, "void")

    def enable_rule(self, rule_id: str, *, idempotency_key: str | None = None) -> "AutomationRule":
        """Switch a rule on"""
        return self._call("POST", "/automation/rules/{ruleId}:enable", {"ruleId": rule_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def disable_rule(self, rule_id: str, *, idempotency_key: str | None = None) -> "AutomationRule":
        """Switch a rule off"""
        return self._call("POST", "/automation/rules/{ruleId}:disable", {"ruleId": rule_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def test_rule(self, body: "RuleTest") -> "RuleTestResult":
        """Dry-run a rule against a sample event"""
        return self._call("POST", "/automation/rules:test", {}, None, {}, body, "json", "application/json", "json")

    def trigger_rule_manually(self, rule_id: str, *, idempotency_key: str | None = None) -> "RuleRunAccepted":
        """Run a rule now"""
        return self._call("POST", "/automation/rules/{ruleId}:trigger", {"ruleId": rule_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def rotate_inbound_trigger(self, rule_id: str, *, idempotency_key: str | None = None) -> "InboundTriggerToken":
        """Mint the address an inbound-webhook rule answers on"""
        return self._call("POST", "/automation/rules/{ruleId}:rotate-inbound-token", {"ruleId": rule_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def rotate_jumble_intake(self, *, idempotency_key: str | None = None) -> "JumbleIntakeToken":
        """Mint the address the jumble accepts webhooks on"""
        return self._call("POST", "/jumble/intake:rotate-token", {}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def start_jumble_intake(self, token: str, body: "JumbleIntakeDelivery") -> "JumbleIntakeAccepted":
        """Deliver something into the jumble from outside"""
        return self._call("POST", "/jumble/inbound/{token}", {"token": token}, None, {}, body, "json", "application/json", "json")

    def deliver_mail(self, token: str, body: bytes) -> "JumbleIntakeAccepted":
        """Deliver a mail into the jumble"""
        return self._call("POST", "/jumble/mail/{token}", {"token": token}, None, {}, body, "raw", "message/rfc822", "json")

    def start_inbound_run(self, token: str, body: dict[str, Any]) -> "RuleRunAccepted":
        """Start a rule from outside"""
        return self._call("POST", "/automation/inbound/{token}", {"token": token}, None, {}, body, "json", "application/json", "json")

    def list_rule_runs(self, *, query: dict[str, Any] | None = None) -> "RuleRunPage":
        """What the rules have done"""
        return self._call("GET", "/automation/runs", {}, query, {}, None, "none", None, "json")

    def get_rule_run(self, run_id: str) -> "RuleRun":
        """One run, with every condition and every action"""
        return self._call("GET", "/automation/runs/{runId}", {"runId": run_id}, None, {}, None, "none", None, "json")

    def replay_rule_run(self, run_id: str, *, idempotency_key: str | None = None) -> "RuleRunAccepted":
        """Complete a failed run"""
        return self._call("POST", "/automation/runs/{runId}:replay", {"runId": run_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_webhook_subscriptions(self) -> dict[str, Any]:
        """The workspace's webhook subscriptions"""
        return self._call("GET", "/integrations/webhooks", {}, None, {}, None, "none", None, "json")

    def create_webhook_subscription(self, body: "WebhookSubscriptionCreate", *, idempotency_key: str | None = None) -> "WebhookSubscriptionSecret":
        """Subscribe an external system to the event stream"""
        return self._call("POST", "/integrations/webhooks", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_webhook_subscription(self, webhook_id: str) -> "WebhookSubscription":
        """One webhook subscription"""
        return self._call("GET", "/integrations/webhooks/{webhookId}", {"webhookId": webhook_id}, None, {}, None, "none", None, "json")

    def update_webhook_subscription(self, webhook_id: str, body: "WebhookSubscriptionUpdate", *, if_match: str | None = None) -> "WebhookSubscription":
        """Change a subscription"""
        return self._call("PATCH", "/integrations/webhooks/{webhookId}", {"webhookId": webhook_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_webhook_subscription(self, webhook_id: str) -> None:
        """Unsubscribe"""
        return self._call("DELETE", "/integrations/webhooks/{webhookId}", {"webhookId": webhook_id}, None, {}, None, "none", None, "void")

    def list_webhook_deliveries(self, webhook_id: str, *, query: dict[str, Any] | None = None) -> "WebhookDeliveryPage":
        """What was delivered, and what happened to it"""
        return self._call("GET", "/integrations/webhooks/{webhookId}/deliveries", {"webhookId": webhook_id}, query, {}, None, "none", None, "json")

    def replay_webhook_delivery(self, webhook_id: str, delivery_id: str) -> "WebhookDelivery":
        """Send a dead-lettered delivery again"""
        return self._call("POST", "/integrations/webhooks/{webhookId}/deliveries/{deliveryId}:replay", {"webhookId": webhook_id, "deliveryId": delivery_id}, None, {}, None, "none", None, "json")

    def send_webhook(self, webhook_id: str, body: "WebhookSend") -> "WebhookDelivery":
        """Deliver one event to this subscription"""
        return self._call("POST", "/integrations/webhooks/{webhookId}:send", {"webhookId": webhook_id}, None, {}, body, "json", "application/json", "json")

    def rotate_webhook_secret(self, webhook_id: str, body: "WebhookSecretRotation", *, idempotency_key: str | None = None) -> "WebhookSubscriptionSecret":
        """Issue a new signing secret"""
        return self._call("POST", "/integrations/webhooks/{webhookId}:rotate-secret", {"webhookId": webhook_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def http_request(self, body: "HttpRequestCall") -> "JobRef":
        """Call an external HTTP address"""
        return self._call("POST", "/integrations/http-requests", {}, None, {}, body, "json", "application/json", "json")

    def poll_trigger_events(self, event_type: str, *, query: dict[str, Any] | None = None) -> "TriggerEventPage":
        """The pull half of the event stream"""
        return self._call("GET", "/integrations/triggers/{eventType}", {"eventType": event_type}, query, {}, None, "none", None, "json")

    def list_calendar_feeds(self) -> dict[str, Any]:
        """GET /integrations/calendar-feeds"""
        return self._call("GET", "/integrations/calendar-feeds", {}, None, {}, None, "none", None, "json")

    def create_calendar_feed(self, body: "CalendarFeedCreate", *, idempotency_key: str | None = None) -> "CalendarFeedSecret":
        """POST /integrations/calendar-feeds"""
        return self._call("POST", "/integrations/calendar-feeds", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def revoke_calendar_feed(self, feed_id: str) -> None:
        """DELETE /integrations/calendar-feeds/{feedId}"""
        return self._call("DELETE", "/integrations/calendar-feeds/{feedId}", {"feedId": feed_id}, None, {}, None, "none", None, "void")

    def get_calendar_feed_document(self, token: str) -> bytes:
        """GET /calendar/{token}.ics"""
        return self._call("GET", "/calendar/{token}.ics", {"token": token}, None, {}, None, "none", None, "raw")

    def get_capabilities(self) -> "Capabilities":
        """Self-description of the installation"""
        return self._call("GET", "/meta/capabilities", {}, None, {}, None, "none", None, "json")

    def get_health_report(self) -> "HealthReport":
        """Deep self-diagnosis of the installation"""
        return self._call("GET", "/meta/health", {}, None, {}, None, "none", None, "json")

    def list_audit_entries(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """Query audit entries"""
        return self._call("GET", "/audit", {}, query, {}, None, "none", None, "json")

    def verify_audit_chain(self, body: dict[str, Any]) -> dict[str, Any]:
        """Verify the integrity of the audit chain"""
        return self._call("POST", "/audit:verify", {}, None, {}, body, "json", "application/json", "json")

    def export_audit_trail(self, body: "AuditExport") -> "JobRef":
        """Export the audit trail over a period"""
        return self._call("POST", "/audit:export", {}, None, {}, body, "json", "application/json", "json")

    def list_backup_targets(self) -> dict[str, Any]:
        """List the backup targets"""
        return self._call("GET", "/backup-targets", {}, None, {}, None, "none", None, "json")

    def create_backup_target(self, body: "BackupTargetCreate") -> "BackupTarget":
        """Create a backup target"""
        return self._call("POST", "/backup-targets", {}, None, {}, body, "json", "application/json", "json")

    def delete_backup_target(self, target_id: str) -> None:
        """Remove a backup target from the workspace's configuration"""
        return self._call("DELETE", "/backup-targets/{targetId}", {"targetId": target_id}, None, {}, None, "none", None, "void")

    def test_backup_target(self, target_id: str) -> "BackupTargetProbe":
        """Test the connection to the target"""
        return self._call("POST", "/backup-targets/{targetId}:test", {"targetId": target_id}, None, {}, None, "none", None, "json")

    def list_backups_at_target(self, target_id: str, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """List the backups present at the target"""
        return self._call("GET", "/backup-targets/{targetId}/backups", {"targetId": target_id}, query, {}, None, "none", None, "json")

    def list_backup_schedules(self) -> dict[str, Any]:
        """The schedules the workspace has"""
        return self._call("GET", "/backup-schedules", {}, None, {}, None, "none", None, "json")

    def create_backup_schedule(self, body: "BackupSchedule") -> "BackupSchedule":
        """Create a backup schedule"""
        return self._call("POST", "/backup-schedules", {}, None, {}, body, "json", "application/json", "json")

    def update_backup_schedule(self, schedule_id: str, body: "BackupScheduleUpdate", *, if_match: str | None = None) -> "BackupSchedule":
        """Change a schedule, or switch it off"""
        return self._call("PATCH", "/backup-schedules/{scheduleId}", {"scheduleId": schedule_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_backup_schedule(self, schedule_id: str) -> None:
        """Remove a schedule"""
        return self._call("DELETE", "/backup-schedules/{scheduleId}", {"scheduleId": schedule_id}, None, {}, None, "none", None, "void")

    def start_backup(self, body: "BackupStart") -> "JobRef":
        """Start a backup immediately"""
        return self._call("POST", "/backups", {}, None, {}, body, "json", "application/json", "json")

    def get_backup_run(self, backup_id: str) -> "BackupRun":
        """What one backup run did"""
        return self._call("GET", "/backups/{backupId}", {"backupId": backup_id}, None, {}, None, "none", None, "json")

    def verify_backup(self, backup_id: str) -> "JobRef":
        """Verify an archive at the target"""
        return self._call("POST", "/backups/{backupId}:verify", {"backupId": backup_id}, None, {}, None, "none", None, "json")

    def start_restore(self, body: "RestoreRequest") -> "JobRef":
        """Start a restore"""
        return self._call("POST", "/restores", {}, None, {}, body, "json", "application/json", "json")

    def get_restore_run(self, restore_id: str) -> "RestoreRun":
        """What one restore did, or is about to do"""
        return self._call("GET", "/restores/{restoreId}", {"restoreId": restore_id}, None, {}, None, "none", None, "json")

    def get_job(self, job_id: str) -> "Job":
        """How a piece of background work is getting on"""
        return self._call("GET", "/jobs/{jobId}", {"jobId": job_id}, None, {}, None, "none", None, "json")

    def cancel_job(self, job_id: str, *, idempotency_key: str | None = None) -> "Job":
        """Stop a piece of background work"""
        return self._call("POST", "/jobs/{jobId}:cancel", {"jobId": job_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_trash(self, *, query: dict[str, Any] | None = None) -> "TrashPage":
        """What is in the trash"""
        return self._call("GET", "/trash", {}, query, {}, None, "none", None, "json")

    def empty_trash(self, *, idempotency_key: str | None = None) -> "PurgeSummary":
        """Remove everything in the trash for good"""
        return self._call("POST", "/trash:empty", {}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_legal_holds(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """The legal holds in force"""
        return self._call("GET", "/legal-holds", {}, query, {}, None, "none", None, "json")

    def place_legal_hold(self, body: "LegalHoldCreate") -> "LegalHold":
        """Place a legal hold"""
        return self._call("POST", "/legal-holds", {}, None, {}, body, "json", "application/json", "json")

    def release_legal_hold(self, hold_id: str, body: "LegalHoldRelease") -> "LegalHold":
        """Lift a legal hold"""
        return self._call("POST", "/legal-holds/{holdId}:release", {"holdId": hold_id}, None, {}, body, "json", "application/json", "json")

    def list_retention_policies(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """List the retention rules"""
        return self._call("GET", "/retention-policies", {}, query, {}, None, "none", None, "json")

    def create_retention_policy(self, body: "RetentionPolicy") -> "RetentionPolicy":
        """Create a retention rule"""
        return self._call("POST", "/retention-policies", {}, None, {}, body, "json", "application/json", "json")

    def update_retention_policy(self, policy_id: str, body: "RetentionPolicyUpdate", *, if_match: str | None = None) -> "RetentionPolicy":
        """Correct a retention rule, or take it out of enforcement"""
        return self._call("PATCH", "/retention-policies/{policyId}", {"policyId": policy_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_retention_policy(self, policy_id: str) -> None:
        """Withdraw a retention rule"""
        return self._call("DELETE", "/retention-policies/{policyId}", {"policyId": policy_id}, None, {}, None, "none", None, "void")

    def preview_retention_policy(self, policy_id: str) -> dict[str, Any]:
        """Determine the effect of a rule without executing it"""
        return self._call("POST", "/retention-policies/{policyId}:preview", {"policyId": policy_id}, None, {}, None, "none", None, "json")

    def retain_item(self, item_id: str) -> "WorkItem":
        """Take an object out of the running retention period"""
        return self._call("POST", "/items/{itemId}:retain", {"itemId": item_id}, None, {}, None, "none", None, "json")

    def sync_pull(self, body: "SyncPullRequest") -> "SyncPullResponse":
        """Fetch the changes since the cursor"""
        return self._call("POST", "/sync:pull", {}, None, {}, body, "json", "application/json", "json")

    def sync_snapshot(self, body: "SyncSnapshotRequest") -> bytes:
        """The initial synchronisation as one stream"""
        return self._call("POST", "/sync:snapshot", {}, None, {}, body, "json", "application/json", "raw")

    def sync_push(self, body: "SyncPushRequest") -> "SyncPushResponse":
        """Transmit local mutations"""
        return self._call("POST", "/sync:push", {}, None, {}, body, "json", "application/json", "json")

    def list_sync_devices(self) -> dict[str, Any]:
        """List your own devices"""
        return self._call("GET", "/sync/devices", {}, None, {}, None, "none", None, "json")

    def forget_sync_device(self, device_id: str) -> None:
        """Forget one of your devices"""
        return self._call("DELETE", "/sync/devices/{deviceId}", {"deviceId": device_id}, None, {}, None, "none", None, "void")

    def invite_account(self, body: "AccountInvite", *, idempotency_key: str | None = None) -> "Account":
        """Invite a person into this workspace"""
        return self._call("POST", "/accounts:invite", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_own_account(self) -> "Account":
        """The account the caller is signed in as"""
        return self._call("GET", "/accounts/me", {}, None, {}, None, "none", None, "json")

    def get_account(self, account_id: str) -> "AccountSummary":
        """The name behind an account identifier"""
        return self._call("GET", "/accounts/{accountId}", {"accountId": account_id}, None, {}, None, "none", None, "json")

    def update_account_preferences(self, account_id: str, body: "AccountPreferences") -> "Account":
        """Set how the product speaks to an account"""
        return self._call("PATCH", "/accounts/{accountId}/preferences", {"accountId": account_id}, None, {}, body, "json", "application/merge-patch+json", "json")

    def list_notification_preferences(self, account_id: str) -> "NotificationPreferenceList":
        """What an account wants to be told about"""
        return self._call("GET", "/accounts/{accountId}/notification-preferences", {"accountId": account_id}, None, {}, None, "none", None, "json")

    def set_notification_preference(self, account_id: str, category: str, channel: str, body: "NotificationPreferenceUpdate") -> "NotificationPreference":
        """Say what to be told about, and whether the title travels"""
        return self._call("PUT", "/accounts/{accountId}/notification-preferences/{category}/{channel}", {"accountId": account_id, "category": category, "channel": channel}, None, {}, body, "json", "application/json", "json")

    def sign_in(self, body: "SignIn") -> "SessionTokens":
        """Sign in with email and password"""
        return self._call("POST", "/auth/sessions", {}, None, {}, body, "json", "application/json", "json")

    def list_sessions(self) -> dict[str, Any]:
        """The caller's active sessions"""
        return self._call("GET", "/auth/sessions", {}, None, {}, None, "none", None, "json")

    def revoke_all_sessions(self) -> None:
        """Sign out everywhere"""
        return self._call("DELETE", "/auth/sessions", {}, None, {}, None, "none", None, "void")

    def refresh_session(self, body: "SessionRefresh") -> "SessionTokens":
        """Exchange a refresh token for the next pair"""
        return self._call("POST", "/auth/sessions:refresh", {}, None, {}, body, "json", "application/json", "json")

    def revoke_session(self, session_id: str) -> None:
        """End one session"""
        return self._call("DELETE", "/auth/sessions/{sessionId}", {"sessionId": session_id}, None, {}, None, "none", None, "void")

    def redeem_invitation(self, body: "InvitationRedemption") -> "SessionTokens":
        """Redeem an invitation and set the first password"""
        return self._call("POST", "/auth/invitations:redeem", {}, None, {}, body, "json", "application/json", "json")

    def complete_sign_in(self, body: "SignInCompletion") -> "SessionTokens":
        """Present the second factor and receive the pair"""
        return self._call("POST", "/auth/sessions:verify", {}, None, {}, body, "json", "application/json", "json")

    def enroll_totp(self, body: "TotpEnrollmentStart") -> "TotpEnrollment":
        """Begin TOTP enrolment"""
        return self._call("POST", "/auth/mfa/totp:enroll", {}, None, {}, body, "json", "application/json", "json")

    def confirm_totp(self, body: "TotpConfirmation") -> "TotpConfirmed":
        """Confirm enrolment with a first valid code"""
        return self._call("POST", "/auth/mfa/totp:confirm", {}, None, {}, body, "json", "application/json", "json")

    def step_up(self, body: "StepUpRequest") -> "StepUpGrant":
        """Prove yourself again, for the irreversible"""
        return self._call("POST", "/auth/step-up", {}, None, {}, body, "json", "application/json", "json")

    def disable_totp(self, body: "MfaDisable") -> None:
        """Disable the second factor"""
        return self._call("POST", "/auth/mfa:disable", {}, None, {}, body, "json", "application/json", "void")

    def list_access_tokens(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """The caller's own personal access tokens"""
        return self._call("GET", "/auth/tokens", {}, query, {}, None, "none", None, "json")

    def create_access_token(self, body: "AccessTokenCreate", *, idempotency_key: str | None = None, step_up: str | None = None) -> "AccessTokenSecret":
        """Mint a personal access token"""
        return self._call("POST", "/auth/tokens", {}, None, {"Idempotency-Key": idempotency_key, "X-Hubtask-Step-Up": step_up}, body, "json", "application/json", "json")

    def revoke_access_token(self, token_id: str) -> None:
        """Revoke a personal access token"""
        return self._call("DELETE", "/auth/tokens/{tokenId}", {"tokenId": token_id}, None, {}, None, "none", None, "void")

    def list_service_accounts(self) -> dict[str, Any]:
        """The workspace's service accounts"""
        return self._call("GET", "/auth/service-accounts", {}, None, {}, None, "none", None, "json")

    def create_service_account(self, body: "ServiceAccountCreate", *, idempotency_key: str | None = None) -> "Account":
        """Create a service account"""
        return self._call("POST", "/auth/service-accounts", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def start_oidc_sign_in(self, body: "OidcStart") -> "OidcAuthorization":
        """Begin a sign-in through the workspace's identity provider"""
        return self._call("POST", "/auth/oidc:start", {}, None, {}, body, "json", "application/json", "json")

    def complete_oidc_sign_in(self, body: "OidcCallback") -> "SessionTokens":
        """Finish the sign-in with the code the provider issued"""
        return self._call("POST", "/auth/oidc:callback", {}, None, {}, body, "json", "application/json", "json")

    def list_tenants(self) -> dict[str, Any]:
        """The installation's workspaces"""
        return self._call("GET", "/admin/tenants", {}, None, {}, None, "none", None, "json")

    def provision_tenant(self, body: "TenantProvision", *, idempotency_key: str | None = None) -> "ProvisionedTenant":
        """Provision a workspace"""
        return self._call("POST", "/admin/tenants", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def suspend_tenant(self, tenant_id: str) -> None:
        """Suspend a workspace"""
        return self._call("POST", "/admin/tenants/{tenantId}:suspend", {"tenantId": tenant_id}, None, {}, None, "none", None, "void")

    def resume_tenant(self, tenant_id: str) -> None:
        """Reactivate a workspace"""
        return self._call("POST", "/admin/tenants/{tenantId}:resume", {"tenantId": tenant_id}, None, {}, None, "none", None, "void")

    def request_tenant_deletion(self, tenant_id: str, body: "TenantDeletionRequest", *, step_up: str | None = None) -> "TenantDeletionScheduled":
        """Request a workspace's deletion"""
        return self._call("POST", "/admin/tenants/{tenantId}:delete", {"tenantId": tenant_id}, None, {"X-Hubtask-Step-Up": step_up}, body, "json", "application/json", "json")

    def export_tenant(self, tenant_id: str, body: "TenantExportRequest") -> "JobRef":
        """Export a workspace whole"""
        return self._call("POST", "/admin/tenants/{tenantId}:export", {"tenantId": tenant_id}, None, {}, body, "json", "application/json", "json")

    def read_encryption_status(self) -> "EncryptionStatus":
        """The keyring, and what still names each key"""
        return self._call("GET", "/admin/encryption", {}, None, {}, None, "none", None, "json")

    def reseal_secrets(self) -> "ResealAccepted":
        """Re-seal what older keys still hold"""
        return self._call("POST", "/admin/encryption:reseal", {}, None, {}, None, "none", None, "json")

    def update_tenant_quotas(self, tenant_id: str, body: "TenantQuotas") -> dict[str, Any]:
        """Set a workspace's quotas"""
        return self._call("PATCH", "/admin/tenants/{tenantId}/quotas", {"tenantId": tenant_id}, None, {}, body, "json", "application/merge-patch+json", "json")

    def read_quotas(self) -> dict[str, Any]:
        """The workspace's quota standing"""
        return self._call("GET", "/quotas", {}, None, {}, None, "none", None, "json")

    def read_workspace(self) -> "Workspace":
        """The workspace the caller is in, and how it is set up"""
        return self._call("GET", "/tenant", {}, None, {}, None, "none", None, "json")

    def update_workspace(self, body: "WorkspaceUpdate", *, if_match: str | None = None) -> "Workspace":
        """Change how the workspace is set up"""
        return self._call("PATCH", "/tenant", {}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def read_identity_provider(self) -> "IdentityProvider":
        """How this workspace signs people in through its own provider"""
        return self._call("GET", "/identity-provider", {}, None, {}, None, "none", None, "json")

    def configure_identity_provider(self, body: "IdentityProviderConfiguration") -> "IdentityProvider":
        """Configure the workspace's identity provider"""
        return self._call("PUT", "/identity-provider", {}, None, {}, body, "json", "application/json", "json")

    def remove_identity_provider(self) -> None:
        """Remove the workspace's identity provider"""
        return self._call("DELETE", "/identity-provider", {}, None, {}, None, "none", None, "void")

    def suggest_decomposition(self, item_id: str, *, idempotency_key: str | None = None) -> None:
        """Ask AI what work sits under this entry"""
        return self._call("POST", "/items/{itemId}:decompose", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "void")

    def ai_suggest_fields(self, item_id: str, body: "AiAsk") -> None:
        """Ask AI to propose this entry's fields"""
        return self._call("POST", "/items/{itemId}:suggest-fields", {"itemId": item_id}, None, {}, body, "json", "application/json", "void")

    def ai_summarize(self, item_id: str, body: "AiAsk") -> None:
        """Ask AI to summarise this entry"""
        return self._call("POST", "/items/{itemId}:summarize", {"itemId": item_id}, None, {}, body, "json", "application/json", "void")

    def ai_translate(self, item_id: str, body: "AiTranslateRequest") -> "AiTranslation":
        """Read this entry in another language"""
        return self._call("POST", "/items/{itemId}:translate", {"itemId": item_id}, None, {}, body, "json", "application/json", "json")

    def ai_classify(self, item_id: str, body: "AiAsk") -> None:
        """Ask AI to propose labels for this entry"""
        return self._call("POST", "/items/{itemId}:classify", {"itemId": item_id}, None, {}, body, "json", "application/json", "void")

    def ai_summarize_thread(self, item_id: str, body: "AiAsk") -> None:
        """Ask AI to summarise this entry's discussion"""
        return self._call("POST", "/items/{itemId}:summarize-thread", {"itemId": item_id}, None, {}, body, "json", "application/json", "void")

    def ai_summarize_container(self, container_id: str, body: "AiAsk") -> None:
        """Ask AI how a collection stands"""
        return self._call("POST", "/containers/{containerId}:summarize", {"containerId": container_id}, None, {}, body, "json", "application/json", "void")

    def suggest_duplicates(self, item_id: str) -> "Suggestion":
        """Which entries look like this one"""
        return self._call("POST", "/items/{itemId}:duplicates", {"itemId": item_id}, None, {}, None, "none", None, "json")

    def list_suggestions(self, *, query: dict[str, Any] | None = None) -> "SuggestionPage":
        """What AI has proposed, and not done"""
        return self._call("GET", "/suggestions", {}, query, {}, None, "none", None, "json")

    def accept_suggestion(self, suggestion_id: str, body: "SuggestionAcceptance") -> "Suggestion":
        """Accept a suggestion"""
        return self._call("POST", "/suggestions/{suggestionId}:accept", {"suggestionId": suggestion_id}, None, {}, body, "json", "application/json", "json")

    def dismiss_suggestion(self, suggestion_id: str) -> "Suggestion":
        """Dismiss a suggestion"""
        return self._call("POST", "/suggestions/{suggestionId}:dismiss", {"suggestionId": suggestion_id}, None, {}, None, "none", None, "json")

    def read_ai_provider(self) -> "AiProvider":
        """The workspace's AI provider, and whether it may be used"""
        return self._call("GET", "/ai-provider", {}, None, {}, None, "none", None, "json")

    def configure_ai_provider(self, body: "AiProviderConfiguration") -> "AiProvider":
        """Configure the workspace's AI provider"""
        return self._call("PUT", "/ai-provider", {}, None, {}, body, "json", "application/json", "json")

    def remove_ai_provider(self) -> None:
        """Remove the workspace's AI provider"""
        return self._call("DELETE", "/ai-provider", {}, None, {}, None, "none", None, "void")

    def list_oauth_clients(self) -> dict[str, Any]:
        """The workspace's registered third-party apps"""
        return self._call("GET", "/oauth/clients", {}, None, {}, None, "none", None, "json")

    def register_oauth_client(self, body: "OauthClientCreate", *, idempotency_key: str | None = None) -> "OauthClientSecret":
        """Register a third-party app"""
        return self._call("POST", "/oauth/clients", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def read_oauth_client(self, client_id: str) -> "OauthClientSummary":
        """What an app is called, for the person being asked to allow it"""
        return self._call("GET", "/oauth/clients/{clientId}", {"clientId": client_id}, None, {}, None, "none", None, "json")

    def delete_oauth_client(self, client_id: str) -> None:
        """Remove a third-party app"""
        return self._call("DELETE", "/oauth/clients/{clientId}", {"clientId": client_id}, None, {}, None, "none", None, "void")

    def authorize_oauth_client(self, body: "OauthAuthorization") -> "OauthCode":
        """Consent to an app's request for bounded access"""
        return self._call("POST", "/oauth/authorize", {}, None, {}, body, "json", "application/json", "json")

    def exchange_oauth_code(self, body: "OauthTokenRequest") -> "SessionTokens":
        """Exchange the code for the pair"""
        return self._call("POST", "/oauth/token", {}, None, {}, body, "json", "application/json", "json")

    def list_oauth_grants(self) -> dict[str, Any]:
        """The apps the caller has allowed, and what"""
        return self._call("GET", "/oauth/grants", {}, None, {}, None, "none", None, "json")

    def revoke_oauth_grant(self, grant_id: str) -> None:
        """Withdraw what an app was allowed"""
        return self._call("DELETE", "/oauth/grants/{grantId}", {"grantId": grant_id}, None, {}, None, "none", None, "void")

    def list_data_subject_requests(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """The data subject requests this workspace is handling"""
        return self._call("GET", "/privacy/requests", {}, query, {}, None, "none", None, "json")

    def create_data_subject_request(self, body: "DataSubjectRequestCreate", *, idempotency_key: str | None = None) -> "DataSubjectRequest":
        """Record a right somebody has exercised"""
        return self._call("POST", "/privacy/requests", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def update_data_subject_request(self, request_id: str, body: "DataSubjectRequestUpdate") -> "DataSubjectRequest":
        """Move a case along"""
        return self._call("PATCH", "/privacy/requests/{requestId}", {"requestId": request_id}, None, {}, body, "json", "application/merge-patch+json", "json")

    def restrict_processing(self, account_id: str, body: "ProcessingRestriction") -> "ProcessingState":
        """Restrict the processing of an account's data (Art. 18)"""
        return self._call("POST", "/accounts/{accountId}:restrict", {"accountId": account_id}, None, {}, body, "json", "application/json", "json")

    def withdraw_consent(self, body: "ConsentWithdrawal") -> "ConsentRecord":
        """Withdraw consent for an optional processing purpose (Art. 21)"""
        return self._call("POST", "/privacy/consents:withdraw", {}, None, {}, body, "json", "application/json", "json")

    def list_memberships(self, *, query: dict[str, Any] | None = None) -> "MembershipPage":
        """Who holds a role at a scope"""
        return self._call("GET", "/memberships", {}, query, {}, None, "none", None, "json")

    def grant_membership(self, body: "MembershipGrant", *, idempotency_key: str | None = None, step_up: str | None = None) -> "Membership":
        """Grant a role at a scope"""
        return self._call("POST", "/memberships", {}, None, {"Idempotency-Key": idempotency_key, "X-Hubtask-Step-Up": step_up}, body, "json", "application/json", "json")

    def revoke_membership(self, membership_id: str, *, step_up: str | None = None) -> None:
        """Take a role away"""
        return self._call("DELETE", "/memberships/{membershipId}", {"membershipId": membership_id}, None, {"X-Hubtask-Step-Up": step_up}, None, "none", None, "void")

    def list_groups(self, *, query: dict[str, Any] | None = None) -> "GroupPage":
        """The workspace's groups"""
        return self._call("GET", "/groups", {}, query, {}, None, "none", None, "json")

    def create_group(self, body: "GroupCreate", *, idempotency_key: str | None = None) -> "Group":
        """Create a group"""
        return self._call("POST", "/groups", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_group(self, group_id: str) -> "GroupDetail":
        """One group, with who is in it"""
        return self._call("GET", "/groups/{groupId}", {"groupId": group_id}, None, {}, None, "none", None, "json")

    def update_group(self, group_id: str, body: "GroupUpdate", *, if_match: str | None = None) -> "Group":
        """Rename a group or change its description"""
        return self._call("PATCH", "/groups/{groupId}", {"groupId": group_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_group(self, group_id: str) -> None:
        """Delete a group"""
        return self._call("DELETE", "/groups/{groupId}", {"groupId": group_id}, None, {}, None, "none", None, "void")

    def list_containers(self, *, query: dict[str, Any] | None = None) -> "ContainerPage":
        """GET /containers"""
        return self._call("GET", "/containers", {}, query, {}, None, "none", None, "json")

    def create_container(self, body: "ContainerCreate", *, idempotency_key: str | None = None) -> "Container":
        """POST /containers"""
        return self._call("POST", "/containers", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_container(self, container_id: str) -> "Container":
        """GET /containers/{containerId}"""
        return self._call("GET", "/containers/{containerId}", {"containerId": container_id}, None, {}, None, "none", None, "json")

    def rename_container(self, container_id: str, body: "ContainerUpdate", *, if_match: str | None = None) -> "Container":
        """PATCH /containers/{containerId}"""
        return self._call("PATCH", "/containers/{containerId}", {"containerId": container_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def trash_container(self, container_id: str, *, if_match: str | None = None) -> None:
        """DELETE /containers/{containerId}"""
        return self._call("DELETE", "/containers/{containerId}", {"containerId": container_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def update_container_policies(self, container_id: str, body: "ContainerPolicies", *, if_match: str | None = None) -> "Container":
        """PUT /containers/{containerId}/policies"""
        return self._call("PUT", "/containers/{containerId}/policies", {"containerId": container_id}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def move_container(self, container_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "Container":
        """POST /containers/{containerId}:move"""
        return self._call("POST", "/containers/{containerId}:move", {"containerId": container_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def reorder_container(self, container_id: str, body: dict[str, Any], *, idempotency_key: str | None = None, if_match: str | None = None) -> "Container":
        """POST /containers/{containerId}:reorder"""
        return self._call("POST", "/containers/{containerId}:reorder", {"containerId": container_id}, None, {"Idempotency-Key": idempotency_key, "If-Match": if_match}, body, "json", "application/json", "json")

    def restore_container(self, container_id: str, *, idempotency_key: str | None = None) -> "Container":
        """POST /containers/{containerId}:restore"""
        return self._call("POST", "/containers/{containerId}:restore", {"containerId": container_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def archive_container(self, container_id: str, *, idempotency_key: str | None = None) -> "Container":
        """POST /containers/{containerId}:archive"""
        return self._call("POST", "/containers/{containerId}:archive", {"containerId": container_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def unarchive_container(self, container_id: str, *, idempotency_key: str | None = None) -> "Container":
        """POST /containers/{containerId}:unarchive"""
        return self._call("POST", "/containers/{containerId}:unarchive", {"containerId": container_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_work_items(self, *, query: dict[str, Any] | None = None) -> "WorkItemPage":
        """GET /items"""
        return self._call("GET", "/items", {}, query, {}, None, "none", None, "json")

    def create_work_item(self, body: "WorkItemCreate", *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items"""
        return self._call("POST", "/items", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_work_item(self, item_id: str, *, query: dict[str, Any] | None = None) -> "WorkItem":
        """GET /items/{itemId}"""
        return self._call("GET", "/items/{itemId}", {"itemId": item_id}, query, {}, None, "none", None, "json")

    def update_work_item(self, item_id: str, body: "WorkItemUpdate", *, if_match: str | None = None) -> "WorkItem":
        """PATCH /items/{itemId}"""
        return self._call("PATCH", "/items/{itemId}", {"itemId": item_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def trash_work_item(self, item_id: str, *, if_match: str | None = None) -> None:
        """DELETE /items/{itemId}"""
        return self._call("DELETE", "/items/{itemId}", {"itemId": item_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def query_items(self, body: "ItemQuery") -> "ItemQueryResult":
        """The generic query - the basis for list, kanban, and timeline"""
        return self._call("POST", "/items:query", {}, None, {}, body, "json", "application/json", "json")

    def search_items(self, body: "ItemSearchQuery") -> "WorkItemPage":
        """Full-text search over the entries a caller may see"""
        return self._call("POST", "/search", {}, None, {}, body, "json", "application/json", "json")

    def reindex_search(self) -> "SearchReindex":
        """Bring the workspace's search documents current"""
        return self._call("POST", "/search:reindex", {}, None, {}, None, "none", None, "json")

    def complete_work_item(self, item_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:complete"""
        return self._call("POST", "/items/{itemId}:complete", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def reopen_work_item(self, item_id: str, *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:reopen"""
        return self._call("POST", "/items/{itemId}:reopen", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def assign_work_item(self, item_id: str, body: "Assignment", *, idempotency_key: str | None = None, if_match: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:assign"""
        return self._call("POST", "/items/{itemId}:assign", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key, "If-Match": if_match}, body, "json", "application/json", "json")

    def unassign_work_item(self, item_id: str, *, idempotency_key: str | None = None, if_match: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:unassign"""
        return self._call("POST", "/items/{itemId}:unassign", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key, "If-Match": if_match}, None, "none", None, "json")

    def auto_assign_work_item(self, item_id: str, *, idempotency_key: str | None = None, if_match: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:auto-assign"""
        return self._call("POST", "/items/{itemId}:auto-assign", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key, "If-Match": if_match}, None, "none", None, "json")

    def purge_work_item(self, item_id: str, *, idempotency_key: str | None = None) -> None:
        """POST /items/{itemId}:purge"""
        return self._call("POST", "/items/{itemId}:purge", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "void")

    def restore_work_item(self, item_id: str, *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:restore"""
        return self._call("POST", "/items/{itemId}:restore", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def archive_work_item(self, item_id: str, *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:archive"""
        return self._call("POST", "/items/{itemId}:archive", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def unarchive_work_item(self, item_id: str, *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:unarchive"""
        return self._call("POST", "/items/{itemId}:unarchive", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def reorder_work_item(self, item_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "WorkItem":
        """POST /items/{itemId}:reorder"""
        return self._call("POST", "/items/{itemId}:reorder", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def move_work_item(self, item_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "MoveResult":
        """POST /items/{itemId}:move"""
        return self._call("POST", "/items/{itemId}:move", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def duplicate_work_item(self, item_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "DuplicateResult":
        """POST /items/{itemId}:duplicate"""
        return self._call("POST", "/items/{itemId}:duplicate", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def bulk_update_work_items(self, body: dict[str, Any], *, idempotency_key: str | None = None) -> dict[str, Any]:
        """POST /items:bulk"""
        return self._call("POST", "/items:bulk", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def list_comments(self, item_id: str, *, query: dict[str, Any] | None = None) -> "CommentPage":
        """GET /items/{itemId}/comments"""
        return self._call("GET", "/items/{itemId}/comments", {"itemId": item_id}, query, {}, None, "none", None, "json")

    def add_comment(self, item_id: str, body: dict[str, Any], *, idempotency_key: str | None = None) -> "Comment":
        """POST /items/{itemId}/comments"""
        return self._call("POST", "/items/{itemId}/comments", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def edit_comment(self, item_id: str, comment_id: str, body: dict[str, Any], *, if_match: str | None = None) -> "Comment":
        """PATCH /items/{itemId}/comments/{commentId}"""
        return self._call("PATCH", "/items/{itemId}/comments/{commentId}", {"itemId": item_id, "commentId": comment_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_comment(self, item_id: str, comment_id: str, *, if_match: str | None = None) -> None:
        """DELETE /items/{itemId}/comments/{commentId}"""
        return self._call("DELETE", "/items/{itemId}/comments/{commentId}", {"itemId": item_id, "commentId": comment_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def list_activity(self, item_id: str, *, query: dict[str, Any] | None = None) -> "ActivityPage":
        """GET /items/{itemId}/activity"""
        return self._call("GET", "/items/{itemId}/activity", {"itemId": item_id}, query, {}, None, "none", None, "json")

    def list_buckets(self, container_id: str) -> dict[str, Any]:
        """GET /containers/{containerId}/buckets"""
        return self._call("GET", "/containers/{containerId}/buckets", {"containerId": container_id}, None, {}, None, "none", None, "json")

    def create_bucket(self, container_id: str, body: "BucketCreate") -> "Bucket":
        """POST /containers/{containerId}/buckets"""
        return self._call("POST", "/containers/{containerId}/buckets", {"containerId": container_id}, None, {}, body, "json", "application/json", "json")

    def update_bucket(self, container_id: str, bucket_id: str, body: "BucketUpdate", *, if_match: str | None = None) -> "Bucket":
        """PATCH /containers/{containerId}/buckets/{bucketId}"""
        return self._call("PATCH", "/containers/{containerId}/buckets/{bucketId}", {"containerId": container_id, "bucketId": bucket_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_bucket(self, container_id: str, bucket_id: str, *, if_match: str | None = None) -> "BucketDeletion":
        """DELETE /containers/{containerId}/buckets/{bucketId}"""
        return self._call("DELETE", "/containers/{containerId}/buckets/{bucketId}", {"containerId": container_id, "bucketId": bucket_id}, None, {"If-Match": if_match}, None, "none", None, "json")

    def reorder_bucket(self, container_id: str, bucket_id: str, body: dict[str, Any], *, if_match: str | None = None) -> "Bucket":
        """POST /containers/{containerId}/buckets/{bucketId}:reorder"""
        return self._call("POST", "/containers/{containerId}/buckets/{bucketId}:reorder", {"containerId": container_id, "bucketId": bucket_id}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def list_labels(self, container_id: str) -> dict[str, Any]:
        """GET /containers/{containerId}/labels"""
        return self._call("GET", "/containers/{containerId}/labels", {"containerId": container_id}, None, {}, None, "none", None, "json")

    def create_label(self, container_id: str, body: "LabelCreate") -> "Label":
        """POST /containers/{containerId}/labels"""
        return self._call("POST", "/containers/{containerId}/labels", {"containerId": container_id}, None, {}, body, "json", "application/json", "json")

    def update_label(self, container_id: str, label_id: str, body: "LabelUpdate", *, if_match: str | None = None) -> "Label":
        """PATCH /containers/{containerId}/labels/{labelId}"""
        return self._call("PATCH", "/containers/{containerId}/labels/{labelId}", {"containerId": container_id, "labelId": label_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_label(self, container_id: str, label_id: str, *, if_match: str | None = None) -> None:
        """DELETE /containers/{containerId}/labels/{labelId}"""
        return self._call("DELETE", "/containers/{containerId}/labels/{labelId}", {"containerId": container_id, "labelId": label_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def add_label(self, item_id: str, label_id: str) -> "ItemLabels":
        """PUT /items/{itemId}/labels/{labelId}"""
        return self._call("PUT", "/items/{itemId}/labels/{labelId}", {"itemId": item_id, "labelId": label_id}, None, {}, None, "none", None, "json")

    def remove_label(self, item_id: str, label_id: str) -> "ItemLabels":
        """DELETE /items/{itemId}/labels/{labelId}"""
        return self._call("DELETE", "/items/{itemId}/labels/{labelId}", {"itemId": item_id, "labelId": label_id}, None, {}, None, "none", None, "json")

    def add_member(self, item_id: str, account_id: str) -> "ItemMembers":
        """PUT /items/{itemId}/members/{accountId}"""
        return self._call("PUT", "/items/{itemId}/members/{accountId}", {"itemId": item_id, "accountId": account_id}, None, {}, None, "none", None, "json")

    def remove_member(self, item_id: str, account_id: str) -> "ItemMembers":
        """DELETE /items/{itemId}/members/{accountId}"""
        return self._call("DELETE", "/items/{itemId}/members/{accountId}", {"itemId": item_id, "accountId": account_id}, None, {}, None, "none", None, "json")

    def list_custom_fields(self, *, query: dict[str, Any] | None = None) -> dict[str, Any]:
        """GET /custom-fields"""
        return self._call("GET", "/custom-fields", {}, query, {}, None, "none", None, "json")

    def define_custom_field(self, body: "CustomFieldDefinitionCreate", *, idempotency_key: str | None = None) -> "CustomFieldDefinition":
        """POST /custom-fields"""
        return self._call("POST", "/custom-fields", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def update_custom_field(self, field_id: str, body: "CustomFieldDefinitionUpdate", *, if_match: str | None = None) -> "CustomFieldDefinition":
        """PATCH /custom-fields/{fieldId}"""
        return self._call("PATCH", "/custom-fields/{fieldId}", {"fieldId": field_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_custom_field(self, field_id: str, *, if_match: str | None = None) -> None:
        """DELETE /custom-fields/{fieldId}"""
        return self._call("DELETE", "/custom-fields/{fieldId}", {"fieldId": field_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def set_custom_field(self, item_id: str, key: str, body: "CustomFieldValue", *, if_match: str | None = None) -> "WorkItem":
        """PUT /items/{itemId}/custom-fields/{key}"""
        return self._call("PUT", "/items/{itemId}/custom-fields/{key}", {"itemId": item_id, "key": key}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def set_cover(self, item_id: str, body: "CoverInput", *, if_match: str | None = None) -> "WorkItem":
        """PUT /items/{itemId}/cover"""
        return self._call("PUT", "/items/{itemId}/cover", {"itemId": item_id}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def clear_cover(self, item_id: str, *, if_match: str | None = None) -> "WorkItem":
        """DELETE /items/{itemId}/cover"""
        return self._call("DELETE", "/items/{itemId}/cover", {"itemId": item_id}, None, {"If-Match": if_match}, None, "none", None, "json")

    def set_due_date(self, item_id: str, body: "DueDateInput", *, if_match: str | None = None) -> "WorkItem":
        """PUT /items/{itemId}/due"""
        return self._call("PUT", "/items/{itemId}/due", {"itemId": item_id}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def clear_due_date(self, item_id: str, *, if_match: str | None = None) -> "WorkItem":
        """DELETE /items/{itemId}/due"""
        return self._call("DELETE", "/items/{itemId}/due", {"itemId": item_id}, None, {"If-Match": if_match}, None, "none", None, "json")

    def get_recurrence(self, item_id: str) -> "Recurrence":
        """GET /items/{itemId}/recurrence"""
        return self._call("GET", "/items/{itemId}/recurrence", {"itemId": item_id}, None, {}, None, "none", None, "json")

    def set_recurrence(self, item_id: str, body: "RecurrenceInput", *, if_match: str | None = None) -> "Recurrence":
        """PUT /items/{itemId}/recurrence"""
        return self._call("PUT", "/items/{itemId}/recurrence", {"itemId": item_id}, None, {"If-Match": if_match}, body, "json", "application/json", "json")

    def remove_recurrence(self, item_id: str, *, if_match: str | None = None) -> None:
        """DELETE /items/{itemId}/recurrence"""
        return self._call("DELETE", "/items/{itemId}/recurrence", {"itemId": item_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def skip_occurrence(self, item_id: str, *, idempotency_key: str | None = None) -> "Recurrence":
        """POST /items/{itemId}/recurrence:skip"""
        return self._call("POST", "/items/{itemId}/recurrence:skip", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def list_reminders(self, item_id: str) -> dict[str, Any]:
        """GET /items/{itemId}/reminders"""
        return self._call("GET", "/items/{itemId}/reminders", {"itemId": item_id}, None, {}, None, "none", None, "json")

    def create_reminder(self, item_id: str, body: "ReminderInput", *, idempotency_key: str | None = None) -> "Reminder":
        """POST /items/{itemId}/reminders"""
        return self._call("POST", "/items/{itemId}/reminders", {"itemId": item_id}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def update_reminder(self, item_id: str, reminder_id: str, body: "ReminderUpdate", *, if_match: str | None = None) -> "Reminder":
        """PATCH /items/{itemId}/reminders/{reminderId}"""
        return self._call("PATCH", "/items/{itemId}/reminders/{reminderId}", {"itemId": item_id, "reminderId": reminder_id}, None, {"If-Match": if_match}, body, "json", "application/merge-patch+json", "json")

    def delete_reminder(self, item_id: str, reminder_id: str, *, if_match: str | None = None) -> None:
        """DELETE /items/{itemId}/reminders/{reminderId}"""
        return self._call("DELETE", "/items/{itemId}/reminders/{reminderId}", {"itemId": item_id, "reminderId": reminder_id}, None, {"If-Match": if_match}, None, "none", None, "void")

    def list_attachments(self, item_id: str, *, query: dict[str, Any] | None = None) -> "MediaPage":
        """GET /items/{itemId}/attachments"""
        return self._call("GET", "/items/{itemId}/attachments", {"itemId": item_id}, query, {}, None, "none", None, "json")

    def attach_media(self, item_id: str, media_id: str) -> "ItemAttachments":
        """PUT /items/{itemId}/attachments/{mediaId}"""
        return self._call("PUT", "/items/{itemId}/attachments/{mediaId}", {"itemId": item_id, "mediaId": media_id}, None, {}, None, "none", None, "json")

    def detach_media(self, item_id: str, media_id: str) -> "ItemAttachments":
        """DELETE /items/{itemId}/attachments/{mediaId}"""
        return self._call("DELETE", "/items/{itemId}/attachments/{mediaId}", {"itemId": item_id, "mediaId": media_id}, None, {}, None, "none", None, "json")

    def request_media_upload(self, body: "MediaUploadRequest", *, idempotency_key: str | None = None) -> "MediaObject":
        """POST /media"""
        return self._call("POST", "/media", {}, None, {"Idempotency-Key": idempotency_key}, body, "json", "application/json", "json")

    def get_media(self, media_id: str) -> "MediaObject":
        """GET /media/{mediaId}"""
        return self._call("GET", "/media/{mediaId}", {"mediaId": media_id}, None, {}, None, "none", None, "json")

    def delete_media(self, media_id: str) -> None:
        """DELETE /media/{mediaId}"""
        return self._call("DELETE", "/media/{mediaId}", {"mediaId": media_id}, None, {}, None, "none", None, "void")

    def confirm_media_upload(self, media_id: str, *, idempotency_key: str | None = None) -> "MediaObject":
        """POST /media/{mediaId}:confirm"""
        return self._call("POST", "/media/{mediaId}:confirm", {"mediaId": media_id}, None, {"Idempotency-Key": idempotency_key}, None, "none", None, "json")

    def upload_media_content(self, media_id: str, body: bytes, *, query: dict[str, Any] | None = None) -> None:
        """PUT /media/{mediaId}:content"""
        return self._call("PUT", "/media/{mediaId}:content", {"mediaId": media_id}, query, {}, body, "raw", "application/octet-stream", "void")

    def download_media_content(self, media_id: str, *, query: dict[str, Any] | None = None) -> bytes:
        """GET /media/{mediaId}:content"""
        return self._call("GET", "/media/{mediaId}:content", {"mediaId": media_id}, query, {}, None, "none", None, "raw")

    def stream_changes(self, *, last_event_id: str | None = None) -> bytes:
        """The change stream, as server-sent events"""
        return self._call("GET", "/stream", {}, None, {"Last-Event-ID": last_event_id}, None, "none", None, "raw")
