// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Jérôme Bastian Winkel

// Command deprecations writes the table of deprecated request fields from api/openapi.yaml (SC-28).
//
// The contract marks a field `deprecated: true` with `x-deprecated-since`, `x-removed-in`, an
// optional `x-sunset` and `x-deprecated-reason`; this reads every operation whose JSON request body
// carries such a field and writes the table the REST adapter announces them from - the
// `Deprecation` and `Sunset` headers, and the manifest's `deprecations`. Generated rather than
// written, so the announcement and the specification cannot drift (ADR-0004).
//
// Usage: deprecations <openapi.yaml> <out.go>
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	// A path item holds its operations by method beside a list of shared parameters, so each entry
	// is decoded only when it is an operation.
	Paths      map[string]map[string]yaml.Node `yaml:"paths"`
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

type operation struct {
	OperationID string `yaml:"operationId"`
	RequestBody struct {
		Content map[string]struct {
			Schema schema `yaml:"schema"`
		} `yaml:"content"`
	} `yaml:"requestBody"`
}

type schema struct {
	Ref        string            `yaml:"$ref"`
	Properties map[string]schema `yaml:"properties"`
	Deprecated bool              `yaml:"deprecated"`
	Since      string            `yaml:"x-deprecated-since"`
	RemovedIn  string            `yaml:"x-removed-in"`
	Sunset     string            `yaml:"x-sunset"`
	Reason     string            `yaml:"x-deprecated-reason"`
}

type entry struct {
	OperationID, Method, Path, Field, Since, RemovedIn, Sunset, Reason string
}

var methods = []string{"get", "put", "post", "patch", "delete"}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: deprecations <openapi.yaml> <out.go>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1]) //nolint:gosec // G703: the file the Makefile names; reading it is the job
	if err != nil {
		fail(err)
	}
	var doc document
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fail(err)
	}

	var entries []entry
	for path, ops := range doc.Paths {
		for _, method := range methods {
			node, ok := ops[method]
			if !ok {
				continue
			}
			var op operation
			if err := node.Decode(&op); err != nil {
				fail(fmt.Errorf("%s %s: %w", method, path, err))
			}
			body, ok := op.RequestBody.Content["application/json"]
			if !ok {
				continue
			}
			resolved := body.Schema
			if resolved.Ref != "" {
				resolved = doc.Components.Schemas[strings.TrimPrefix(resolved.Ref, "#/components/schemas/")]
			}
			for name, property := range resolved.Properties {
				if !property.Deprecated {
					continue
				}
				if property.Since == "" || property.RemovedIn == "" || property.Reason == "" {
					fail(fmt.Errorf("%s %s: %s is deprecated without x-deprecated-since, x-removed-in and x-deprecated-reason", method, path, name))
				}
				entries = append(entries, entry{
					OperationID: op.OperationID, Method: strings.ToUpper(method), Path: path, Field: name,
					Since: property.Since, RemovedIn: property.RemovedIn, Sunset: property.Sunset,
					Reason: property.Reason,
				})
			}
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Path != entries[j].Path {
			return entries[i].Path < entries[j].Path
		}
		if entries[i].Method != entries[j].Method {
			return entries[i].Method < entries[j].Method
		}
		return entries[i].Field < entries[j].Field
	})

	var out bytes.Buffer
	out.WriteString("// Code generated by tools/deprecations from api/openapi.yaml. DO NOT EDIT.\n\n")
	out.WriteString("package rest\n\n")
	out.WriteString("// deprecatedFields is every deprecated request field the contract declares, in a stable order.\n")
	out.WriteString("var deprecatedFields = []deprecatedField{\n")
	for _, e := range entries {
		fmt.Fprintf(&out, "\t{OperationID: %q, Method: %q, Path: %q, Field: %q, Since: %q, RemovedIn: %q, Sunset: %q, Reason: %q},\n",
			e.OperationID, e.Method, e.Path, e.Field, e.Since, e.RemovedIn, e.Sunset, e.Reason)
	}
	out.WriteString("}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(os.Args[2], formatted, 0o600); err != nil { //nolint:gosec // G703: the output the Makefile names
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "deprecations:", err)
	os.Exit(1)
}
