<!-- SPDX-License-Identifier: BUSL-1.1
     Copyright (c) 2026 Jérôme Bastian Winkel -->
<script lang="ts">
  // The rule the editor produces is printed underneath: the presets and the raw field write the
  // same string, and that is the claim worth being able to check by looking.

  import RecurrenceEditor from './RecurrenceEditor.svelte';

  const { mode = 'weekly' }: { mode?: 'weekly' | 'monthly' | 'raw' | 'conflict' } = $props();

  let rule = $state('FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TH');
  let repeats = $state<'ON_SCHEDULE' | 'ON_COMPLETION'>('ON_SCHEDULE');
  let horizon = $state(12);

  $effect(() => {
    rule =
      mode === 'monthly'
        ? 'FREQ=MONTHLY;INTERVAL=1;BYMONTHDAY=15;COUNT=6'
        : mode === 'raw'
          ? 'FREQ=MONTHLY;INTERVAL=1;BYDAY=FR;BYSETPOS=-1'
          : mode === 'conflict'
            ? 'FREQ=WEEKLY;INTERVAL=1;UNTIL=20270101T000000Z;COUNT=10'
            : 'FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TH';
  });
</script>

<div>
  <RecurrenceEditor
    label="Repeats"
    {rule}
    mode={repeats}
    zone="Europe/Berlin"
    zoneLabel="Read in"
    {horizon}
    horizonLabel="Occurrences kept ahead"
    horizonHint="How far the server materialises the series. It does not change the rule."
    frequencyLabel="How often"
    frequencyLabels={{ DAILY: 'Every day', WEEKLY: 'Every week', MONTHLY: 'Every month', YEARLY: 'Every year' }}
    rawLabel="Write the rule"
    rawHint="RFC 5545, without the RRULE: prefix — FREQ=MONTHLY;BYDAY=FR;BYSETPOS=-1"
    intervalLabel="Every how many"
    weekdaysLabel="On these days"
    weekdayLabels={{ MO: 'Mon', TU: 'Tue', WE: 'Wed', TH: 'Thu', FR: 'Fri', SA: 'Sat', SU: 'Sun' }}
    weekStart="MO"
    monthDayLabel="Day of the month"
    endLabel="Until when"
    endNeverLabel="It does not stop"
    endOnLabel="On a date"
    endAfterLabel="After a number of times"
    endDateLabel="Last day"
    endCountLabel="How many times"
    endConflictLabel="A rule ends on a date or after a number of times, never both. Remove one."
    modeLabel="When the next one is due"
    onScheduleLabel="On the schedule"
    onScheduleHint="The next one is where the calendar puts it, whether or not this one was finished."
    onCompletionLabel="After it is finished"
    onCompletionHint="The next one is a period after this one was actually completed."
    sourceLabel="The occurrences are generated by the server from this rule. Nothing is expanded here."
    onChange={(next) => {
      rule = next;
    }}
    onModeChange={(next) => {
      repeats = next;
    }}
    onHorizonChange={(next) => {
      horizon = next;
    }}
  />

  <p class="produced"><code>RRULE:{rule}</code></p>
</div>

<style>
  .produced { margin-block-start: var(--sp-150); color: var(--text-subtle); font-size: var(--fs-075); }
</style>
