// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Jérôme Bastian Winkel

package main

import (
	"os"
	"strings"
	"testing"
)

const fixture = `
openapi: 3.1.0
info: { title: Fixture, version: "1" }
paths:
  /items:
    post:
      operationId: createItem
      summary: Create an entry
      parameters:
        - $ref: "#/components/parameters/IdempotencyKey"
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/ItemCreate" }
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Item" }
  /items/{itemId}:
    parameters:
      - $ref: "#/components/parameters/ItemId"
    get:
      operationId: getItem
      parameters:
        - name: expand
          in: query
          schema: { type: array, items: { type: string } }
      responses:
        "200":
          description: The entry
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Item" }
    delete:
      operationId: trashItem
      deprecated: true
      responses:
        "204": { description: Gone }
  /items/{itemId}:complete:
    parameters:
      - $ref: "#/components/parameters/ItemId"
    post:
      operationId: completeItem
      security: []
      responses:
        "200":
          description: Done
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Item" }
  /calendar/{token}.ics:
    get:
      operationId: feed
      parameters:
        - { name: token, in: path, required: true, schema: { type: string } }
      responses:
        "200":
          description: The feed
          content:
            text/calendar:
              schema: { type: string }
components:
  parameters:
    ItemId: { name: itemId, in: path, required: true, schema: { type: string, format: uuid } }
    IdempotencyKey: { name: Idempotency-Key, in: header, schema: { type: string } }
  schemas:
    ItemType: { type: string, enum: [TASK, ACTIVITY] }
    ItemCreate:
      type: object
      required: [title, type]
      properties:
        title: { type: string }
        type: { $ref: "#/components/schemas/ItemType" }
        notes: { type: [string, "null"] }
        labels: { type: array, items: { $ref: "#/components/schemas/Label" } }
        from: { type: string }
    Item:
      allOf:
        - $ref: "#/components/schemas/ItemCreate"
        - type: object
          required: [id]
          properties:
            id: { type: string, format: uuid }
            kind: { oneOf: [ { type: string }, { type: integer } ] }
    Label:
      type: object
      properties:
        id: { type: string }
        nested: { $ref: "#/components/schemas/Label" }
`

func read(t *testing.T) *Document {
	t.Helper()
	doc, err := Read([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	return doc
}

func TestTheModelReadsOperationsInOrderWithTheirParts(t *testing.T) {
	doc := read(t)
	ids := []string{}
	for _, op := range doc.Operations {
		ids = append(ids, op.ID)
	}
	if got := strings.Join(ids, ","); got != "createItem,getItem,trashItem,completeItem,feed" {
		t.Errorf("operations = %s", got)
	}
	get := doc.Operations[1]
	if len(get.PathParams) != 1 || get.PathParams[0].Name != "itemId" || !get.PathParams[0].Required {
		t.Errorf("the shared path parameter did not reach the operation: %+v", get.PathParams)
	}
	if len(get.Query) != 1 || get.Query[0].Type != "list[str]" {
		t.Errorf("query = %+v", get.Query)
	}
	create := doc.Operations[0]
	if create.Body == nil || create.Body.SchemaName != "ItemCreate" || len(create.Headers) != 1 {
		t.Errorf("create = %+v", create)
	}
	if create.Answer == nil || create.Answer.Status != "201" || create.Answer.SchemaName != "Item" {
		t.Errorf("answer = %+v", create.Answer)
	}
	if !doc.Operations[2].Deprecated || doc.Operations[2].Answer.ContentType != "" {
		t.Errorf("trash = %+v", doc.Operations[2])
	}
	if !doc.Operations[3].Public {
		t.Error("security: [] should mark the operation public")
	}
}

func TestTheTypeScriptClientIsTypedAgainstTheOperations(t *testing.T) {
	ts := GenerateTypeScript(read(t))
	for _, want := range []string{
		"// Code generated by tools/sdkgen",
		`createItem(body: NonNullable<operations["createItem"]['requestBody']>['content']["application/json"], options: CallOptions & { readonly idempotencyKey?: string } = {}): Promise<operations["createItem"]['responses'][201]['content']["application/json"]>`,
		`getItem(itemId: string, options: CallOptions & { readonly query?: NonNullable<operations["getItem"]['parameters']['query']> } = {}): Promise<operations["getItem"]['responses'][200]['content']["application/json"]>`,
		`trashItem(itemId: string, options: CallOptions = {}): Promise<void>`,
		"   * @deprecated",
		`feed(token: string, options: CallOptions = {}): Promise<Response>`,
		`this.call("POST", "/items/{itemId}:complete", { "itemId": itemId }, undefined, {  }, undefined, "none", undefined, "json", options.signal)`,
	} {
		if !strings.Contains(ts, want) {
			t.Errorf("missing in the TypeScript client:\n%s", want)
		}
	}
}

func TestThePythonClientAndTypesSpellTheContract(t *testing.T) {
	client, types := GeneratePython(read(t))
	for _, want := range []string{
		`def create_item(self, body: "ItemCreate", *, idempotency_key: str | None = None) -> "Item":`,
		`def get_item(self, item_id: str, *, query: dict[str, Any] | None = None) -> "Item":`,
		`def trash_item(self, item_id: str) -> None:`,
		`"""DELETE /items/{itemId} (deprecated)"""`,
		`def feed(self, token: str) -> bytes:`,
	} {
		if !strings.Contains(client, want) {
			t.Errorf("missing in the Python client:\n%s", want)
		}
	}
	for _, want := range []string{
		`ItemType = Literal["TASK", "ACTIVITY"]`,
		"ItemCreate = TypedDict(\"ItemCreate\", {",
		`    "from": str,`,
		`    "title": Required[str],`,
		`    "notes": str | None,`,
		`    "labels": list["Label"],`,
		"Item = TypedDict(\"Item\", {",
		`    "id": Required[str],`,
		`    "kind": int | str,`,
		"class Label(TypedDict, total=False):",
		`    nested: "Label"`,
	} {
		if !strings.Contains(types, want) {
			t.Errorf("missing in the Python types:\n%s", want)
		}
	}
}

func TestTheRealContractGenerates(t *testing.T) {
	raw, err := os.ReadFile("../../api/openapi.yaml")
	if err != nil {
		t.Skip("no specification beside the tool")
	}
	doc, err := Read(raw)
	if err != nil {
		t.Fatal(err)
	}
	ts := GenerateTypeScript(doc)
	client, _ := GeneratePython(doc)
	for _, op := range doc.Operations {
		if !strings.Contains(ts, "  "+op.ID+"(") {
			t.Errorf("%s has no TypeScript method", op.ID)
		}
		if !strings.Contains(client, "    def "+pyName(op.ID)+"(") {
			t.Errorf("%s has no Python method", op.ID)
		}
	}
}
