// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Activity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActivity = `-- name: ListActivity :many
SELECT id, item_id, container_id, actor_type, actor_id, verb, change_set, occurred_at
FROM activity_entry
WHERE item_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (occurred_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListActivityParams struct {
	ItemID           pgtype.UUID
	CursorOccurredAt pgtype.Timestamptz
	CursorID         pgtype.UUID
	PageSize         int32
}

type ListActivityRow struct {
	ID          pgtype.UUID
	ItemID      pgtype.UUID
	ContainerID pgtype.UUID
	ActorType   string
	ActorID     pgtype.UUID
	Verb        string
	ChangeSet   []byte
	OccurredAt  pgtype.Timestamptz
}

// One page of an item's history, newest first.
//
// Keyset rather than an offset, like every other list in this schema (api-guidelines.md §4): an
// offset re-reads everything it skips and shifts under a concurrent write, and a history is written
// to precisely while somebody is reading it. The boundary is the pair (occurred_at, id), because
// two steps of one act share a timestamp - a cursor on the time alone would either skip the second
// or return the first again forever.
//
// Served by activity_page_idx, whose columns are this ORDER BY.
func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ListActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivity,
		arg.ItemID,
		arg.CursorOccurredAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRow{}
	for rows.Next() {
		var i ListActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ContainerID,
			&i.ActorType,
			&i.ActorID,
			&i.Verb,
			&i.ChangeSet,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivity = `-- name: RecordActivity :exec

INSERT INTO activity_entry (
  id, tenant_id, item_id, container_id, actor_type, actor_id, verb, change_set, occurred_at
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8
)
`

type RecordActivityParams struct {
	ID          pgtype.UUID
	ItemID      pgtype.UUID
	ContainerID pgtype.UUID
	ActorType   string
	ActorID     pgtype.UUID
	Verb        string
	ChangeSet   []byte
	OccurredAt  pgtype.Timestamptz
}

// The item history: what happened to a piece of work, in the words the people working on it read
// (B-11, domain-model.md §3.5).
//
// Append-only. There is deliberately no UPDATE and no DELETE in this file: an entry is not edited,
// and what removes one is the deletion of the item it belongs to, through the foreign key
// (0009_activity_history.sql). A statement that deleted one by hand would be a history somebody
// could tidy up, which is the opposite of what a history is for.
//
// The tenant is never a parameter. It comes from the transaction's own context through
// current_tenant_id(), which is the value row level security compares against (ADR-0010).
// One step of one item's history, written inside the transaction that made the change.
//
// `container_id` is the collection the item was in when this happened - the visibility anchor
// rather than a second subject. It is stored rather than joined at read time because the item may
// have moved since, and a history that re-derived it would show where the entry is now instead of
// where it was then.
//
// The correlation and causation columns stay NULL. They belong to an act caused by another act,
// and everything this milestone records is something a person asked for directly; filling them
// with a request identifier would be a chain that describes nothing (automation.md §2).
func (q *Queries) RecordActivity(ctx context.Context, arg RecordActivityParams) error {
	_, err := q.db.Exec(ctx, recordActivity,
		arg.ID,
		arg.ItemID,
		arg.ContainerID,
		arg.ActorType,
		arg.ActorID,
		arg.Verb,
		arg.ChangeSet,
		arg.OccurredAt,
	)
	return err
}
