// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: AiRequest.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAiRequest = `-- name: DeleteAiRequest :execrows
DELETE FROM ai_request WHERE id = $1
`

func (q *Queries) DeleteAiRequest(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAiRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAiRequests = `-- name: DeleteExpiredAiRequests :execrows
DELETE FROM ai_request
WHERE id IN (
  SELECT id FROM ai_request AS expired
  WHERE expired.created_at < $1
  ORDER BY expired.created_at
  LIMIT $2
)
`

type DeleteExpiredAiRequestsParams struct {
	Cutoff pgtype.Timestamptz
	Batch  int32
}

// The safety net under the job's own deletion: a request an abandoned job left behind goes with
// the suggestions' own sweep, oldest first and in batches.
func (q *Queries) DeleteExpiredAiRequests(ctx context.Context, arg DeleteExpiredAiRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAiRequests, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAiRequest = `-- name: FindAiRequest :one
SELECT id, asked_by, text, created_at FROM ai_request WHERE id = $1
`

type FindAiRequestRow struct {
	ID        pgtype.UUID
	AskedBy   pgtype.UUID
	Text      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) FindAiRequest(ctx context.Context, id pgtype.UUID) (FindAiRequestRow, error) {
	row := q.db.QueryRow(ctx, findAiRequest, id)
	var i FindAiRequestRow
	err := row.Scan(
		&i.ID,
		&i.AskedBy,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const putAiRequest = `-- name: PutAiRequest :exec

INSERT INTO ai_request (id, tenant_id, asked_by, text, created_at)
VALUES ($1, current_tenant_id(), $2, $3, $4)
`

type PutAiRequestParams struct {
	ID        pgtype.UUID
	AskedBy   pgtype.UUID
	Text      string
	CreatedAt pgtype.Timestamptz
}

// The words a person asked a template to be drafted from (P-11).
//
// Every statement runs inside the transaction wrapper that sets `app.tenant_id`; the policy
// underneath answers "which workspace", and `current_tenant_id()` is written on insert.
func (q *Queries) PutAiRequest(ctx context.Context, arg PutAiRequestParams) error {
	_, err := q.db.Exec(ctx, putAiRequest,
		arg.ID,
		arg.AskedBy,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}
