// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Backup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backupTargetCredentialsNotUnder = `-- name: BackupTargetCredentialsNotUnder :many
SELECT id, credential_enc, credential_key_id
FROM backup_target
WHERE credential_key_id IS NOT NULL AND credential_key_id <> $1
ORDER BY id
`

type BackupTargetCredentialsNotUnderRow struct {
	ID              pgtype.UUID
	CredentialEnc   []byte
	CredentialKeyID *string
}

// The rows a re-seal visits (ADR-0045). Like FindBackupTargetCredential it reads the credential
// and nothing that is on its way to a response.
func (q *Queries) BackupTargetCredentialsNotUnder(ctx context.Context, keyID *string) ([]BackupTargetCredentialsNotUnderRow, error) {
	rows, err := q.db.Query(ctx, backupTargetCredentialsNotUnder, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupTargetCredentialsNotUnderRow{}
	for rows.Next() {
		var i BackupTargetCredentialsNotUnderRow
		if err := rows.Scan(&i.ID, &i.CredentialEnc, &i.CredentialKeyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBackupTargets = `-- name: CountBackupTargets :one
SELECT
  count(*) AS configured,
  count(*) FILTER (WHERE encryption_mode = 'NONE') AS unencrypted
FROM backup_target
WHERE enabled
`

type CountBackupTargetsRow struct {
	Configured  int64
	Unencrypted int64
}

// Whether this tenant has any target at all, and whether any of them is unencrypted. Two counts
// rather than a list, because the health surface asks a question about the installation rather
// than about a target (backup-restore.md §10).
func (q *Queries) CountBackupTargets(ctx context.Context) (CountBackupTargetsRow, error) {
	row := q.db.QueryRow(ctx, countBackupTargets)
	var i CountBackupTargetsRow
	err := row.Scan(&i.Configured, &i.Unencrypted)
	return i, err
}

const dueBackupSchedules = `-- name: DueBackupSchedules :many
SELECT id, target_id, tenant_id, scope_kind, scope_id, rrule, time_zone, mode, full_rrule,
       include_media, include_audit, retention, notify_on, enabled, next_run_at, created_at, version
FROM backup_schedule
WHERE enabled AND next_run_at IS NOT NULL AND next_run_at <= $1::timestamptz
ORDER BY next_run_at
LIMIT $2::int
`

type DueBackupSchedulesParams struct {
	Now   pgtype.Timestamptz
	Batch int32
}

// What is due now, in the tenant the transaction is bound to.
//
// `next_run_at` is a stored decision rather than a rule expanded on the spot: expanding an RRULE
// costs a library call per schedule, and a poller that did it on every wake-up would do it for
// every schedule that is not due. The value is written by the pass that last ran, which is the same
// shape D-03's reminders use.
func (q *Queries) DueBackupSchedules(ctx context.Context, arg DueBackupSchedulesParams) ([]BackupSchedule, error) {
	rows, err := q.db.Query(ctx, dueBackupSchedules, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupSchedule{}
	for rows.Next() {
		var i BackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.TenantID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Rrule,
			&i.TimeZone,
			&i.Mode,
			&i.FullRrule,
			&i.IncludeMedia,
			&i.IncludeAudit,
			&i.Retention,
			&i.NotifyOn,
			&i.Enabled,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireBackupRun = `-- name: ExpireBackupRun :exec
UPDATE backup_run SET status = 'EXPIRED' WHERE id = $1 AND status = 'SUCCEEDED'
`

func (q *Queries) ExpireBackupRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireBackupRun, id)
	return err
}

const findBackupRun = `-- name: FindBackupRun :one
SELECT id, schedule_id, target_id, tenant_id, parent_run_id, trigger, mode, status, archive_path,
       size_bytes, item_count, media_count, checksum, snapshot_at, started_at, finished_at,
       error_code, expires_at, verified_at, verify_ok
FROM backup_run
WHERE id = $1
`

type FindBackupRunRow struct {
	ID          pgtype.UUID
	ScheduleID  pgtype.UUID
	TargetID    pgtype.UUID
	TenantID    pgtype.UUID
	ParentRunID pgtype.UUID
	Trigger     string
	Mode        string
	Status      string
	ArchivePath *string
	SizeBytes   *int64
	ItemCount   *int32
	MediaCount  *int32
	Checksum    *string
	SnapshotAt  pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ErrorCode   *string
	ExpiresAt   pgtype.Timestamptz
	VerifiedAt  pgtype.Timestamptz
	VerifyOk    *bool
}

func (q *Queries) FindBackupRun(ctx context.Context, id pgtype.UUID) (FindBackupRunRow, error) {
	row := q.db.QueryRow(ctx, findBackupRun, id)
	var i FindBackupRunRow
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TargetID,
		&i.TenantID,
		&i.ParentRunID,
		&i.Trigger,
		&i.Mode,
		&i.Status,
		&i.ArchivePath,
		&i.SizeBytes,
		&i.ItemCount,
		&i.MediaCount,
		&i.Checksum,
		&i.SnapshotAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.VerifyOk,
	)
	return i, err
}

const findBackupSchedule = `-- name: FindBackupSchedule :one
SELECT id, target_id, tenant_id, scope_kind, scope_id, rrule, time_zone, mode, full_rrule,
       include_media, include_audit, retention, notify_on, enabled, next_run_at, created_at, version
FROM backup_schedule
WHERE id = $1
`

func (q *Queries) FindBackupSchedule(ctx context.Context, id pgtype.UUID) (BackupSchedule, error) {
	row := q.db.QueryRow(ctx, findBackupSchedule, id)
	var i BackupSchedule
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.TenantID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Rrule,
		&i.TimeZone,
		&i.Mode,
		&i.FullRrule,
		&i.IncludeMedia,
		&i.IncludeAudit,
		&i.Retention,
		&i.NotifyOn,
		&i.Enabled,
		&i.NextRunAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const findBackupTarget = `-- name: FindBackupTarget :one
SELECT id, tenant_id, name, kind, config, credential_key_id, encryption_mode, encryption_key_id,
       region_note, insecure_ack_by, insecure_ack_at, enabled,
       last_test_at, last_test_ok, last_test_error, created_at, created_by, version
FROM backup_target
WHERE id = $1
`

type FindBackupTargetRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	Kind            string
	Config          []byte
	CredentialKeyID *string
	EncryptionMode  string
	EncryptionKeyID *string
	RegionNote      *string
	InsecureAckBy   pgtype.UUID
	InsecureAckAt   pgtype.Timestamptz
	Enabled         bool
	LastTestAt      pgtype.Timestamptz
	LastTestOk      *bool
	LastTestError   *string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Version         int32
}

func (q *Queries) FindBackupTarget(ctx context.Context, id pgtype.UUID) (FindBackupTargetRow, error) {
	row := q.db.QueryRow(ctx, findBackupTarget, id)
	var i FindBackupTargetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.CredentialKeyID,
		&i.EncryptionMode,
		&i.EncryptionKeyID,
		&i.RegionNote,
		&i.InsecureAckBy,
		&i.InsecureAckAt,
		&i.Enabled,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.LastTestError,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const findBackupTargetCredential = `-- name: FindBackupTargetCredential :one
SELECT credential_enc, credential_key_id
FROM backup_target
WHERE id = $1
`

type FindBackupTargetCredentialRow struct {
	CredentialEnc   []byte
	CredentialKeyID *string
}

// The one statement that reads the sealed credential, and it reads nothing else. A separate
// statement rather than a column on the two above: what a credential must never do is travel with
// something that is on its way to a response, and the way to make that structural is for the
// rows that go to a response never to contain one.
func (q *Queries) FindBackupTargetCredential(ctx context.Context, id pgtype.UUID) (FindBackupTargetCredentialRow, error) {
	row := q.db.QueryRow(ctx, findBackupTargetCredential, id)
	var i FindBackupTargetCredentialRow
	err := row.Scan(&i.CredentialEnc, &i.CredentialKeyID)
	return i, err
}

const finishBackupRun = `-- name: FinishBackupRun :execrows
UPDATE backup_run SET
  status       = $1,
  archive_path = $2,
  manifest     = $3,
  size_bytes   = $4,
  item_count   = $5,
  media_count  = $6,
  checksum     = $7,
  snapshot_at  = COALESCE($8, snapshot_at),
  finished_at  = $9,
  error_code   = $10
WHERE id = $11 AND status = 'RUNNING'
`

type FinishBackupRunParams struct {
	Status      string
	ArchivePath *string
	Manifest    []byte
	SizeBytes   *int64
	ItemCount   *int32
	MediaCount  *int32
	Checksum    *string
	SnapshotAt  pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ErrorCode   *string
	ID          pgtype.UUID
}

// What the run wrote, once it has written it. The manifest is kept as a copy so that a listing can
// answer without reaching the target, and the target stays the source of truth (§8.1).
func (q *Queries) FinishBackupRun(ctx context.Context, arg FinishBackupRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishBackupRun,
		arg.Status,
		arg.ArchivePath,
		arg.Manifest,
		arg.SizeBytes,
		arg.ItemCount,
		arg.MediaCount,
		arg.Checksum,
		arg.SnapshotAt,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBackupRun = `-- name: InsertBackupRun :execrows
INSERT INTO backup_run (
  id, schedule_id, target_id, tenant_id, parent_run_id, trigger, mode, status,
  snapshot_at, started_at
)
SELECT
  $1, $2, $3, $4,
  $5, $6, $7, 'RUNNING',
  $8, $9
WHERE NOT EXISTS (
  SELECT 1 FROM backup_run other
  WHERE other.target_id = $3
    AND other.status = 'RUNNING'
    AND other.id <> $1
)
ON CONFLICT (id) DO NOTHING
`

type InsertBackupRunParams struct {
	ID          pgtype.UUID
	ScheduleID  pgtype.UUID
	TargetID    pgtype.UUID
	TenantID    pgtype.UUID
	ParentRunID pgtype.UUID
	Trigger     string
	Mode        string
	SnapshotAt  pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
}

// The runs.
//
// The insert is the lock §5 asks for: one run at a time per target, enforced by the statement
// rather than by a check the caller ran a moment earlier - a check followed by an insert has a gap
// between them wide enough for exactly the thing it prevents.
//
// `other.id <> id` is what makes a resumption possible. A worker that died left its own row
// RUNNING; the attempt that takes the job over is the same run, and it has to be able to carry on
// rather than be locked out by itself (BK-7). ON CONFLICT DO NOTHING is the other half of that: the
// second attempt writes nothing and reads the row it already has.
func (q *Queries) InsertBackupRun(ctx context.Context, arg InsertBackupRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBackupRun,
		arg.ID,
		arg.ScheduleID,
		arg.TargetID,
		arg.TenantID,
		arg.ParentRunID,
		arg.Trigger,
		arg.Mode,
		arg.SnapshotAt,
		arg.StartedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBackupSchedule = `-- name: InsertBackupSchedule :exec

INSERT INTO backup_schedule (
  id, target_id, tenant_id, scope_kind, scope_id, rrule, time_zone, mode, full_rrule,
  include_media, include_audit, retention, notify_on, enabled, next_run_at, created_at, version
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11,
  $12, $13::text[], true, $14,
  $15, 1
)
`

type InsertBackupScheduleParams struct {
	ID           pgtype.UUID
	TargetID     pgtype.UUID
	TenantID     pgtype.UUID
	ScopeKind    string
	ScopeID      pgtype.UUID
	Rrule        string
	TimeZone     string
	Mode         string
	FullRrule    *string
	IncludeMedia bool
	IncludeAudit bool
	Retention    []byte
	NotifyOn     []string
	NextRunAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// ─────────────────────────── The schedules and the runs (E-05) ───────────────────────────
//
// backup_schedule and backup_run are both behind row level security, so no statement here carries
// a tenant condition - with one exception that is named where it appears: the instance-wide
// schedules belong to no tenant, and the leader reads them under a scope that has none.
func (q *Queries) InsertBackupSchedule(ctx context.Context, arg InsertBackupScheduleParams) error {
	_, err := q.db.Exec(ctx, insertBackupSchedule,
		arg.ID,
		arg.TargetID,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Rrule,
		arg.TimeZone,
		arg.Mode,
		arg.FullRrule,
		arg.IncludeMedia,
		arg.IncludeAudit,
		arg.Retention,
		arg.NotifyOn,
		arg.NextRunAt,
		arg.CreatedAt,
	)
	return err
}

const insertBackupTarget = `-- name: InsertBackupTarget :exec

INSERT INTO backup_target (
  id, tenant_id, name, kind, config, credential_enc, credential_key_id,
  encryption_mode, encryption_key_id, region_note, insecure_ack_by, insecure_ack_at,
  enabled, created_at, created_by, version
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12,
  true, $13, $14, 1
)
`

type InsertBackupTargetParams struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	Kind            string
	Config          []byte
	CredentialEnc   []byte
	CredentialKeyID *string
	EncryptionMode  string
	EncryptionKeyID *string
	RegionNote      *string
	InsecureAckBy   pgtype.UUID
	InsecureAckAt   pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
}

// The backup targets (E-03, backup-restore.md §2).
//
// backup_target is behind row level security like every other tenant table, so no statement here
// carries a tenant condition: the policy applies one no query can forget (ADR-0010). What it means
// for a target with tenant_id IS NULL - the instance-wide shape 0001_init has always allowed - is
// that nothing in this milestone can see one, because the policy compares against a tenant and an
// instance-wide row has none. That is deliberate rather than an oversight: instance administration
// has no surface on this API yet, and the targets a tenant creates are the tenant's.
//
// The credential is read by exactly one statement, and it is named for it. Every other statement
// selects the columns a caller may see, so a credential cannot reach a response because somebody
// added a field to a mapper.
func (q *Queries) InsertBackupTarget(ctx context.Context, arg InsertBackupTargetParams) error {
	_, err := q.db.Exec(ctx, insertBackupTarget,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.CredentialEnc,
		arg.CredentialKeyID,
		arg.EncryptionMode,
		arg.EncryptionKeyID,
		arg.RegionNote,
		arg.InsecureAckBy,
		arg.InsecureAckAt,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const lastSuccessfulBackupPerTarget = `-- name: LastSuccessfulBackupPerTarget :many
SELECT target_id, max(COALESCE(finished_at, started_at))::timestamptz AS last_success_at
FROM backup_run
WHERE status = 'SUCCEEDED'
GROUP BY target_id
`

type LastSuccessfulBackupPerTargetRow struct {
	TargetID      pgtype.UUID
	LastSuccessAt pgtype.Timestamptz
}

// The number alert A-12 watches: when each target last had a backup that worked
// (observability-reliability.md §10). One row per target, and a target that has never had one is
// absent rather than zero - a gauge of zero reads as "1970" on every dashboard.
func (q *Queries) LastSuccessfulBackupPerTarget(ctx context.Context) ([]LastSuccessfulBackupPerTargetRow, error) {
	rows, err := q.db.Query(ctx, lastSuccessfulBackupPerTarget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastSuccessfulBackupPerTargetRow{}
	for rows.Next() {
		var i LastSuccessfulBackupPerTargetRow
		if err := rows.Scan(&i.TargetID, &i.LastSuccessAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestSuccessfulBackupRun = `-- name: LatestSuccessfulBackupRun :one
SELECT id, schedule_id, target_id, tenant_id, parent_run_id, trigger, mode, status, archive_path,
       size_bytes, item_count, media_count, checksum, snapshot_at, started_at, finished_at,
       error_code, expires_at, verified_at, verify_ok
FROM backup_run
WHERE target_id = $1 AND status = 'SUCCEEDED' AND archive_path IS NOT NULL
ORDER BY snapshot_at DESC NULLS LAST, started_at DESC
LIMIT 1
`

type LatestSuccessfulBackupRunRow struct {
	ID          pgtype.UUID
	ScheduleID  pgtype.UUID
	TargetID    pgtype.UUID
	TenantID    pgtype.UUID
	ParentRunID pgtype.UUID
	Trigger     string
	Mode        string
	Status      string
	ArchivePath *string
	SizeBytes   *int64
	ItemCount   *int32
	MediaCount  *int32
	Checksum    *string
	SnapshotAt  pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ErrorCode   *string
	ExpiresAt   pgtype.Timestamptz
	VerifiedAt  pgtype.Timestamptz
	VerifyOk    *bool
}

// The archive an incremental continues: the newest run at this target that finished and left
// something behind. A run that failed is not a parent - there is no archive at the other end of it.
func (q *Queries) LatestSuccessfulBackupRun(ctx context.Context, targetID pgtype.UUID) (LatestSuccessfulBackupRunRow, error) {
	row := q.db.QueryRow(ctx, latestSuccessfulBackupRun, targetID)
	var i LatestSuccessfulBackupRunRow
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TargetID,
		&i.TenantID,
		&i.ParentRunID,
		&i.Trigger,
		&i.Mode,
		&i.Status,
		&i.ArchivePath,
		&i.SizeBytes,
		&i.ItemCount,
		&i.MediaCount,
		&i.Checksum,
		&i.SnapshotAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.VerifyOk,
	)
	return i, err
}

const listBackupSchedules = `-- name: ListBackupSchedules :many
SELECT id, target_id, tenant_id, scope_kind, scope_id, rrule, time_zone, mode, full_rrule,
       include_media, include_audit, retention, notify_on, enabled, next_run_at, created_at, version
FROM backup_schedule
ORDER BY created_at
`

func (q *Queries) ListBackupSchedules(ctx context.Context) ([]BackupSchedule, error) {
	rows, err := q.db.Query(ctx, listBackupSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupSchedule{}
	for rows.Next() {
		var i BackupSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.TenantID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Rrule,
			&i.TimeZone,
			&i.Mode,
			&i.FullRrule,
			&i.IncludeMedia,
			&i.IncludeAudit,
			&i.Retention,
			&i.NotifyOn,
			&i.Enabled,
			&i.NextRunAt,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackupTargets = `-- name: ListBackupTargets :many
SELECT id, tenant_id, name, kind, config, credential_key_id, encryption_mode, encryption_key_id,
       region_note, insecure_ack_by, insecure_ack_at, enabled,
       last_test_at, last_test_ok, last_test_error, created_at, created_by, version
FROM backup_target
ORDER BY lower(name)
`

type ListBackupTargetsRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	Kind            string
	Config          []byte
	CredentialKeyID *string
	EncryptionMode  string
	EncryptionKeyID *string
	RegionNote      *string
	InsecureAckBy   pgtype.UUID
	InsecureAckAt   pgtype.Timestamptz
	Enabled         bool
	LastTestAt      pgtype.Timestamptz
	LastTestOk      *bool
	LastTestError   *string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Version         int32
}

// The list a client reads back. Ordered by name rather than by creation, because an operator
// looking for "the Hetzner one" is looking alphabetically.
func (q *Queries) ListBackupTargets(ctx context.Context) ([]ListBackupTargetsRow, error) {
	rows, err := q.db.Query(ctx, listBackupTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackupTargetsRow{}
	for rows.Next() {
		var i ListBackupTargetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.CredentialKeyID,
			&i.EncryptionMode,
			&i.EncryptionKeyID,
			&i.RegionNote,
			&i.InsecureAckBy,
			&i.InsecureAckAt,
			&i.Enabled,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.LastTestError,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBackupScheduleDue = `-- name: NextBackupScheduleDue :one
SELECT min(next_run_at)::timestamptz AS due
FROM backup_schedule
WHERE enabled AND next_run_at IS NOT NULL
`

// The earliest moment this tenant owes a backup, which is what a poller reschedules itself to.
func (q *Queries) NextBackupScheduleDue(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextBackupScheduleDue)
	var due pgtype.Timestamptz
	err := row.Scan(&due)
	return due, err
}

const recordBackupTargetTest = `-- name: RecordBackupTargetTest :execrows
UPDATE backup_target SET
  last_test_at    = $1,
  last_test_ok    = $2,
  last_test_error = $3
WHERE id = $4
`

type RecordBackupTargetTestParams struct {
	TestedAt  pgtype.Timestamptz
	Succeeded *bool
	ErrorCode *string
	ID        pgtype.UUID
}

// What the connection probe leaves behind. The error is a message code, never a driver message:
// an FTP or SSH library's message carries the host, the user and sometimes the password (rule 10).
func (q *Queries) RecordBackupTargetTest(ctx context.Context, arg RecordBackupTargetTestParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordBackupTargetTest,
		arg.TestedAt,
		arg.Succeeded,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordBackupVerification = `-- name: RecordBackupVerification :execrows
UPDATE backup_run
SET verified_at = $1, verify_ok = $2
WHERE id = $3
`

type RecordBackupVerificationParams struct {
	VerifiedAt pgtype.Timestamptz
	VerifyOk   *bool
	ID         pgtype.UUID
}

// What `:verify` found, without touching anything else on the row.
func (q *Queries) RecordBackupVerification(ctx context.Context, arg RecordBackupVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordBackupVerification, arg.VerifiedAt, arg.VerifyOk, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rewrapBackupTargetCredential = `-- name: RewrapBackupTargetCredential :execrows
UPDATE backup_target
SET credential_enc = $1, credential_key_id = $2
WHERE id = $3 AND credential_key_id = $4
`

type RewrapBackupTargetCredentialParams struct {
	CredentialEnc   []byte
	CredentialKeyID *string
	ID              pgtype.UUID
	ExpectedKeyID   *string
}

func (q *Queries) RewrapBackupTargetCredential(ctx context.Context, arg RewrapBackupTargetCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapBackupTargetCredential,
		arg.CredentialEnc,
		arg.CredentialKeyID,
		arg.ID,
		arg.ExpectedKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBackupRunExpiry = `-- name: SetBackupRunExpiry :exec
UPDATE backup_run SET expires_at = $1 WHERE id = $2
`

type SetBackupRunExpiryParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// When the generation plan expects an archive to go. Written after a successful run has decided,
// and cleared for an archive the plan now intends to keep - a stale date on a kept archive is what
// an operator would read as "this is about to disappear".
func (q *Queries) SetBackupRunExpiry(ctx context.Context, arg SetBackupRunExpiryParams) error {
	_, err := q.db.Exec(ctx, setBackupRunExpiry, arg.ExpiresAt, arg.ID)
	return err
}

const setBackupScheduleNextRun = `-- name: SetBackupScheduleNextRun :exec
UPDATE backup_schedule
SET next_run_at = $1, version = version + 1
WHERE id = $2
`

type SetBackupScheduleNextRunParams struct {
	NextRunAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) SetBackupScheduleNextRun(ctx context.Context, arg SetBackupScheduleNextRunParams) error {
	_, err := q.db.Exec(ctx, setBackupScheduleNextRun, arg.NextRunAt, arg.ID)
	return err
}
