// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: BackupRestore.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRestoreRun = `-- name: ClaimRestoreRun :execrows
UPDATE restore_run run SET
  status     = 'RUNNING',
  started_at = COALESCE(run.started_at, $1::timestamptz)
WHERE run.id = $2
  AND run.status IN ('PENDING', 'VALIDATING', 'RUNNING')
  AND NOT EXISTS (
    SELECT 1 FROM restore_run other
    WHERE other.status IN ('VALIDATING', 'RUNNING')
      AND other.id <> run.id
  )
`

type ClaimRestoreRunParams struct {
	StartedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// The claim, and the lock against two restores in one tenant at once.
//
// An UPDATE rather than an insert, because the row is written when the restore is accepted and
// claimed when the job picks it up - and a job that died and is picked up again has to be able to
// claim the same row a second time. That is BK-7's restore half: `status IN (...)` includes RUNNING
// so a resumed attempt continues its own run rather than being told the tenant is busy, and
// `started_at` is kept rather than moved, so the run still says when it actually began.
func (q *Queries) ClaimRestoreRun(ctx context.Context, arg ClaimRestoreRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimRestoreRun, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRestoreRun = `-- name: FindRestoreRun :one
SELECT id, target_id, source_archive, tenant_id, target_tenant_id, mode, conflict_rule, selection,
       dry_run, create_safety_backup, safety_backup_run_id, status, report, progress, requested_by,
       approved_by, started_at, finished_at, error_code
FROM restore_run
WHERE id = $1
`

type FindRestoreRunRow struct {
	ID                 pgtype.UUID
	TargetID           pgtype.UUID
	SourceArchive      string
	TenantID           pgtype.UUID
	TargetTenantID     pgtype.UUID
	Mode               string
	ConflictRule       string
	Selection          []byte
	DryRun             bool
	CreateSafetyBackup bool
	SafetyBackupRunID  pgtype.UUID
	Status             string
	Report             []byte
	Progress           []byte
	RequestedBy        pgtype.UUID
	ApprovedBy         pgtype.UUID
	StartedAt          pgtype.Timestamptz
	FinishedAt         pgtype.Timestamptz
	ErrorCode          *string
}

func (q *Queries) FindRestoreRun(ctx context.Context, id pgtype.UUID) (FindRestoreRunRow, error) {
	row := q.db.QueryRow(ctx, findRestoreRun, id)
	var i FindRestoreRunRow
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.SourceArchive,
		&i.TenantID,
		&i.TargetTenantID,
		&i.Mode,
		&i.ConflictRule,
		&i.Selection,
		&i.DryRun,
		&i.CreateSafetyBackup,
		&i.SafetyBackupRunID,
		&i.Status,
		&i.Report,
		&i.Progress,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
	)
	return i, err
}

const findWorkspaceName = `-- name: FindWorkspaceName :one
SELECT display_name FROM tenant WHERE id = current_tenant_id()
`

// What §8.3 step 3 asks to have typed. Bounded by row level security to the tenant of the running
// transaction, so this cannot be used to learn another workspace's name.
func (q *Queries) FindWorkspaceName(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, findWorkspaceName)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const finishRestoreRun = `-- name: FinishRestoreRun :execrows
UPDATE restore_run SET
  status               = $1,
  -- COALESCE, so that a failure with nothing to report does not erase what the attempt before it
  -- got through. A restore that died in its pre-check knows nothing; the progress the earlier
  -- attempt recorded is the only account of what has been done (BK-7).
  report               = COALESCE($2, report),
  safety_backup_run_id = COALESCE($3, safety_backup_run_id),
  finished_at          = $4,
  error_code           = $5
WHERE id = $6
  AND status IN ('PENDING', 'VALIDATING', 'RUNNING')
`

type FinishRestoreRunParams struct {
	Status            string
	Report            []byte
	SafetyBackupRunID pgtype.UUID
	FinishedAt        pgtype.Timestamptz
	ErrorCode         *string
	ID                pgtype.UUID
}

// Refused for a run that is no longer going, which is what makes a cancelled restore stay
// cancelled.
func (q *Queries) FinishRestoreRun(ctx context.Context, arg FinishRestoreRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRestoreRun,
		arg.Status,
		arg.Report,
		arg.SafetyBackupRunID,
		arg.FinishedAt,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRestoreRun = `-- name: InsertRestoreRun :exec
INSERT INTO restore_run (
  id, target_id, source_archive, tenant_id, target_tenant_id, mode, conflict_rule,
  selection, dry_run, create_safety_backup, status, requested_by
) VALUES (
  $1, $2, $3, current_tenant_id(),
  $4, $5, $6,
  $7, $8, $9,
  'PENDING', $10
)
`

type InsertRestoreRunParams struct {
	ID                 pgtype.UUID
	TargetID           pgtype.UUID
	SourceArchive      string
	TargetTenantID     pgtype.UUID
	Mode               string
	ConflictRule       string
	Selection          []byte
	DryRun             bool
	CreateSafetyBackup bool
	RequestedBy        pgtype.UUID
}

// The run row, written in the transaction that accepts the restore (§8.3 step 1). PENDING: the
// job has not started, and a caller polling `result_url` sees that rather than a 404.
func (q *Queries) InsertRestoreRun(ctx context.Context, arg InsertRestoreRunParams) error {
	_, err := q.db.Exec(ctx, insertRestoreRun,
		arg.ID,
		arg.TargetID,
		arg.SourceArchive,
		arg.TargetTenantID,
		arg.Mode,
		arg.ConflictRule,
		arg.Selection,
		arg.DryRun,
		arg.CreateSafetyBackup,
		arg.RequestedBy,
	)
	return err
}

const journalledDeletions = `-- name: JournalledDeletions :many

SELECT entity, entity_id, deleted_at, reason
FROM deletion_journal
WHERE deleted_at > $1::timestamptz
  AND (deleted_at, entity, entity_id)
      > ($2::timestamptz, $3::text, $4::uuid)
ORDER BY deleted_at, entity, entity_id
LIMIT $5::int
`

type JournalledDeletionsParams struct {
	Since       pgtype.Timestamptz
	AfterAt     pgtype.Timestamptz
	AfterEntity string
	AfterID     pgtype.UUID
	Batch       int32
}

type JournalledDeletionsRow struct {
	Entity    string
	EntityID  pgtype.UUID
	DeletedAt pgtype.Timestamptz
	Reason    string
}

// The statements a restore reads and records itself through (E-06, backup-restore.md §7, §8).
//
// Row level security supplies the tenant condition none of these statements writes (ADR-0010),
// which is BK-10 at the layer where it cannot be forgotten: a restore into another tenant's
// archive is refused by the use case, and a statement that reached across anyway would find
// nothing.
// The deletion journal, read for the first time in production (§7).
//
// Paged on (deleted_at, entity, entity_id) rather than on OFFSET, for the reason the export is:
// a page over a set another statement may reorder can repeat a row or drop one, and dropping one
// here means an object comes back that somebody asked to have deleted.
func (q *Queries) JournalledDeletions(ctx context.Context, arg JournalledDeletionsParams) ([]JournalledDeletionsRow, error) {
	rows, err := q.db.Query(ctx, journalledDeletions,
		arg.Since,
		arg.AfterAt,
		arg.AfterEntity,
		arg.AfterID,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalledDeletionsRow{}
	for rows.Next() {
		var i JournalledDeletionsRow
		if err := rows.Scan(
			&i.Entity,
			&i.EntityID,
			&i.DeletedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRestoreProgress = `-- name: RecordRestoreProgress :execrows
UPDATE restore_run SET
  report   = $1,
  progress = $2
WHERE id = $3
  AND status IN ('PENDING', 'VALIDATING', 'RUNNING')
`

type RecordRestoreProgressParams struct {
	Report   []byte
	Progress []byte
	ID       pgtype.UUID
}

// How far the run has got, written in the transaction of the batch it got there with (BK-7).
//
// The report travels with it because a resumed attempt continues counting rather than starting
// again: a report that only covered the last attempt would say a restore did a fraction of what it
// did.
func (q *Queries) RecordRestoreProgress(ctx context.Context, arg RecordRestoreProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRestoreProgress, arg.Report, arg.Progress, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordRestoreSafetyCopy = `-- name: RecordRestoreSafetyCopy :execrows
UPDATE restore_run SET safety_backup_run_id = $1
WHERE id = $2
`

type RecordRestoreSafetyCopyParams struct {
	SafetyBackupRunID pgtype.UUID
	ID                pgtype.UUID
}

// The copy §8.3 step 4 takes before a destructive mode, recorded before the mode runs: the way back
// has to be findable from the run even if the run itself then fails.
func (q *Queries) RecordRestoreSafetyCopy(ctx context.Context, arg RecordRestoreSafetyCopyParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRestoreSafetyCopy, arg.SafetyBackupRunID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreInProgress = `-- name: RestoreInProgress :one
SELECT EXISTS (
  SELECT 1 FROM restore_run WHERE status IN ('PENDING', 'VALIDATING', 'RUNNING')
) AS running
`

// Whether this tenant already has a restore going. Asked when one is requested, so that the refusal
// is a 409 the caller can read rather than a claim that fails minutes later inside a job.
func (q *Queries) RestoreInProgress(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, restoreInProgress)
	var running bool
	err := row.Scan(&running)
	return running, err
}
