// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Comment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findComment = `-- name: FindComment :one
SELECT id, tenant_id, item_id, author_id, parent_comment_id, body,
       created_at, edited_at, deleted_at, version
FROM comment
WHERE id = $1
`

// Tombstones are returned rather than filtered out: whether a deleted comment may be edited is
// the domain's question, and a query that hid one would turn "it was deleted" into "it never
// existed" - which is not what a thread full of replies to it says.
func (q *Queries) FindComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, findComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec

INSERT INTO comment (
  id, tenant_id, item_id, author_id, parent_comment_id, body, created_at, version
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, normalize($5::text, NFC),
  $6, 1
)
`

type InsertCommentParams struct {
	ID              pgtype.UUID
	ItemID          pgtype.UUID
	AuthorID        pgtype.UUID
	ParentCommentID pgtype.UUID
	Body            string
	CreatedAt       pgtype.Timestamptz
}

// The discussion beside the entries (C-03, domain-model.md §3.5).
//
// The tenant is never a parameter here: it comes from the transaction's own context through
// current_tenant_id(), which is the same value row level security compares against (ADR-0010).
//
// The body is stored Unicode NFC normalised, in the database rather than in the application, for
// the reason container names are: two spellings of the same word are one text to a person, and
// the domain may not import a Unicode library (ADR-0001, I-W7).
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.ItemID,
		arg.AuthorID,
		arg.ParentCommentID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const listComments = `-- name: ListComments :many
SELECT id, tenant_id, item_id, author_id, parent_comment_id, body,
       created_at, edited_at, deleted_at, version
FROM comment
WHERE item_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) > ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at, id
LIMIT $4
`

type ListCommentsParams struct {
	ItemID          pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

// One page of one entry's discussion, oldest first: a conversation reads top down, and a page
// boundary in the middle of it must not reorder what was already read. Tombstones are in it -
// that is the point of a soft deletion (§3.5) - and the caller serves them without their body.
//
// Keyset rather than an offset, like every list in this schema (api-guidelines.md §4). The
// boundary is the pair (created_at, id): two comments written in the same millisecond are one
// timestamp, and a cursor on the time alone would skip the second or return the first forever.
// Served by comment_item_idx, whose leading columns are this ORDER BY.
func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listComments,
		arg.ItemID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.AuthorID,
			&i.ParentCommentID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentBody = `-- name: SetCommentBody :execrows
UPDATE comment SET
  body      = normalize($1::text, NFC),
  edited_at = $2,
  version   = version + 1
WHERE id = $3::uuid
  AND version = $4
  AND deleted_at IS NULL
`

type SetCommentBodyParams struct {
	Body            string
	EditedAt        pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The rewrite, under the same optimistic lock every other row takes (api-guidelines.md §5). The
// deletion stamp is in the guard rather than trusted to the caller's read: a tombstone's text is
// gone, and an edit racing a deletion must lose to it rather than resurrect the words.
func (q *Queries) SetCommentBody(ctx context.Context, arg SetCommentBodyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCommentBody,
		arg.Body,
		arg.EditedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCommentDeleted = `-- name: SetCommentDeleted :execrows
UPDATE comment SET
  body       = '',
  deleted_at = $1,
  version    = version + 1
WHERE id = $2::uuid
  AND version = $3
  AND deleted_at IS NULL
`

type SetCommentDeletedParams struct {
	DeletedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The tombstone: text gone, identity and timestamps kept (C-03's acceptance). edited_at survives
// deliberately - that the words had been rewritten is part of the thread's history, what they
// were is not.
func (q *Queries) SetCommentDeleted(ctx context.Context, arg SetCommentDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCommentDeleted, arg.DeletedAt, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
