// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: IdentityProvider.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountHasIdentity = `-- name: AccountHasIdentity :one
SELECT EXISTS (
  SELECT 1 FROM account_identity WHERE account_id = $1
) AS held
`

// Whether the account already signs in through some provider (ADR-0071's addendum): such an
// identity is a credential of its own, and an account holding one is not connected to another
// provider on that provider's word.
func (q *Queries) AccountHasIdentity(ctx context.Context, accountID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, accountHasIdentity, accountID)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const consumeOidcFlow = `-- name: ConsumeOidcFlow :one
UPDATE oidc_flow SET consumed_at = $1
WHERE state_hash = $2
  AND session_id IS NULL
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, provider_id, code_verifier, nonce
`

type ConsumeOidcFlowParams struct {
	Now       pgtype.Timestamptz
	StateHash []byte
}

type ConsumeOidcFlowRow struct {
	ID           pgtype.UUID
	ProviderID   pgtype.UUID
	CodeVerifier string
	Nonce        string
}

// Judged and burned in one statement, ConsumeOauthCode's discipline: unexpired and unconsumed,
// or nothing at all - so a state presented twice matches no row whoever races whom. A sign-in's:
// a flow bound to a session is a step-up and finishes no sign-in.
func (q *Queries) ConsumeOidcFlow(ctx context.Context, arg ConsumeOidcFlowParams) (ConsumeOidcFlowRow, error) {
	row := q.db.QueryRow(ctx, consumeOidcFlow, arg.Now, arg.StateHash)
	var i ConsumeOidcFlowRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CodeVerifier,
		&i.Nonce,
	)
	return i, err
}

const consumeStepUpOidcFlow = `-- name: ConsumeStepUpOidcFlow :one
UPDATE oidc_flow SET consumed_at = $1
WHERE state_hash = $2
  AND session_id = $3
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, provider_id, code_verifier, nonce, session_id
`

type ConsumeStepUpOidcFlowParams struct {
	Now       pgtype.Timestamptz
	StateHash []byte
	SessionID pgtype.UUID
}

type ConsumeStepUpOidcFlowRow struct {
	ID           pgtype.UUID
	ProviderID   pgtype.UUID
	CodeVerifier string
	Nonce        string
	SessionID    pgtype.UUID
}

// The step-up's: only a flow bound to this very session, judged and burned in the same statement.
func (q *Queries) ConsumeStepUpOidcFlow(ctx context.Context, arg ConsumeStepUpOidcFlowParams) (ConsumeStepUpOidcFlowRow, error) {
	row := q.db.QueryRow(ctx, consumeStepUpOidcFlow, arg.Now, arg.StateHash, arg.SessionID)
	var i ConsumeStepUpOidcFlowRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CodeVerifier,
		&i.Nonce,
		&i.SessionID,
	)
	return i, err
}

const countIdentityProviders = `-- name: CountIdentityProviders :one
SELECT count(*) FROM identity_provider WHERE tenant_id = current_tenant_id()
`

// What the bound is checked against before an insert. The workspace's own only: the installation's
// rows are not its to be limited by.
func (q *Queries) CountIdentityProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentityProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredOidcFlows = `-- name: DeleteExpiredOidcFlows :execrows
DELETE FROM oidc_flow
WHERE id IN (
  SELECT id FROM oidc_flow AS expired
  WHERE expired.expires_at < $1
  LIMIT $2
)
`

type DeleteExpiredOidcFlowsParams struct {
	Cutoff pgtype.Timestamptz
	Batch  int32
}

// Hygiene in the session sweep's pass, the expired authorization codes' reasoning: a flow lives
// minutes, and what is left of it after that is a row nobody will ever present again.
func (q *Queries) DeleteExpiredOidcFlows(ctx context.Context, arg DeleteExpiredOidcFlowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOidcFlows, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdentityProvider = `-- name: DeleteIdentityProvider :execrows
DELETE FROM identity_provider WHERE id = $1
`

func (q *Queries) DeleteIdentityProvider(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIdentityProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAccountByProviderSubject = `-- name: FindAccountByProviderSubject :one
SELECT a.id, a.tenant_id, a.kind, a.email, a.display_name, a.status, a.locale, a.time_zone,
  a.week_start, a.celebrations, a.onboarding_completed_at
FROM account_identity link
JOIN account a ON a.tenant_id = link.tenant_id AND a.id = link.account_id
WHERE link.provider_id = $1
  AND link.subject = $2
  AND a.deleted_at IS NULL
`

type FindAccountByProviderSubjectParams struct {
	ProviderID pgtype.UUID
	Subject    string
}

type FindAccountByProviderSubjectRow struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	Kind                  AccountKind
	Email                 *string
	DisplayName           string
	Status                AccountStatus
	Locale                *string
	TimeZone              *string
	WeekStart             *string
	Celebrations          *bool
	OnboardingCompletedAt pgtype.Timestamptz
}

// The subject the provider vouched for, under the unique index that makes it one account per
// provider per workspace (migration 0103). Deleted accounts are excluded: an arriving subject whose
// account was deleted is a first arrival, not a resurrection.
func (q *Queries) FindAccountByProviderSubject(ctx context.Context, arg FindAccountByProviderSubjectParams) (FindAccountByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, findAccountByProviderSubject, arg.ProviderID, arg.Subject)
	var i FindAccountByProviderSubjectRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Locale,
		&i.TimeZone,
		&i.WeekStart,
		&i.Celebrations,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const findIdentityProviderByID = `-- name: FindIdentityProviderByID :one
SELECT id, tenant_id, issuer, client_id, display_name, kind, provisioning, position,
  allowed_email_domains, allowed_directories, enabled, created_at, updated_at, version
FROM identity_provider
WHERE id = $1
`

type FindIdentityProviderByIDRow struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	Issuer              string
	ClientID            string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int32
}

// What a reader is allowed to see: never the sealed secret. The one caller that needs it asks for
// it by name below, so a read cannot spill it by accident.
func (q *Queries) FindIdentityProviderByID(ctx context.Context, id pgtype.UUID) (FindIdentityProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, findIdentityProviderByID, id)
	var i FindIdentityProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Issuer,
		&i.ClientID,
		&i.DisplayName,
		&i.Kind,
		&i.Provisioning,
		&i.Position,
		&i.AllowedEmailDomains,
		&i.AllowedDirectories,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findIdentityProviderSecret = `-- name: FindIdentityProviderSecret :one
SELECT id, tenant_id, issuer, client_id, display_name, kind, provisioning, position,
  client_secret_enc, client_secret_key_id, allowed_email_domains, allowed_directories, enabled
FROM identity_provider
WHERE id = $1
`

type FindIdentityProviderSecretRow struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	Issuer              string
	ClientID            string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	ClientSecretEnc     []byte
	ClientSecretKeyID   string
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
}

// The token exchange's own read, separate from the one above so that opening the envelope is a
// deliberate call and not a field that happens to be in a struct somebody logged.
func (q *Queries) FindIdentityProviderSecret(ctx context.Context, id pgtype.UUID) (FindIdentityProviderSecretRow, error) {
	row := q.db.QueryRow(ctx, findIdentityProviderSecret, id)
	var i FindIdentityProviderSecretRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Issuer,
		&i.ClientID,
		&i.DisplayName,
		&i.Kind,
		&i.Provisioning,
		&i.Position,
		&i.ClientSecretEnc,
		&i.ClientSecretKeyID,
		&i.AllowedEmailDomains,
		&i.AllowedDirectories,
		&i.Enabled,
	)
	return i, err
}

const insertIdentityProvider = `-- name: InsertIdentityProvider :one
INSERT INTO identity_provider
  (id, tenant_id, issuer, client_id, client_secret_enc, client_secret_key_id,
   display_name, kind, provisioning, position, allowed_email_domains, allowed_directories,
   enabled, created_at)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5,
  $6, $7, $8, $9,
  $10, $11,
  $12, $13
)
RETURNING id, tenant_id, issuer, client_id, display_name, kind, provisioning, position,
  allowed_email_domains, allowed_directories, enabled, created_at, updated_at, version
`

type InsertIdentityProviderParams struct {
	ID                  pgtype.UUID
	Issuer              string
	ClientID            string
	ClientSecretEnc     []byte
	ClientSecretKeyID   string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	Now                 pgtype.Timestamptz
}

type InsertIdentityProviderRow struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	Issuer              string
	ClientID            string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int32
}

// `current_tenant_id()` rather than an argument, and it is what makes one statement serve both
// levels: a workspace's transaction writes its own row, and the installation's scope - where the
// setting is the empty string and the function therefore NULL - writes the row that belongs to
// nobody. A caller cannot choose which, because there is nothing to pass.
func (q *Queries) InsertIdentityProvider(ctx context.Context, arg InsertIdentityProviderParams) (InsertIdentityProviderRow, error) {
	row := q.db.QueryRow(ctx, insertIdentityProvider,
		arg.ID,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.ClientSecretKeyID,
		arg.DisplayName,
		arg.Kind,
		arg.Provisioning,
		arg.Position,
		arg.AllowedEmailDomains,
		arg.AllowedDirectories,
		arg.Enabled,
		arg.Now,
	)
	var i InsertIdentityProviderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Issuer,
		&i.ClientID,
		&i.DisplayName,
		&i.Kind,
		&i.Provisioning,
		&i.Position,
		&i.AllowedEmailDomains,
		&i.AllowedDirectories,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertOidcFlow = `-- name: InsertOidcFlow :exec
INSERT INTO oidc_flow
  (id, tenant_id, provider_id, state_hash, code_verifier, nonce, created_at, expires_at, session_id)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6, $7,
  $8
)
`

type InsertOidcFlowParams struct {
	ID           pgtype.UUID
	ProviderID   pgtype.UUID
	StateHash    []byte
	CodeVerifier string
	Nonce        string
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	SessionID    pgtype.UUID
}

// A NULL session is a sign-in flow; a session is the step-up at the provider it belongs to
// (ADR-0075 §2).
func (q *Queries) InsertOidcFlow(ctx context.Context, arg InsertOidcFlowParams) error {
	_, err := q.db.Exec(ctx, insertOidcFlow,
		arg.ID,
		arg.ProviderID,
		arg.StateHash,
		arg.CodeVerifier,
		arg.Nonce,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.SessionID,
	)
	return err
}

const linkAccountIdentity = `-- name: LinkAccountIdentity :execrows
INSERT INTO account_identity (tenant_id, account_id, provider_id, subject, linked_at)
SELECT a.tenant_id, a.id, $1, $2, $3
FROM account a
WHERE a.id = $4 AND a.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type LinkAccountIdentityParams struct {
	ProviderID pgtype.UUID
	Subject    string
	Now        pgtype.Timestamptz
	AccountID  pgtype.UUID
}

// Writes the link, and races safely: the unique index on (tenant, provider, subject) is what
// refuses a subject already spoken for, and `DO NOTHING` is what makes a second sign-in that got
// there first leave nothing for this one to overwrite. An account already bound to another subject
// at this provider is never quietly re-pointed, because the primary key refuses that too.
func (q *Queries) LinkAccountIdentity(ctx context.Context, arg LinkAccountIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkAccountIdentity,
		arg.ProviderID,
		arg.Subject,
		arg.Now,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIdentityProviderSecrets = `-- name: ListIdentityProviderSecrets :many
SELECT id, client_secret_enc, client_secret_key_id
FROM identity_provider
WHERE tenant_id IS NOT DISTINCT FROM current_tenant_id()
`

type ListIdentityProviderSecretsRow struct {
	ID                pgtype.UUID
	ClientSecretEnc   []byte
	ClientSecretKeyID string
}

// The re-seal's read (ADR-0045): every row of *this level* that holds a wrapping, so a rotation can
// move each one under the key it named when it was read.
//
// `IS NOT DISTINCT FROM` rather than `=`, and that is the whole difference: in a workspace's scope
// it is the workspace's own rows, and in the installation's - where `current_tenant_id()` is NULL -
// it is the rows that belong to no workspace. Which is what makes the installation's provider
// re-sealable at all, by a pass that runs in that scope.
func (q *Queries) ListIdentityProviderSecrets(ctx context.Context) ([]ListIdentityProviderSecretsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityProviderSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentityProviderSecretsRow{}
	for rows.Next() {
		var i ListIdentityProviderSecretsRow
		if err := rows.Scan(&i.ID, &i.ClientSecretEnc, &i.ClientSecretKeyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityProviders = `-- name: ListIdentityProviders :many

SELECT id, tenant_id, issuer, client_id, display_name, kind, provisioning, position,
  allowed_email_domains, allowed_directories, enabled, created_at, updated_at, version
FROM identity_provider
ORDER BY (tenant_id IS NULL), position, created_at, id
`

type ListIdentityProvidersRow struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	Issuer              string
	ClientID            string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int32
}

// The relying-party surface (H-04, SI-10): the providers a workspace signs in through, and the
// flows of one sign-in.
//
// Every statement here runs inside the transaction wrapper that sets `app.tenant_id`, so the
// policy underneath answers "which level" - `current_tenant_id()` is written on insert rather than
// passed in, and in the installation's own scope it is NULL, which is exactly the row that belongs
// to no workspace. One insert statement therefore serves both levels, and nothing has to decide
// which one it is in.
// The ways in that are in force here: this workspace's own rows and the installation's, which the
// read policy admits together (migration 0103). The workspace's come first - its own choices sit
// above the default it inherited - and the sealed secret is in none of it.
func (q *Queries) ListIdentityProviders(ctx context.Context) ([]ListIdentityProvidersRow, error) {
	rows, err := q.db.Query(ctx, listIdentityProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIdentityProvidersRow{}
	for rows.Next() {
		var i ListIdentityProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Issuer,
			&i.ClientID,
			&i.DisplayName,
			&i.Kind,
			&i.Provisioning,
			&i.Position,
			&i.AllowedEmailDomains,
			&i.AllowedDirectories,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rewrapIdentityProviderSecret = `-- name: RewrapIdentityProviderSecret :execrows
UPDATE identity_provider
SET client_secret_enc = $1, client_secret_key_id = $2
WHERE id = $3 AND client_secret_key_id = $4
`

type RewrapIdentityProviderSecretParams struct {
	ClientSecretEnc   []byte
	ClientSecretKeyID string
	ID                pgtype.UUID
	ExpectedKeyID     string
}

// A re-seal (ADR-0045): the wrapping moves, the configuration does not, so the version stays -
// an operator rotating the installation's keys has not changed anybody's provider.
func (q *Queries) RewrapIdentityProviderSecret(ctx context.Context, arg RewrapIdentityProviderSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapIdentityProviderSecret,
		arg.ClientSecretEnc,
		arg.ClientSecretKeyID,
		arg.ID,
		arg.ExpectedKeyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIdentityProvider = `-- name: UpdateIdentityProvider :one
UPDATE identity_provider SET
  issuer                = $1,
  client_id             = $2,
  client_secret_enc     = coalesce($3, client_secret_enc),
  client_secret_key_id  = coalesce($4, client_secret_key_id),
  display_name          = $5,
  kind                  = $6,
  provisioning          = $7,
  position              = $8,
  allowed_email_domains = $9,
  allowed_directories   = $10,
  enabled               = $11,
  updated_at            = $12,
  version               = version + 1
WHERE id = $13
RETURNING id, tenant_id, issuer, client_id, display_name, kind, provisioning, position,
  allowed_email_domains, allowed_directories, enabled, created_at, updated_at, version
`

type UpdateIdentityProviderParams struct {
	Issuer              string
	ClientID            string
	ClientSecretEnc     []byte
	ClientSecretKeyID   *string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	Now                 pgtype.Timestamptz
	ID                  pgtype.UUID
}

type UpdateIdentityProviderRow struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	Issuer              string
	ClientID            string
	DisplayName         string
	Kind                string
	Provisioning        string
	Position            int32
	AllowedEmailDomains []string
	AllowedDirectories  []string
	Enabled             bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int32
}

// Set whole, not patched: a provider half-changed is a provider nobody can reason about. The
// secret is the one exception and the reason is that there is no way to read it back - a caller
// that sent none means "keep the one that is sealed", and COALESCE is what says so in a single
// statement rather than a read-then-write two sign-ins could interleave.
//
// The version rises on every write, so a concurrent second configuration is visible as a conflict.
func (q *Queries) UpdateIdentityProvider(ctx context.Context, arg UpdateIdentityProviderParams) (UpdateIdentityProviderRow, error) {
	row := q.db.QueryRow(ctx, updateIdentityProvider,
		arg.Issuer,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.ClientSecretKeyID,
		arg.DisplayName,
		arg.Kind,
		arg.Provisioning,
		arg.Position,
		arg.AllowedEmailDomains,
		arg.AllowedDirectories,
		arg.Enabled,
		arg.Now,
		arg.ID,
	)
	var i UpdateIdentityProviderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Issuer,
		&i.ClientID,
		&i.DisplayName,
		&i.Kind,
		&i.Provisioning,
		&i.Position,
		&i.AllowedEmailDomains,
		&i.AllowedDirectories,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
