// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Import.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimImportRun = `-- name: ClaimImportRun :execrows
UPDATE import_run SET
  status     = 'RUNNING',
  started_at = COALESCE(started_at, $1::timestamptz)
WHERE id = $2
  AND status IN ('PENDING', 'RUNNING')
`

type ClaimImportRunParams struct {
	StartedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// The claim: a job that died and is picked up again claims the same row a second time, so
// RUNNING is among the states it may claim from and started_at is kept rather than moved.
func (q *Queries) ClaimImportRun(ctx context.Context, arg ClaimImportRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimImportRun, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findImportRun = `-- name: FindImportRun :one
SELECT id, tenant_id, requested_by, kind, media_id, hub_id, mapping, time_zone, language, status,
       report, refused, progress, error_code, created_at, started_at, finished_at
FROM import_run
WHERE id = $1
`

func (q *Queries) FindImportRun(ctx context.Context, id pgtype.UUID) (ImportRun, error) {
	row := q.db.QueryRow(ctx, findImportRun, id)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequestedBy,
		&i.Kind,
		&i.MediaID,
		&i.HubID,
		&i.Mapping,
		&i.TimeZone,
		&i.Language,
		&i.Status,
		&i.Report,
		&i.Refused,
		&i.Progress,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishImportRun = `-- name: FinishImportRun :execrows
UPDATE import_run SET
  status      = $1,
  report      = COALESCE($2, report),
  refused     = COALESCE($3, refused),
  error_code  = $4,
  finished_at = $5
WHERE id = $6
  AND status IN ('PENDING', 'RUNNING')
`

type FinishImportRunParams struct {
	Status     string
	Report     []byte
	Refused    []byte
	ErrorCode  *string
	FinishedAt pgtype.Timestamptz
	ID         pgtype.UUID
}

// Refused for a run that is no longer going. COALESCE on the report, so that a failure with
// nothing to report does not erase what the attempt before it got through.
func (q *Queries) FinishImportRun(ctx context.Context, arg FinishImportRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishImportRun,
		arg.Status,
		arg.Report,
		arg.Refused,
		arg.ErrorCode,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertImportRun = `-- name: InsertImportRun :exec

INSERT INTO import_run (
  id, tenant_id, requested_by, kind, media_id, hub_id, mapping, time_zone, language, status
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6, $7,
  $8, 'PENDING'
)
`

type InsertImportRunParams struct {
	ID          pgtype.UUID
	RequestedBy pgtype.UUID
	Kind        string
	MediaID     pgtype.UUID
	HubID       pgtype.UUID
	Mapping     []byte
	TimeZone    *string
	Language    *string
}

// The import from another system (P-08, backup-restore.md §9). Every statement is bounded by the
// transaction's tenant (SET LOCAL app.tenant_id) and the row level security on import_run.
// The run row, written in the transaction that accepts the import. PENDING: the job has not
// started, and a caller polling `result_url` sees that rather than a 404.
func (q *Queries) InsertImportRun(ctx context.Context, arg InsertImportRunParams) error {
	_, err := q.db.Exec(ctx, insertImportRun,
		arg.ID,
		arg.RequestedBy,
		arg.Kind,
		arg.MediaID,
		arg.HubID,
		arg.Mapping,
		arg.TimeZone,
		arg.Language,
	)
	return err
}

const recordImportProgress = `-- name: RecordImportProgress :execrows
UPDATE import_run SET
  report   = $1,
  progress = $2
WHERE id = $3
  AND status IN ('PENDING', 'RUNNING')
`

type RecordImportProgressParams struct {
	Report   []byte
	Progress []byte
	ID       pgtype.UUID
}

// How far the run has got, written in the transaction of the batch it got there with, so that a
// resumed attempt skips what an earlier one decided (the applier's BK-7 rule).
func (q *Queries) RecordImportProgress(ctx context.Context, arg RecordImportProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordImportProgress, arg.Report, arg.Progress, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
