// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Job.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE job SET
  state        = 'CANCELLED',
  finished_at  = $1,
  locked_until = NULL
WHERE id = $2
  AND tenant_id = $3
  AND state IN ('PENDING', 'RUNNING')
RETURNING id, tenant_id, state, last_error, created_at, finished_at
`

type CancelJobParams struct {
	Now      pgtype.Timestamptz
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

type CancelJobRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	State      string
	LastError  *string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

// Cancellation, and it is the state change alone: no lease is named, because the caller holds
// none. A pass that is under way is not interrupted - it finds at its next write that the row is
// no longer RUNNING under its lease, and rolls back rather than applying its work (test RT-3 is
// the same fence). The lease is cleared so that nothing waits for it to expire.
//
// The state condition is what makes a terminal job a conflict rather than a silent overwrite: a
// job that succeeded a second ago must not read back as cancelled.
func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (CancelJobRow, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.Now, arg.ID, arg.TenantID)
	var i CancelJobRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const claimJobs = `-- name: ClaimJobs :many
UPDATE job SET
  state        = 'RUNNING',
  attempts     = attempts + 1,
  locked_until = $1
WHERE id IN (
  -- The alias is not decoration: without it every column in here reads as a reference to the row
  -- being updated, and "run_at" would mean two different things in one statement.
  SELECT due.id FROM job AS due
  WHERE (due.state = 'PENDING' AND due.run_at <= $2)
     OR (due.state = 'RUNNING' AND due.locked_until < $2)
  ORDER BY due.priority, due.run_at
  FOR UPDATE SKIP LOCKED
  LIMIT $3
)
RETURNING id, tenant_id, kind, payload, attempts, max_attempts, locked_until
`

type ClaimJobsParams struct {
	LockedUntil pgtype.Timestamptz
	Now         pgtype.Timestamptz
	BatchSize   int32
}

type ClaimJobsRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Kind        string
	Payload     []byte
	Attempts    int32
	MaxAttempts int32
	LockedUntil pgtype.Timestamptz
}

// The claim. Two kinds of row are claimable: one that is due, and one whose lease has run out -
// the second is a job whose worker died, and picking it up again is the whole reason a lease has
// an end.
func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]ClaimJobsRow, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.LockedUntil, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimJobsRow{}
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE job SET
  state        = 'SUCCEEDED',
  finished_at  = $1,
  locked_until = NULL,
  last_error   = NULL
WHERE id = $2 AND state = 'RUNNING' AND locked_until = $3
`

type CompleteJobParams struct {
	Now   pgtype.Timestamptz
	ID    pgtype.UUID
	Lease pgtype.Timestamptz
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.Now, arg.ID, arg.Lease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE job SET
  state        = 'DEAD_LETTER',
  finished_at  = $1,
  locked_until = NULL,
  last_error   = $2
WHERE id = $3 AND state = 'RUNNING' AND locked_until = $4
`

type DeadLetterJobParams struct {
	Now       pgtype.Timestamptz
	LastError *string
	ID        pgtype.UUID
	Lease     pgtype.Timestamptz
}

// The dead letter keeps the context an operator needs to act: which kind, which tenant, what it
// was given, how often it was tried, and the code of the last failure. Never a message - a message
// can carry what the job was working on (rule 10).
func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterJob,
		arg.Now,
		arg.LastError,
		arg.ID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :exec

INSERT INTO job (id, tenant_id, kind, payload, dedupe_key, run_at, max_attempts)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (kind, dedupe_key) WHERE dedupe_key IS NOT NULL AND state IN ('PENDING','RUNNING')
DO UPDATE SET run_at = LEAST(job.run_at, EXCLUDED.run_at)
WHERE job.state = 'PENDING'
`

type EnqueueJobParams struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Kind        string
	Payload     []byte
	DedupeKey   *string
	RunAt       pgtype.Timestamptz
	MaxAttempts int32
}

// The job queue (ADR-0008). Picked up with FOR UPDATE SKIP LOCKED, so several workers claim
// disjoint batches instead of queueing behind each other.
//
// The job table is the one table without row level security (db/migrations/0001_init.sql): part of
// the queue belongs to no tenant, and a worker must be able to read it before it knows whose job
// the next one is. Every statement here therefore carries its own conditions - there is no policy
// underneath that would catch a forgotten one.
//
// Every statement that finishes an attempt names the lease it is finishing. That is the fence: if
// the lease expired and somebody else claimed the job in the meantime, the update matches nothing,
// the caller's transaction rolls back, and the work of the process that fell behind is discarded
// rather than applied twice (test RT-3).
// Enqueue, or leave the job that is already scheduled alone. The dedupe key collapses "make sure
// this is being worked on" into one row; when the waiting job is due later than the new request,
// its wake-up is pulled forward rather than a second row being created. A job that is already
// running is not touched: its own reschedule decides when it runs next.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.RunAt,
		arg.MaxAttempts,
	)
	return err
}

const findJob = `-- name: FindJob :one
SELECT id, tenant_id, state, last_error, created_at, finished_at
FROM job
WHERE id = $1 AND tenant_id = $2
`

type FindJobParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

type FindJobRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	State      string
	LastError  *string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

// What a caller polls, and the only two statements here that are asked on somebody's behalf
// rather than by a worker. They therefore carry the tenant condition themselves - the job table
// has no row level security, so there is no policy underneath that would catch a forgotten one,
// and a NULL tenant_id (the queue's own housekeeping) matches no caller's tenant by construction.
//
// The columns are the resource's, not the row's: no payload, no attempt count, no lease, no
// dedupe key. Selecting them and dropping them later is how one of them eventually reaches a
// response by accident.
func (q *Queries) FindJob(ctx context.Context, arg FindJobParams) (FindJobRow, error) {
	row := q.db.QueryRow(ctx, findJob, arg.ID, arg.TenantID)
	var i FindJobRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.State,
		&i.LastError,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const holdJob = `-- name: HoldJob :one
SELECT id FROM job
WHERE id = $1 AND state = 'RUNNING' AND locked_until = $2
FOR UPDATE
`

type HoldJobParams struct {
	ID    pgtype.UUID
	Lease pgtype.Timestamptz
}

// The row lock a pass takes on its own job, held until the caller's transaction ends (D-03).
//
// SELECT ... FOR UPDATE rather than an UPDATE: nothing about the row changes, and what is wanted
// is only that a concurrent Enqueue on this dedupe key waits for the pass rather than finding the
// row RUNNING and doing nothing. The lease is in the predicate for the reason every other
// statement here carries it: a worker that fell behind and lost the job locks nothing.
func (q *Queries) HoldJob(ctx context.Context, arg HoldJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, holdJob, arg.ID, arg.Lease)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const jobQueueDepth = `-- name: JobQueueDepth :many
SELECT kind, count(*) AS pending
FROM job
WHERE state = 'PENDING' AND run_at <= $1
GROUP BY kind
`

type JobQueueDepthRow struct {
	Kind    string
	Pending int64
}

// The backlog: what is due and waiting, not what is running. Counting work in flight would make a
// busy queue look like a stuck one, and the alert hangs off this number rising (alert A-06).
func (q *Queries) JobQueueDepth(ctx context.Context, now pgtype.Timestamptz) ([]JobQueueDepthRow, error) {
	rows, err := q.db.Query(ctx, jobQueueDepth, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobQueueDepthRow{}
	for rows.Next() {
		var i JobQueueDepthRow
		if err := rows.Scan(&i.Kind, &i.Pending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repeatJob = `-- name: RepeatJob :execrows
UPDATE job SET
  state        = 'PENDING',
  run_at       = $1,
  attempts     = 0,
  locked_until = NULL,
  last_error   = NULL
WHERE id = $2 AND state = 'RUNNING' AND locked_until = $3
`

type RepeatJobParams struct {
	RunAt pgtype.Timestamptz
	ID    pgtype.UUID
	Lease pgtype.Timestamptz
}

// A poller's next round rather than a retry: the attempts start again from zero, because the round
// that just finished succeeded.
func (q *Queries) RepeatJob(ctx context.Context, arg RepeatJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, repeatJob, arg.RunAt, arg.ID, arg.Lease)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE job SET
  state        = 'PENDING',
  run_at       = $1,
  locked_until = NULL,
  last_error   = $2
WHERE id = $3 AND state = 'RUNNING' AND locked_until = $4
`

type RetryJobParams struct {
	RunAt     pgtype.Timestamptz
	LastError *string
	ID        pgtype.UUID
	Lease     pgtype.Timestamptz
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.RunAt,
		arg.LastError,
		arg.ID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
