// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustMediaRefCount = `-- name: AdjustMediaRefCount :execrows
UPDATE media_object SET
  ref_count = GREATEST(ref_count + $1::int, 0)
WHERE id = $2::uuid
`

type AdjustMediaRefCountParams struct {
	Delta int32
	ID    pgtype.UUID
}

// The fast half of reference counting: the use case that adds or drops a reference moves the
// counter in its own transaction, so DeleteMedia can refuse a referenced object without a scan.
// The reconciliation job recomputes the counter from the actual references, because a purge's
// cascade drops attachment rows without passing through here - the counter is a cache, and the
// recount is what makes it honest (data-protection.md §5).
func (q *Queries) AdjustMediaRefCount(ctx context.Context, arg AdjustMediaRefCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, adjustMediaRefCount, arg.Delta, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItemAttachment = `-- name: DeleteItemAttachment :execrows
DELETE FROM item_attachment
WHERE item_id = $1::uuid AND media_id = $2::uuid
`

type DeleteItemAttachmentParams struct {
	ItemID  pgtype.UUID
	MediaID pgtype.UUID
}

func (q *Queries) DeleteItemAttachment(ctx context.Context, arg DeleteItemAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemAttachment, arg.ItemID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMediaObjectRow = `-- name: DeleteMediaObjectRow :execrows
UPDATE media_object SET deleted_at = $1
WHERE id = $2::uuid AND ref_count = 0 AND deleted_at IS NULL
`

type DeleteMediaObjectRowParams struct {
	DeletedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// The record's removal, by hand (DeleteMedia): only an unreferenced, live object matches. The
// bytes are the reconciliation job's to remove - a request has no business waiting on a bucket.
func (q *Queries) DeleteMediaObjectRow(ctx context.Context, arg DeleteMediaObjectRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaObjectRow, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findMediaObject = `-- name: FindMediaObject :one
SELECT id, tenant_id, storage_key, file_name, mime_type, byte_size, checksum, usage, status,
       ref_count, created_by, created_at, deleted_at
FROM media_object
WHERE id = $1
`

type FindMediaObjectRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	StorageKey string
	FileName   *string
	MimeType   string
	ByteSize   int64
	Checksum   *string
	Usage      string
	Status     string
	RefCount   int32
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

func (q *Queries) FindMediaObject(ctx context.Context, id pgtype.UUID) (FindMediaObjectRow, error) {
	row := q.db.QueryRow(ctx, findMediaObject, id)
	var i FindMediaObjectRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageKey,
		&i.FileName,
		&i.MimeType,
		&i.ByteSize,
		&i.Checksum,
		&i.Usage,
		&i.Status,
		&i.RefCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertItemAttachment = `-- name: InsertItemAttachment :execrows
INSERT INTO item_attachment (tenant_id, item_id, media_id)
VALUES (current_tenant_id(), $1, $2)
ON CONFLICT DO NOTHING
`

type InsertItemAttachmentParams struct {
	ItemID  pgtype.UUID
	MediaID pgtype.UUID
}

// ON CONFLICT DO NOTHING, for the reason AddItemMember gives: attaching what is already attached
// is the state the caller asked for, and zero rows is how the caller knows not to raise the
// reference count twice.
func (q *Queries) InsertItemAttachment(ctx context.Context, arg InsertItemAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertItemAttachment, arg.ItemID, arg.MediaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMediaObject = `-- name: InsertMediaObject :exec

INSERT INTO media_object (
  id, tenant_id, storage_key, file_name, mime_type, byte_size, usage, status,
  ref_count, created_by, created_at
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6, $7,
  0, $8, $9
)
`

type InsertMediaObjectParams struct {
	ID         pgtype.UUID
	StorageKey string
	FileName   *string
	MimeType   string
	ByteSize   int64
	Usage      string
	Status     string
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

// The media objects and what references them (C-06, domain-model.md §3.5).
//
// The tenant is never a parameter: it comes from the transaction's own context through
// current_tenant_id(), the same value row level security compares against (ADR-0010).
func (q *Queries) InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) error {
	_, err := q.db.Exec(ctx, insertMediaObject,
		arg.ID,
		arg.StorageKey,
		arg.FileName,
		arg.MimeType,
		arg.ByteSize,
		arg.Usage,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listItemAttachmentIDs = `-- name: ListItemAttachmentIDs :many
SELECT media_id FROM item_attachment
WHERE item_id = $1::uuid
ORDER BY media_id
`

// The identifiers alone, ordered stably: what the attach and detach answers carry.
func (q *Queries) ListItemAttachmentIDs(ctx context.Context, itemID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listItemAttachmentIDs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var media_id pgtype.UUID
		if err := rows.Scan(&media_id); err != nil {
			return nil, err
		}
		items = append(items, media_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemAttachments = `-- name: ListItemAttachments :many
SELECT m.id, m.tenant_id, m.storage_key, m.file_name, m.mime_type, m.byte_size, m.checksum,
       m.usage, m.status, m.ref_count, m.created_by, m.created_at, m.deleted_at
FROM item_attachment a
JOIN media_object m ON m.id = a.media_id
WHERE a.item_id = $1::uuid
  AND (
    $2::timestamptz IS NULL
    OR (m.created_at, m.id) > ($2::timestamptz, $3::uuid)
  )
ORDER BY m.created_at, m.id
LIMIT $4
`

type ListItemAttachmentsParams struct {
	ItemID          pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListItemAttachmentsRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	StorageKey string
	FileName   *string
	MimeType   string
	ByteSize   int64
	Checksum   *string
	Usage      string
	Status     string
	RefCount   int32
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

// One page of an entry's attachments as media objects, oldest upload first. The keyset is
// (created_at, id) over the media object, for the reason every list here pages that way
// (api-guidelines.md §4).
func (q *Queries) ListItemAttachments(ctx context.Context, arg ListItemAttachmentsParams) ([]ListItemAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listItemAttachments,
		arg.ItemID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemAttachmentsRow{}
	for rows.Next() {
		var i ListItemAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StorageKey,
			&i.FileName,
			&i.MimeType,
			&i.ByteSize,
			&i.Checksum,
			&i.Usage,
			&i.Status,
			&i.RefCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaReferencingItems = `-- name: ListMediaReferencingItems :many
SELECT id, collection_id FROM work_item WHERE cover_media_id = $1::uuid
UNION
SELECT w.id, w.collection_id
FROM item_attachment a JOIN work_item w ON w.id = a.item_id
WHERE a.media_id = $1::uuid
LIMIT 50
`

type ListMediaReferencingItemsRow struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
}

// The items an object serves, for GetMedia's authorisation: whoever may read one of them may
// read the object's record. Bounded - the question is "may this actor see it", and fifty items
// answer it or nothing will.
func (q *Queries) ListMediaReferencingItems(ctx context.Context, mediaID pgtype.UUID) ([]ListMediaReferencingItemsRow, error) {
	rows, err := q.db.Query(ctx, listMediaReferencingItems, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaReferencingItemsRow{}
	for rows.Next() {
		var i ListMediaReferencingItemsRow
		if err := rows.Scan(&i.ID, &i.CollectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaOrphans = `-- name: MarkMediaOrphans :execrows
UPDATE media_object SET deleted_at = $1
WHERE deleted_at IS NULL
  AND ref_count = 0
  AND (
    (status = 'READY'
      AND unreferenced_since IS NOT NULL
      AND unreferenced_since < $2)
    OR (status = 'PENDING' AND created_at < $3)
  )
`

type MarkMediaOrphansParams struct {
	Now                pgtype.Timestamptz
	UnreferencedBefore pgtype.Timestamptz
	PendingBefore      pgtype.Timestamptz
}

// The second pass: what nothing references is marked, not yet removed. Both kinds wait, and they
// wait on different clocks. A READY object is garbage once nothing has pointed at it for the
// unreferenced grace - never merely because a pass caught it between its confirmation and the
// first thing that uses it, which is a window every upload passes through and every detach opens
// again. A PENDING row is a staging nobody confirmed, and its clock runs from the staging.
//
// Marking is not a reversible step, which is why the grace sits here rather than after it: a
// marked object is refused by every read path, so nothing can attach it, so nothing can ever
// recount it back to life.
func (q *Queries) MarkMediaOrphans(ctx context.Context, arg MarkMediaOrphansParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaOrphans, arg.Now, arg.UnreferencedBefore, arg.PendingBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recountMediaReferences = `-- name: RecountMediaReferences :exec
UPDATE media_object m SET
  ref_count = c.total,
  unreferenced_since = CASE
    WHEN c.total = 0 THEN COALESCE(m.unreferenced_since, $1)
    ELSE NULL
  END
FROM (
  SELECT o.id,
    (SELECT count(*) FROM item_attachment a WHERE a.media_id = o.id)
    + (SELECT count(*) FROM work_item w WHERE w.cover_media_id = o.id) AS total
  FROM media_object o
  WHERE o.deleted_at IS NULL
) c
WHERE m.id = c.id AND m.deleted_at IS NULL
`

// The reconciliation's first pass: the counter becomes what the references say, and a row that
// nothing points at learns since when. Whole-tenant, which is a scan by design - the job runs in
// the background on a bounded table, and a recount that tried to be incremental would be a second
// bookkeeping to get wrong.
//
// The stamp is maintained here rather than beside every AdjustRefCount, because this is already
// the statement that rewrites the counter for every live row: six call sites moving a counter are
// six places to forget, and this one cannot drift from the count it sets in the same breath.
// COALESCE keeps the first zero rather than the latest one - a row unreferenced for a week must
// not have its grace restarted by every pass that walks past it - and a row that gained a
// reference has its stamp cleared, which is what makes the grace start again when it next loses
// one.
func (q *Queries) RecountMediaReferences(ctx context.Context, now pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, recountMediaReferences, now)
	return err
}

const removeMediaObjectRows = `-- name: RemoveMediaObjectRows :execrows
DELETE FROM media_object WHERE id = ANY($1::uuid[])
`

// The rows go with the journal entries in one transaction; the bytes follow through the purge
// job, which retries - at least once, idempotent at the store (core/port/storage).
func (q *Queries) RemoveMediaObjectRows(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeMediaObjectRows, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sealMediaObject = `-- name: SealMediaObject :execrows
UPDATE media_object SET
  status    = 'READY',
  mime_type = $1,
  byte_size = $2
WHERE id = $3::uuid AND status = 'PENDING' AND deleted_at IS NULL
`

type SealMediaObjectParams struct {
	MimeType string
	ByteSize int64
	ID       pgtype.UUID
}

// The confirmation's write: PENDING becomes READY, carrying the judged type and the measured
// size. Matches only a live PENDING row, so a double confirmation and a confirmation racing the
// reconciliation job both come back as zero rows - the caller reads the row again and answers
// from what it finds.
func (q *Queries) SealMediaObject(ctx context.Context, arg SealMediaObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, sealMediaObject, arg.MimeType, arg.ByteSize, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeMediaOrphans = `-- name: TakeMediaOrphans :many
SELECT id, storage_key
FROM media_object
WHERE deleted_at IS NOT NULL AND deleted_at <= $1
ORDER BY deleted_at
LIMIT $2
`

type TakeMediaOrphansParams struct {
	MarkedBefore pgtype.Timestamptz
	Batch        int32
}

type TakeMediaOrphansRow struct {
	ID         pgtype.UUID
	StorageKey string
}

// The third pass: marked rows past their grace, handed to the purge job. The keys travel in the
// job's payload, so the byte deletion needs no transaction of its own to find them.
func (q *Queries) TakeMediaOrphans(ctx context.Context, arg TakeMediaOrphansParams) ([]TakeMediaOrphansRow, error) {
	rows, err := q.db.Query(ctx, takeMediaOrphans, arg.MarkedBefore, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TakeMediaOrphansRow{}
	for rows.Next() {
		var i TakeMediaOrphansRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
