// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Meta.sql

package sqlc

import (
	"context"
)

const listCapabilityProfiles = `-- name: ListCapabilityProfiles :many

SELECT DISTINCT ON (type)
  type,
  capabilities,
  allowed_child_types,
  max_depth
FROM item_capability_profile
ORDER BY type, (tenant_id IS NOT NULL) DESC
`

type ListCapabilityProfilesRow struct {
	Type              ItemType
	Capabilities      []string
	AllowedChildTypes []ItemType
	MaxDepth          int32
}

// The profile that applies, one row per item type: a tenant's own override when it has one, the
// system default otherwise. DISTINCT ON does the choosing in the database, so the application
// never has to merge two lists and never has to decide which wins.
//
// No tenant condition: row level security shows the system rows plus this tenant's, and nothing
// else (db/schema.sql, item_capability_profile).
func (q *Queries) ListCapabilityProfiles(ctx context.Context) ([]ListCapabilityProfilesRow, error) {
	rows, err := q.db.Query(ctx, listCapabilityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCapabilityProfilesRow{}
	for rows.Next() {
		var i ListCapabilityProfilesRow
		if err := rows.Scan(
			&i.Type,
			&i.Capabilities,
			&i.AllowedChildTypes,
			&i.MaxDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemCapabilityProfiles = `-- name: ListSystemCapabilityProfiles :many
SELECT type, capabilities, allowed_child_types, max_depth
FROM item_capability_profile
WHERE tenant_id IS NULL
ORDER BY type
`

type ListSystemCapabilityProfilesRow struct {
	Type              ItemType
	Capabilities      []string
	AllowedChildTypes []ItemType
	MaxDepth          int32
}

// The system defaults alone, whatever the caller's tenant has overridden.
//
// They bound what a narrowing may do, and one question can only be answered from them: which
// types sit directly under a collection. Read off a narrowed set, a tenant that removed a task's
// children would promote the work package to a top level it was never allowed to sit at
// (domain-model.md §2).
func (q *Queries) ListSystemCapabilityProfiles(ctx context.Context) ([]ListSystemCapabilityProfilesRow, error) {
	rows, err := q.db.Query(ctx, listSystemCapabilityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemCapabilityProfilesRow{}
	for rows.Next() {
		var i ListSystemCapabilityProfilesRow
		if err := rows.Scan(
			&i.Type,
			&i.Capabilities,
			&i.AllowedChildTypes,
			&i.MaxDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextLanguages = `-- name: ListTextLanguages :many
SELECT l.tag::text FROM hubtask_text_languages() AS l(tag, configuration)
`

// The languages this installation can index, as BCP 47 tags (C-08, ADR-0034).
//
// Read from the database rather than listed in Go, because it is the database that decides: the
// mapping lives in `hubtask_text_languages()`, which joins the tags this product knows against the
// text search configurations this PostgreSQL was actually built with. A constant in the
// application would answer for an installation that has one configuration fewer, and a client's
// language picker would then offer a language that is silently indexed word by word.
func (q *Queries) ListTextLanguages(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTextLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var l_tag string
		if err := rows.Scan(&l_tag); err != nil {
			return nil, err
		}
		items = append(items, l_tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
