// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountKind string

const (
	AccountKindUSER           AccountKind = "USER"
	AccountKindSERVICEACCOUNT AccountKind = "SERVICE_ACCOUNT"
)

func (e *AccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountKind(s)
	case string:
		*e = AccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountKind: %T", src)
	}
	return nil
}

type NullAccountKind struct {
	AccountKind AccountKind
	Valid       bool // Valid is true if AccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.AccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountKind), nil
}

type AccountStatus string

const (
	AccountStatusACTIVE   AccountStatus = "ACTIVE"
	AccountStatusINVITED  AccountStatus = "INVITED"
	AccountStatusDISABLED AccountStatus = "DISABLED"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus
	Valid         bool // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type ContainerType string

const (
	ContainerTypeHUB        ContainerType = "HUB"
	ContainerTypeCOLLECTION ContainerType = "COLLECTION"
)

func (e *ContainerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContainerType(s)
	case string:
		*e = ContainerType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContainerType: %T", src)
	}
	return nil
}

type NullContainerType struct {
	ContainerType ContainerType
	Valid         bool // Valid is true if ContainerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContainerType) Scan(value interface{}) error {
	if value == nil {
		ns.ContainerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContainerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContainerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContainerType), nil
}

type ItemType string

const (
	ItemTypeTASK        ItemType = "TASK"
	ItemTypeWORKPACKAGE ItemType = "WORK_PACKAGE"
	ItemTypeACTIVITY    ItemType = "ACTIVITY"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type MembershipRole string

const (
	MembershipRoleOWNER       MembershipRole = "OWNER"
	MembershipRoleADMIN       MembershipRole = "ADMIN"
	MembershipRoleMEMBER      MembershipRole = "MEMBER"
	MembershipRoleCONTRIBUTOR MembershipRole = "CONTRIBUTOR"
	MembershipRoleVIEWER      MembershipRole = "VIEWER"
	MembershipRoleGUEST       MembershipRole = "GUEST"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole
	Valid          bool // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type MembershipScope string

const (
	MembershipScopeTENANT     MembershipScope = "TENANT"
	MembershipScopeHUB        MembershipScope = "HUB"
	MembershipScopeCOLLECTION MembershipScope = "COLLECTION"
	MembershipScopeITEM       MembershipScope = "ITEM"
)

func (e *MembershipScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipScope(s)
	case string:
		*e = MembershipScope(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipScope: %T", src)
	}
	return nil
}

type NullMembershipScope struct {
	MembershipScope MembershipScope
	Valid           bool // Valid is true if MembershipScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipScope) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipScope), nil
}

type TenantStatus string

const (
	TenantStatusACTIVE          TenantStatus = "ACTIVE"
	TenantStatusSUSPENDED       TenantStatus = "SUSPENDED"
	TenantStatusPENDINGDELETION TenantStatus = "PENDING_DELETION"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus
	Valid        bool // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type AccessToken struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	AccountID   pgtype.UUID
	Name        string
	TokenHash   []byte
	TokenPrefix string
	Scopes      []string
	ExpiresAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Account struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Kind            AccountKind
	Email           *string
	DisplayName     string
	ExternalSubject *string
	PasswordHash    *string
	Locale          *string
	TimeZone        *string
	WeekStart       *string
	Status          AccountStatus
	AiConsent       bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Version         int32
}

type AccountGroup struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Name        string
	Description *string
	CreatedAt   pgtype.Timestamptz
	Version     int32
}

type AccountGroupMember struct {
	TenantID  pgtype.UUID
	GroupID   pgtype.UUID
	AccountID pgtype.UUID
}

type ActivityEntry struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	ItemID        pgtype.UUID
	ContainerID   pgtype.UUID
	ActorType     string
	ActorID       pgtype.UUID
	Verb          string
	ChangeSet     []byte
	OccurredAt    pgtype.Timestamptz
	CorrelationID pgtype.UUID
	CausationID   pgtype.UUID
}

type AuditAnchor struct {
	TenantID    pgtype.UUID
	AnchoredAt  pgtype.Timestamptz
	LastSeq     int64
	ChainHash   []byte
	Destination *string
	Receipt     *string
}

type AuditLog struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Seq          int64
	OccurredAt   pgtype.Timestamptz
	Action       string
	Outcome      string
	Severity     string
	ActorType    string
	ActorID      pgtype.UUID
	ActorLabel   *string
	OnBehalfOfID pgtype.UUID
	TargetType   *string
	TargetID     pgtype.UUID
	TargetLabel  *string
	Context      []byte
	Changes      []byte
	LegalBasis   *string
	PrevHash     []byte
	Hash         []byte
}

type AuditLog202608 struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Seq          int64
	OccurredAt   pgtype.Timestamptz
	Action       string
	Outcome      string
	Severity     string
	ActorType    string
	ActorID      pgtype.UUID
	ActorLabel   *string
	OnBehalfOfID pgtype.UUID
	TargetType   *string
	TargetID     pgtype.UUID
	TargetLabel  *string
	Context      []byte
	Changes      []byte
	LegalBasis   *string
	PrevHash     []byte
	Hash         []byte
}

type AuditLogDefault struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Seq          int64
	OccurredAt   pgtype.Timestamptz
	Action       string
	Outcome      string
	Severity     string
	ActorType    string
	ActorID      pgtype.UUID
	ActorLabel   *string
	OnBehalfOfID pgtype.UUID
	TargetType   *string
	TargetID     pgtype.UUID
	TargetLabel  *string
	Context      []byte
	Changes      []byte
	LegalBasis   *string
	PrevHash     []byte
	Hash         []byte
}

type AutoAssignPolicy struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	ScopeType  string
	ScopeID    pgtype.UUID
	Strategy   string
	Candidates []byte
	State      []byte
	Enabled    bool
	Version    int32
}

type AutomationRule struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	ScopeType    string
	ScopeID      pgtype.UUID
	Name         string
	Enabled      bool
	RunAs        pgtype.UUID
	Trigger      []byte
	Conditions   []byte
	Actions      []byte
	Throttle     []byte
	OnError      string
	FailureCount int32
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
}

type BackupRun struct {
	ID          pgtype.UUID
	ScheduleID  pgtype.UUID
	TargetID    pgtype.UUID
	TenantID    pgtype.UUID
	ParentRunID pgtype.UUID
	Trigger     string
	Mode        string
	Status      string
	ArchivePath *string
	Manifest    []byte
	SizeBytes   *int64
	ItemCount   *int32
	MediaCount  *int32
	Checksum    *string
	SnapshotAt  pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	ErrorCode   *string
	ExpiresAt   pgtype.Timestamptz
	VerifiedAt  pgtype.Timestamptz
	VerifyOk    *bool
}

type BackupSchedule struct {
	ID           pgtype.UUID
	TargetID     pgtype.UUID
	TenantID     pgtype.UUID
	ScopeKind    string
	ScopeID      pgtype.UUID
	Rrule        string
	TimeZone     string
	Mode         string
	FullRrule    *string
	IncludeMedia bool
	IncludeAudit bool
	Retention    []byte
	NotifyOn     []string
	Enabled      bool
	NextRunAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Version      int32
}

type BackupTarget struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	Kind            string
	Config          []byte
	CredentialEnc   []byte
	CredentialKeyID *string
	EncryptionMode  string
	EncryptionKeyID *string
	RegionNote      *string
	InsecureAckBy   pgtype.UUID
	InsecureAckAt   pgtype.Timestamptz
	Enabled         bool
	LastTestAt      pgtype.Timestamptz
	LastTestOk      *bool
	LastTestError   *string
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	Version         int32
}

type Bucket struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	CollectionID pgtype.UUID
	Name         string
	OrderKey     string
	WipLimit     *int32
	IsDoneBucket bool
	ColorToken   *string
	DeletedAt    pgtype.Timestamptz
	Version      int32
}

type CalendarFeed struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	AccountID pgtype.UUID
	ViewID    pgtype.UUID
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type ChangeLog struct {
	TenantID    pgtype.UUID
	Seq         int64
	Entity      string
	EntityID    pgtype.UUID
	Op          string
	ContainerID pgtype.UUID
	ActorID     pgtype.UUID
	DeviceID    pgtype.UUID
	Hlc         string
	OccurredAt  pgtype.Timestamptz
	Payload     []byte
}

type ChangeLog202608 struct {
	TenantID    pgtype.UUID
	Seq         int64
	Entity      string
	EntityID    pgtype.UUID
	Op          string
	ContainerID pgtype.UUID
	ActorID     pgtype.UUID
	DeviceID    pgtype.UUID
	Hlc         string
	OccurredAt  pgtype.Timestamptz
	Payload     []byte
}

type ChangeLogDefault struct {
	TenantID    pgtype.UUID
	Seq         int64
	Entity      string
	EntityID    pgtype.UUID
	Op          string
	ContainerID pgtype.UUID
	ActorID     pgtype.UUID
	DeviceID    pgtype.UUID
	Hlc         string
	OccurredAt  pgtype.Timestamptz
	Payload     []byte
}

type Comment struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ItemID          pgtype.UUID
	AuthorID        pgtype.UUID
	ParentCommentID pgtype.UUID
	Body            string
	CreatedAt       pgtype.Timestamptz
	EditedAt        pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Version         int32
}

type ConsentRecord struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	Granted   bool
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Source    *string
}

type Container struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Type         ContainerType
	ParentID     pgtype.UUID
	Name         string
	Description  *string
	Icon         *string
	ColorToken   *string
	OrderKey     string
	Policies     []byte
	ArchivedAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	TrashBatchID pgtype.UUID
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int32
}

type CustomFieldDefinition struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	CollectionID pgtype.UUID
	Key          string
	Kind         string
	Options      []byte
	IsRequired   bool
	AppliesTo    []ItemType
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int32
}

type DataSubjectRequest struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	SubjectAccountID pgtype.UUID
	SubjectEmail     *string
	Kind             string
	Status           string
	ErasureMode      *string
	ReceivedAt       pgtype.Timestamptz
	DueAt            pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	HandledBy        pgtype.UUID
	RejectionReason  *string
	ResultMediaID    pgtype.UUID
	Notes            *string
}

type DeletionJournal struct {
	TenantID  pgtype.UUID
	Entity    string
	EntityID  pgtype.UUID
	DeletedAt pgtype.Timestamptz
	Reason    string
}

type EventConsumption struct {
	TenantID   pgtype.UUID
	Consumer   string
	EventID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	TenantID     pgtype.UUID
	Key          string
	Endpoint     string
	RequestHash  []byte
	ResponseCode *int32
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
}

type ItemAttachment struct {
	TenantID pgtype.UUID
	ItemID   pgtype.UUID
	MediaID  pgtype.UUID
}

type ItemCapabilityProfile struct {
	TenantID          pgtype.UUID
	Type              ItemType
	Capabilities      []string
	AllowedChildTypes []ItemType
	MaxDepth          int32
}

type ItemLabel struct {
	TenantID pgtype.UUID
	ItemID   pgtype.UUID
	LabelID  pgtype.UUID
}

type ItemMember struct {
	TenantID  pgtype.UUID
	ItemID    pgtype.UUID
	AccountID pgtype.UUID
}

type Job struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Kind        string
	Payload     []byte
	DedupeKey   *string
	RunAt       pgtype.Timestamptz
	State       string
	Attempts    int32
	MaxAttempts int32
	LockedUntil pgtype.Timestamptz
	LastError   *string
	Priority    int16
	CreatedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	Progress    *float32
}

type JumbleEntry struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Channel      string
	Sender       *string
	RawSubject   *string
	RawBody      *string
	Attachments  []pgtype.UUID
	Suggestion   []byte
	Status       string
	TargetItemID pgtype.UUID
	ReceivedAt   pgtype.Timestamptz
	ProcessedAt  pgtype.Timestamptz
}

type Label struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	CollectionID pgtype.UUID
	Name         string
	ColorToken   string
	Description  *string
	DeletedAt    pgtype.Timestamptz
	Version      int32
}

type LegalHold struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	ScopeKind      string
	ScopeID        pgtype.UUID
	Reason         string
	PlacedBy       pgtype.UUID
	PlacedAt       pgtype.Timestamptz
	ReleasedBy     pgtype.UUID
	ReleasedAt     pgtype.Timestamptz
	ReleasedReason *string
}

type MediaObject struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	StorageKey string
	MimeType   string
	ByteSize   int64
	Checksum   *string
	Usage      string
	RefCount   int32
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Status     string
	FileName   *string
}

type Membership struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	AccountID pgtype.UUID
	GroupID   pgtype.UUID
	ScopeType MembershipScope
	ScopeID   pgtype.UUID
	Role      MembershipRole
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	RecipientID pgtype.UUID
	Category    string
	Channel     string
	State       string
	Reason      *string
	EventID     pgtype.UUID
	ItemID      pgtype.UUID
	ActorID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	SentAt      pgtype.Timestamptz
	Attempts    int32
}

type NotificationPreference struct {
	TenantID     pgtype.UUID
	AccountID    pgtype.UUID
	Category     string
	Channel      string
	Enabled      bool
	IncludeTitle bool
	UpdatedAt    pgtype.Timestamptz
}

type OutboxEvent struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
	DispatchedAt   pgtype.Timestamptz
	Attempts       int32
	LockedUntil    pgtype.Timestamptz
	Replay         bool
}

type PrivacyIncident struct {
	ID                pgtype.UUID
	TenantID          pgtype.UUID
	DetectedAt        pgtype.Timestamptz
	ReportedAt        pgtype.Timestamptz
	Severity          string
	DataCategories    []string
	AffectedCount     *int32
	Description       string
	Measures          *string
	AuthorityNotified bool
	SubjectsNotified  bool
	ClosedAt          pgtype.Timestamptz
}

type RecurrenceRule struct {
	ID                 pgtype.UUID
	TenantID           pgtype.UUID
	SourceItemID       pgtype.UUID
	Rrule              string
	TimeZone           string
	Mode               string
	HorizonDays        int32
	EndsAt             pgtype.Timestamptz
	MaxCount           *int32
	LastMaterializedAt pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	Version            int32
	UpdatedAt          pgtype.Timestamptz
}

type Reminder struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	ItemID     pgtype.UUID
	OffsetSpec string
	Channels   []string
	Recipients []pgtype.UUID
	State      string
	FireAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Version    int32
	UpdatedAt  pgtype.Timestamptz
}

type RestoreRun struct {
	ID            pgtype.UUID
	TargetID      pgtype.UUID
	SourceArchive string
	// The tenant that asked for the restore, and the one the row is visible in (RLS).
	TenantID          pgtype.UUID
	Mode              string
	ConflictRule      string
	Selection         []byte
	DryRun            bool
	SafetyBackupRunID pgtype.UUID
	Status            string
	Report            []byte
	RequestedBy       pgtype.UUID
	ApprovedBy        pgtype.UUID
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	ErrorCode         *string
	// The tenant being restored into. Differs from tenant_id only for NEW_TENANT, and is NULL for an instance restore.
	TargetTenantID     pgtype.UUID
	CreateSafetyBackup bool
	Progress           []byte
}

type RetentionPolicy struct {
	TenantID      pgtype.UUID
	DataKind      string
	RetainDays    int32
	MinDays       int32
	MaxDays       *int32
	Justification *string
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
}

type RetentionRule struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	ScopeKind      string
	ScopeID        pgtype.UUID
	DataKind       string
	Condition      *string
	RetainDays     int32
	Action         string
	ThenAfterDays  *int32
	ThenAction     *string
	GraceDays      int32
	Notify         []byte
	Justification  *string
	Enabled        bool
	ExportTargetID pgtype.UUID
	CreatedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int32
}

type RetentionRun struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	PolicyID       pgtype.UUID
	DataKind       string
	Phase          string
	Matched        int32
	Affected       int32
	Blocked        int32
	BlockedReasons []byte
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	Status         string
}

type RuleRun struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	RuleID           pgtype.UUID
	EventID          pgtype.UUID
	Status           string
	ConditionResults []byte
	ActionResults    []byte
	ErrorCode        *string
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	CausationDepth   int32
}

type SavedView struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	ScopeType     string
	ScopeID       pgtype.UUID
	OwnerID       pgtype.UUID
	Name          string
	Layout        string
	Query         []byte
	Grouping      []byte
	VisibleFields []string
	Sharing       string
	CreatedAt     pgtype.Timestamptz
	Version       int32
}

type SetElement struct {
	TenantID  pgtype.UUID
	ItemID    pgtype.UUID
	SetName   string
	ElementID pgtype.UUID
	AddTag    *string
	RemoveTag *string
}

type SyncDevice struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	AccountID   pgtype.UUID
	Platform    *string
	DisplayName *string
	LastCursor  *int64
	LastSeenAt  pgtype.Timestamptz
	Scopes      []byte
	PushToken   *string
	Blocked     bool
	CreatedAt   pgtype.Timestamptz
}

type SyncOpLog struct {
	TenantID  pgtype.UUID
	OpID      pgtype.UUID
	DeviceID  pgtype.UUID
	Result    string
	EntityID  pgtype.UUID
	AppliedAt pgtype.Timestamptz
	Response  []byte
}

type Template struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
	Name        string
	Description *string
	RootType    ItemType
	Nodes       []byte
	CreatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
	UpdatedAt   pgtype.Timestamptz
}

type Tenant struct {
	ID              pgtype.UUID
	Slug            string
	DisplayName     string
	Status          TenantStatus
	DefaultLocale   string
	DefaultTimeZone string
	Settings        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	Version         int32
}

type Tombstone struct {
	TenantID   pgtype.UUID
	Entity     string
	EntityID   pgtype.UUID
	DeletedAt  pgtype.Timestamptz
	PurgeAfter pgtype.Timestamptz
}

type UsageRecord struct {
	TenantID pgtype.UUID
	Period   pgtype.Date
	Metric   string
	Value    int64
}

type WebhookDelivery struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	SubscriptionID pgtype.UUID
	EventID        pgtype.UUID
	Attempt        int32
	Status         string
	ResponseStatus *int32
	ErrorCode      *string
	NextAttemptAt  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type WebhookSubscription struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	TargetUrl    string
	EventTypes   []string
	FilterExpr   *string
	SecretEnc    []byte
	State        string
	FailureCount int32
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	Version      int32
}

type WorkItem struct {
	ID                    pgtype.UUID
	TenantID              pgtype.UUID
	CollectionID          pgtype.UUID
	Type                  ItemType
	ParentID              pgtype.UUID
	Path                  string
	Depth                 int32
	Title                 string
	Notes                 *string
	IsCompleted           bool
	CompletedAt           pgtype.Timestamptz
	CompletedBy           pgtype.UUID
	BucketID              pgtype.UUID
	OrderKey              string
	StartAt               pgtype.Timestamptz
	DueAt                 pgtype.Timestamptz
	DueDateOnly           bool
	DueTimeZone           *string
	AssigneeID            pgtype.UUID
	CoverKind             *string
	CoverColorToken       *string
	CoverMediaID          pgtype.UUID
	CustomFields          []byte
	RecurrenceRuleID      pgtype.UUID
	OriginJumbleID        pgtype.UUID
	ContentLanguage       *string
	SearchVector          interface{}
	ArchivedAt            pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	TrashBatchID          pgtype.UUID
	CreatedBy             pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Version               int32
	CustomFieldRefs       []byte
	SearchDocument        interface{}
	DueSoonAnnouncedAt    pgtype.Timestamptz
	OverdueAnnouncedAt    pgtype.Timestamptz
	RetentionPendingUntil pgtype.Timestamptz
	RetentionRuleID       pgtype.UUID
	RetentionAction       *string
}
