// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendOutboxEvent = `-- name: AppendOutboxEvent :exec

INSERT INTO outbox_event (
  id, tenant_id, event_type, subject, payload,
  actor_type, actor_id, correlation_id, causation_id, causation_depth, occurred_at, replay
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11
)
`

type AppendOutboxEventParams struct {
	ID             pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
	Replay         bool
}

// The transactional outbox (ADR-0007): the event is written in the same transaction as the change
// it describes, and the dispatcher delivers it afterwards.
//
// Both halves are here, and both run under row level security: an event is written into the tenant
// of the transaction, and read out of it again. A dispatcher therefore works one tenant at a time
// (multi-tenancy.md §2.1) - which is also what stops one busy tenant from filling every batch.
func (q *Queries) AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) error {
	_, err := q.db.Exec(ctx, appendOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.Subject,
		arg.Payload,
		arg.ActorType,
		arg.ActorID,
		arg.CorrelationID,
		arg.CausationID,
		arg.CausationDepth,
		arg.OccurredAt,
		arg.Replay,
	)
	return err
}

const claimEventConsumption = `-- name: ClaimEventConsumption :execrows
INSERT INTO event_consumption (tenant_id, consumer, event_id, consumed_at)
VALUES (current_tenant_id(), $1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimEventConsumptionParams struct {
	Consumer   string
	EventID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// The claim is the question (ADR-0007): a consumer inserts before it reacts, and an insert that
// changes nothing is the answer "somebody already has". Asking first and inserting afterwards
// would let two dispatchers both be told no.
func (q *Queries) ClaimEventConsumption(ctx context.Context, arg ClaimEventConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimEventConsumption, arg.Consumer, arg.EventID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingEvents = `-- name: ClaimPendingEvents :many
SELECT
  id, tenant_id, event_type, subject, payload,
  actor_type, actor_id, correlation_id, causation_id, causation_depth, occurred_at, replay
FROM outbox_event
WHERE dispatched_at IS NULL
ORDER BY occurred_at, id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimPendingEventsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
	Replay         bool
}

// The dispatcher's claim. The rows are locked for the length of the transaction and rows another
// dispatcher holds are skipped rather than waited for, so two workers on one tenant divide the
// work instead of queueing.
func (q *Queries) ClaimPendingEvents(ctx context.Context, batchSize int32) ([]ClaimPendingEventsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingEventsRow{}
	for rows.Next() {
		var i ClaimPendingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Subject,
			&i.Payload,
			&i.ActorType,
			&i.ActorID,
			&i.CorrelationID,
			&i.CausationID,
			&i.CausationDepth,
			&i.OccurredAt,
			&i.Replay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDispatchedEvents = `-- name: CountDispatchedEvents :one
SELECT count(*) FROM (
  SELECT 1 FROM outbox_event
  WHERE dispatched_at IS NOT NULL
    AND occurred_at < $1
  LIMIT $2
) AS due
`

type CountDispatchedEventsParams struct {
	Cutoff  pgtype.Timestamptz
	Ceiling int32
}

// How many rows are due, counted no higher than the ceiling: what the caller needs is "is there
// more after this batch" rather than a count of the table.
func (q *Queries) CountDispatchedEvents(ctx context.Context, arg CountDispatchedEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDispatchedEvents, arg.Cutoff, arg.Ceiling)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingEvents = `-- name: CountPendingEvents :one
SELECT count(*) FROM outbox_event WHERE dispatched_at IS NULL
`

// What is left for this tenant after a round: the dispatcher's decision between running again at
// once and going back to sleep.
func (q *Queries) CountPendingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDispatchedEvents = `-- name: DeleteDispatchedEvents :execrows
DELETE FROM outbox_event
WHERE id IN (
  SELECT due.id FROM outbox_event AS due
  WHERE due.dispatched_at IS NOT NULL
    AND due.occurred_at < $1
  ORDER BY due.occurred_at
  LIMIT $2
)
`

type DeleteDispatchedEventsParams struct {
	Cutoff pgtype.Timestamptz
	Batch  int32
}

// The retention sweep's batch (data-retention.md §3: anchor `occurred_at`, 7 days).
//
// The guard is `dispatched_at IS NOT NULL`, and it is a correctness rule rather than a retention
// one: the dispatcher stamps that column only after every subscriber has had the event, so a NULL
// means somebody has not consumed it yet. Such a row is never due, whatever period a tenant
// configures - deleting it would lose the event silently, which is the one failure an outbox
// exists to rule out (ADR-0007).
//
// Batched through a subquery, because DELETE takes no LIMIT: a pass that took every expired row
// would be a pass nobody can stop. Oldest first, so a backlog drains in the order it built up.
func (q *Queries) DeleteDispatchedEvents(ctx context.Context, arg DeleteDispatchedEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDispatchedEvents, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredConsumption = `-- name: DeleteExpiredConsumption :execrows
DELETE FROM event_consumption
WHERE (tenant_id, consumer, event_id) IN (
  SELECT due.tenant_id, due.consumer, due.event_id FROM event_consumption AS due
  WHERE due.consumed_at < $1
  ORDER BY due.consumed_at
  LIMIT $2
)
`

type DeleteExpiredConsumptionParams struct {
	Cutoff pgtype.Timestamptz
	Batch  int32
}

// The other half of the outbox's sweep: the record of who has already consumed what
// (core/port/eventbus.RetentionWindow).
//
// event_consumption_gc_idx has existed since phase 0 and nothing ever collected against it. The
// table is the outbox's twin - one row per event per consumer - so leaving it unswept would have
// made the sweep of the events themselves a half measure.
//
// The same period as the events, deliberately: a record whose event has been swept can say nothing
// about an event nobody can deliver again. Two periods that could drift apart would give one of
// them a value at which this stops being true.
func (q *Queries) DeleteExpiredConsumption(ctx context.Context, arg DeleteExpiredConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredConsumption, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOutboxEvent = `-- name: FindOutboxEvent :one
SELECT id, tenant_id, event_type, subject, payload, actor_type, actor_id,
       correlation_id, causation_id, causation_depth, occurred_at, replay
FROM outbox_event
WHERE id = $1
`

type FindOutboxEventRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
	Replay         bool
}

// One event, as it was written. The webhook deliverer renders the body from this rather than from
// a copy in the job payload, so a retry two days later sends what the first attempt would have -
// and a job row does not become a second place a workspace's content lives.
func (q *Queries) FindOutboxEvent(ctx context.Context, id pgtype.UUID) (FindOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, findOutboxEvent, id)
	var i FindOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Subject,
		&i.Payload,
		&i.ActorType,
		&i.ActorID,
		&i.CorrelationID,
		&i.CausationID,
		&i.CausationDepth,
		&i.OccurredAt,
		&i.Replay,
	)
	return i, err
}

const markEventsDispatched = `-- name: MarkEventsDispatched :exec
UPDATE outbox_event
SET dispatched_at = $1
WHERE id = ANY($2::uuid[])
`

type MarkEventsDispatchedParams struct {
	DispatchedAt pgtype.Timestamptz
	Ids          []pgtype.UUID
}

// Recorded in the same transaction as the delivery itself. A mark that committed without its
// delivery would lose the event silently, which is the one failure an outbox exists to rule out.
func (q *Queries) MarkEventsDispatched(ctx context.Context, arg MarkEventsDispatchedParams) error {
	_, err := q.db.Exec(ctx, markEventsDispatched, arg.DispatchedAt, arg.Ids)
	return err
}
