// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendOutboxEvent = `-- name: AppendOutboxEvent :exec

INSERT INTO outbox_event (
  id, tenant_id, event_type, subject, payload,
  actor_type, actor_id, correlation_id, causation_id, causation_depth, occurred_at
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10
)
`

type AppendOutboxEventParams struct {
	ID             pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
}

// The transactional outbox (ADR-0007): the event is written in the same transaction as the change
// it describes, and the dispatcher delivers it afterwards.
//
// Both halves are here, and both run under row level security: an event is written into the tenant
// of the transaction, and read out of it again. A dispatcher therefore works one tenant at a time
// (multi-tenancy.md §2.1) - which is also what stops one busy tenant from filling every batch.
func (q *Queries) AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) error {
	_, err := q.db.Exec(ctx, appendOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.Subject,
		arg.Payload,
		arg.ActorType,
		arg.ActorID,
		arg.CorrelationID,
		arg.CausationID,
		arg.CausationDepth,
		arg.OccurredAt,
	)
	return err
}

const claimEventConsumption = `-- name: ClaimEventConsumption :execrows
INSERT INTO event_consumption (tenant_id, consumer, event_id, consumed_at)
VALUES (current_tenant_id(), $1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimEventConsumptionParams struct {
	Consumer   string
	EventID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// The claim is the question (ADR-0007): a consumer inserts before it reacts, and an insert that
// changes nothing is the answer "somebody already has". Asking first and inserting afterwards
// would let two dispatchers both be told no.
func (q *Queries) ClaimEventConsumption(ctx context.Context, arg ClaimEventConsumptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimEventConsumption, arg.Consumer, arg.EventID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimPendingEvents = `-- name: ClaimPendingEvents :many
SELECT
  id, tenant_id, event_type, subject, payload,
  actor_type, actor_id, correlation_id, causation_id, causation_depth, occurred_at
FROM outbox_event
WHERE dispatched_at IS NULL
ORDER BY occurred_at, id
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ClaimPendingEventsRow struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
}

// The dispatcher's claim. The rows are locked for the length of the transaction and rows another
// dispatcher holds are skipped rather than waited for, so two workers on one tenant divide the
// work instead of queueing.
func (q *Queries) ClaimPendingEvents(ctx context.Context, batchSize int32) ([]ClaimPendingEventsRow, error) {
	rows, err := q.db.Query(ctx, claimPendingEvents, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingEventsRow{}
	for rows.Next() {
		var i ClaimPendingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Subject,
			&i.Payload,
			&i.ActorType,
			&i.ActorID,
			&i.CorrelationID,
			&i.CausationID,
			&i.CausationDepth,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingEvents = `-- name: CountPendingEvents :one
SELECT count(*) FROM outbox_event WHERE dispatched_at IS NULL
`

// What is left for this tenant after a round: the dispatcher's decision between running again at
// once and going back to sleep.
func (q *Queries) CountPendingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markEventsDispatched = `-- name: MarkEventsDispatched :exec
UPDATE outbox_event
SET dispatched_at = $1
WHERE id = ANY($2::uuid[])
`

type MarkEventsDispatchedParams struct {
	DispatchedAt pgtype.Timestamptz
	Ids          []pgtype.UUID
}

// Recorded in the same transaction as the delivery itself. A mark that committed without its
// delivery would lose the event silently, which is the one failure an outbox exists to rule out.
func (q *Queries) MarkEventsDispatched(ctx context.Context, arg MarkEventsDispatchedParams) error {
	_, err := q.db.Exec(ctx, markEventsDispatched, arg.DispatchedAt, arg.Ids)
	return err
}
