// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendOutboxEvent = `-- name: AppendOutboxEvent :exec

INSERT INTO outbox_event (
  id, tenant_id, event_type, subject, payload,
  actor_type, actor_id, correlation_id, causation_id, causation_depth, occurred_at
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10
)
`

type AppendOutboxEventParams struct {
	ID             pgtype.UUID
	EventType      string
	Subject        *string
	Payload        []byte
	ActorType      string
	ActorID        pgtype.UUID
	CorrelationID  pgtype.UUID
	CausationID    pgtype.UUID
	CausationDepth int32
	OccurredAt     pgtype.Timestamptz
}

// The transactional outbox (ADR-0007): the event is written in the same transaction as the change
// it describes, and the dispatcher delivers it afterwards. Nothing here marks an event as
// delivered - that is the dispatcher's half, and it arrives with A-08.
func (q *Queries) AppendOutboxEvent(ctx context.Context, arg AppendOutboxEventParams) error {
	_, err := q.db.Exec(ctx, appendOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.Subject,
		arg.Payload,
		arg.ActorType,
		arg.ActorID,
		arg.CorrelationID,
		arg.CausationID,
		arg.CausationDepth,
		arg.OccurredAt,
	)
	return err
}
