// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Password.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendPasswordHistory = `-- name: AppendPasswordHistory :exec
INSERT INTO account_password_history (id, tenant_id, account_id, password_hash, set_at)
VALUES (
  $1, current_tenant_id(), $2,
  $3, $4
)
`

type AppendPasswordHistoryParams struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	PasswordHash string
	SetAt        pgtype.Timestamptz
}

func (q *Queries) AppendPasswordHistory(ctx context.Context, arg AppendPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, appendPasswordHistory,
		arg.ID,
		arg.AccountID,
		arg.PasswordHash,
		arg.SetAt,
	)
	return err
}

const findAccountByEmailForPassword = `-- name: FindAccountByEmailForPassword :one
SELECT
  a.id, a.tenant_id, a.kind, a.email, a.display_name, a.status,
  a.locale, a.time_zone, a.week_start,
  a.password_hash, a.password_set_at
FROM account a
WHERE lower(a.email) = lower($1) AND a.deleted_at IS NULL
`

type FindAccountByEmailForPasswordRow struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Kind          AccountKind
	Email         *string
	DisplayName   string
	Status        AccountStatus
	Locale        *string
	TimeZone      *string
	WeekStart     *string
	PasswordHash  *string
	PasswordSetAt pgtype.Timestamptz
}

// The same, by address, for the reset that must answer identically whether or not it found one.
func (q *Queries) FindAccountByEmailForPassword(ctx context.Context, email string) (FindAccountByEmailForPasswordRow, error) {
	row := q.db.QueryRow(ctx, findAccountByEmailForPassword, email)
	var i FindAccountByEmailForPasswordRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Locale,
		&i.TimeZone,
		&i.WeekStart,
		&i.PasswordHash,
		&i.PasswordSetAt,
	)
	return i, err
}

const findAccountForPassword = `-- name: FindAccountForPassword :one
SELECT
  a.id, a.tenant_id, a.kind, a.email, a.display_name, a.status,
  a.locale, a.time_zone, a.week_start,
  a.password_hash, a.password_set_at
FROM account a
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type FindAccountForPasswordRow struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	Kind          AccountKind
	Email         *string
	DisplayName   string
	Status        AccountStatus
	Locale        *string
	TimeZone      *string
	WeekStart     *string
	PasswordHash  *string
	PasswordSetAt pgtype.Timestamptz
}

// What setting or judging a password needs of the account (ADR-0068 §5).
func (q *Queries) FindAccountForPassword(ctx context.Context, id pgtype.UUID) (FindAccountForPasswordRow, error) {
	row := q.db.QueryRow(ctx, findAccountForPassword, id)
	var i FindAccountForPasswordRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.Locale,
		&i.TimeZone,
		&i.WeekStart,
		&i.PasswordHash,
		&i.PasswordSetAt,
	)
	return i, err
}

const recentPasswordHashes = `-- name: RecentPasswordHashes :many
SELECT password_hash
FROM account_password_history
WHERE account_id = $1
ORDER BY set_at DESC
LIMIT $2
`

type RecentPasswordHashesParams struct {
	AccountID pgtype.UUID
	Depth     int32
}

// The newest few, newest first. The depth is the policy's, passed in.
func (q *Queries) RecentPasswordHashes(ctx context.Context, arg RecentPasswordHashesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, recentPasswordHashes, arg.AccountID, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var password_hash string
		if err := rows.Scan(&password_hash); err != nil {
			return nil, err
		}
		items = append(items, password_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountPassword = `-- name: SetAccountPassword :execrows
UPDATE account
   SET password_hash = $1,
       password_set_at = $2,
       updated_at = $2,
       version = version + 1
 WHERE id = $3 AND deleted_at IS NULL
`

type SetAccountPasswordParams struct {
	PasswordHash *string
	At           pgtype.Timestamptz
	AccountID    pgtype.UUID
}

// The hash and the moment in one statement, so no reader sees one without the other.
func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountPassword, arg.PasswordHash, arg.At, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trimPasswordHistory = `-- name: TrimPasswordHistory :exec
DELETE FROM account_password_history h
WHERE h.account_id = $1
  AND h.id NOT IN (
    SELECT k.id FROM account_password_history k
    WHERE k.account_id = $1
    ORDER BY k.set_at DESC
    LIMIT $2
  )
`

type TrimPasswordHistoryParams struct {
	AccountID pgtype.UUID
	Keep      int32
}

// Everything past the newest `keep`, dropped in the same transaction as the append - so the table
// cannot grow past the policy even after the policy is lowered.
func (q *Queries) TrimPasswordHistory(ctx context.Context, arg TrimPasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, trimPasswordHistory, arg.AccountID, arg.Keep)
	return err
}
