// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Privacy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const auditPseudonyms = `-- name: AuditPseudonyms :many
SELECT actor_id, pseudonym
FROM audit_pseudonym
WHERE tenant_id = current_tenant_id() AND actor_id = ANY($1::uuid[])
`

type AuditPseudonymsRow struct {
	ActorID   pgtype.UUID
	Pseudonym string
}

// The pseudonyms of a set of actors, for a page of the trail that has just been read.
//
// Asked for the actors on the page rather than read whole: a workspace that has answered a hundred
// erasures has a hundred rows here, and a page has at most a few dozen distinct actors.
func (q *Queries) AuditPseudonyms(ctx context.Context, actorIds []pgtype.UUID) ([]AuditPseudonymsRow, error) {
	rows, err := q.db.Query(ctx, auditPseudonyms, actorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditPseudonymsRow{}
	for rows.Next() {
		var i AuditPseudonymsRow
		if err := rows.Scan(&i.ActorID, &i.Pseudonym); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDataSubjectRequest = `-- name: FindDataSubjectRequest :one
SELECT id, subject_account_id, subject_email, kind, status, scope, erasure_mode,
       received_at, due_at, completed_at, handled_by, rejection_reason,
       target_id, result_archive, notes
FROM data_subject_request
WHERE id = $1 AND tenant_id = current_tenant_id()
`

type FindDataSubjectRequestRow struct {
	ID               pgtype.UUID
	SubjectAccountID pgtype.UUID
	SubjectEmail     *string
	Kind             string
	Status           string
	Scope            string
	ErasureMode      *string
	ReceivedAt       pgtype.Timestamptz
	DueAt            pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	HandledBy        pgtype.UUID
	RejectionReason  *string
	TargetID         pgtype.UUID
	ResultArchive    *string
	Notes            *string
}

func (q *Queries) FindDataSubjectRequest(ctx context.Context, id pgtype.UUID) (FindDataSubjectRequestRow, error) {
	row := q.db.QueryRow(ctx, findDataSubjectRequest, id)
	var i FindDataSubjectRequestRow
	err := row.Scan(
		&i.ID,
		&i.SubjectAccountID,
		&i.SubjectEmail,
		&i.Kind,
		&i.Status,
		&i.Scope,
		&i.ErasureMode,
		&i.ReceivedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.HandledBy,
		&i.RejectionReason,
		&i.TargetID,
		&i.ResultArchive,
		&i.Notes,
	)
	return i, err
}

const insertAuditPseudonym = `-- name: InsertAuditPseudonym :exec
INSERT INTO audit_pseudonym (tenant_id, actor_id, pseudonym, reason, created_at)
VALUES (current_tenant_id(), $1, $2, $3, $4)
ON CONFLICT (tenant_id, actor_id) DO NOTHING
`

type InsertAuditPseudonymParams struct {
	ActorID   pgtype.UUID
	Pseudonym string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

// The substitution the audit trail reads at the boundary (audit.md §6). Idempotent on the actor:
// an erasure that is retried records the same pseudonym rather than a second one.
func (q *Queries) InsertAuditPseudonym(ctx context.Context, arg InsertAuditPseudonymParams) error {
	_, err := q.db.Exec(ctx, insertAuditPseudonym,
		arg.ActorID,
		arg.Pseudonym,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const insertConsentRecord = `-- name: InsertConsentRecord :exec
INSERT INTO consent_record (id, tenant_id, account_id, purpose, granted, granted_at, revoked_at, source)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6, $7
)
`

type InsertConsentRecordParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	Granted   bool
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Source    *string
}

// A consent record is never updated in place: what an operator has to be able to show is not "is
// this allowed now" but "was it allowed then", so a change is a new row and the old one keeps the
// period it covered.
func (q *Queries) InsertConsentRecord(ctx context.Context, arg InsertConsentRecordParams) error {
	_, err := q.db.Exec(ctx, insertConsentRecord,
		arg.ID,
		arg.AccountID,
		arg.Purpose,
		arg.Granted,
		arg.GrantedAt,
		arg.RevokedAt,
		arg.Source,
	)
	return err
}

const insertDataSubjectRequest = `-- name: InsertDataSubjectRequest :exec

INSERT INTO data_subject_request (
  id, tenant_id, subject_account_id, subject_email, kind, status, scope,
  erasure_mode, received_at, due_at, handled_by, target_id, notes
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11, $12
)
`

type InsertDataSubjectRequestParams struct {
	ID               pgtype.UUID
	SubjectAccountID pgtype.UUID
	SubjectEmail     *string
	Kind             string
	Status           string
	Scope            string
	ErasureMode      *string
	ReceivedAt       pgtype.Timestamptz
	DueAt            pgtype.Timestamptz
	HandledBy        pgtype.UUID
	TargetID         pgtype.UUID
	Notes            *string
}

// Data subject rights (E-10, data-protection.md §4). The tables have stood since `0001_init`;
// these are the first statements over them.
//
// The tenant is never a parameter. It comes from the transaction's own context through
// current_tenant_id(), which is the value row level security compares against (ADR-0010) - and
// that holds for the installation-wide case as well: it opens one transaction per tenant rather
// than one query across tenants.
func (q *Queries) InsertDataSubjectRequest(ctx context.Context, arg InsertDataSubjectRequestParams) error {
	_, err := q.db.Exec(ctx, insertDataSubjectRequest,
		arg.ID,
		arg.SubjectAccountID,
		arg.SubjectEmail,
		arg.Kind,
		arg.Status,
		arg.Scope,
		arg.ErasureMode,
		arg.ReceivedAt,
		arg.DueAt,
		arg.HandledBy,
		arg.TargetID,
		arg.Notes,
	)
	return err
}

const latestConsent = `-- name: LatestConsent :one
SELECT id, account_id, purpose, granted, granted_at, revoked_at, source
FROM consent_record
WHERE tenant_id = current_tenant_id()
  AND purpose = $1
  AND account_id IS NOT DISTINCT FROM $2
ORDER BY granted_at DESC
LIMIT 1
`

type LatestConsentParams struct {
	Purpose   string
	AccountID pgtype.UUID
}

type LatestConsentRow struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Purpose   string
	Granted   bool
	GrantedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Source    *string
}

func (q *Queries) LatestConsent(ctx context.Context, arg LatestConsentParams) (LatestConsentRow, error) {
	row := q.db.QueryRow(ctx, latestConsent, arg.Purpose, arg.AccountID)
	var i LatestConsentRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Purpose,
		&i.Granted,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.Source,
	)
	return i, err
}

const listDataSubjectRequests = `-- name: ListDataSubjectRequests :many
SELECT id, subject_account_id, subject_email, kind, status, scope, erasure_mode,
       received_at, due_at, completed_at, handled_by, rejection_reason,
       target_id, result_archive, notes
FROM data_subject_request
WHERE tenant_id = current_tenant_id()
  AND ($1::boolean OR status IN ('RECEIVED','IN_PROGRESS'))
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR kind = $3::text)
  AND ($4::timestamptz IS NULL OR due_at < $4::timestamptz)
  AND (
    $5::timestamptz IS NULL
    OR (due_at, id) > ($5::timestamptz, $6::uuid)
  )
ORDER BY due_at ASC, id ASC
LIMIT $7
`

type ListDataSubjectRequestsParams struct {
	IncludeClosed bool
	Status        *string
	Kind          *string
	DueBefore     pgtype.Timestamptz
	CursorDueAt   pgtype.Timestamptz
	CursorID      pgtype.UUID
	PageSize      int32
}

type ListDataSubjectRequestsRow struct {
	ID               pgtype.UUID
	SubjectAccountID pgtype.UUID
	SubjectEmail     *string
	Kind             string
	Status           string
	Scope            string
	ErasureMode      *string
	ReceivedAt       pgtype.Timestamptz
	DueAt            pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	HandledBy        pgtype.UUID
	RejectionReason  *string
	TargetID         pgtype.UUID
	ResultArchive    *string
	Notes            *string
}

// One page of the cases, the soonest deadline first.
//
// By deadline rather than by receipt, because that is the order the work has to be done in: a case
// recorded yesterday with a week to run is more urgent than one recorded last month with three.
// The open ones alone unless the caller asks for the closed ones too - "what do we owe" is what
// this list answers.
//
// Served by dsr_open_idx (tenant_id, status, due_at) for the open half, which is the half that is
// read.
func (q *Queries) ListDataSubjectRequests(ctx context.Context, arg ListDataSubjectRequestsParams) ([]ListDataSubjectRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDataSubjectRequests,
		arg.IncludeClosed,
		arg.Status,
		arg.Kind,
		arg.DueBefore,
		arg.CursorDueAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDataSubjectRequestsRow{}
	for rows.Next() {
		var i ListDataSubjectRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectAccountID,
			&i.SubjectEmail,
			&i.Kind,
			&i.Status,
			&i.Scope,
			&i.ErasureMode,
			&i.ReceivedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.HandledBy,
			&i.RejectionReason,
			&i.TargetID,
			&i.ResultArchive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const overdueRequestCount = `-- name: OverdueRequestCount :one
SELECT
  count(*) FILTER (WHERE due_at < $1::timestamptz) AS overdue,
  count(*) AS open_cases,
  min(due_at) AS next_due_at
FROM data_subject_request
WHERE tenant_id = current_tenant_id()
  AND status IN ('RECEIVED','IN_PROGRESS')
`

type OverdueRequestCountRow struct {
	Overdue   int64
	OpenCases int64
	NextDueAt interface{}
}

// How many open cases are past their deadline, and how soon the next one falls due.
//
// The reading behind alert A-19 (data-protection.md §4): "without deadline monitoring, the right
// gets violated in practice even though the feature exists". Two numbers rather than a list,
// because a gauge is what an alert evaluates and the list is a page somebody reads.
func (q *Queries) OverdueRequestCount(ctx context.Context, now pgtype.Timestamptz) (OverdueRequestCountRow, error) {
	row := q.db.QueryRow(ctx, overdueRequestCount, now)
	var i OverdueRequestCountRow
	err := row.Scan(&i.Overdue, &i.OpenCases, &i.NextDueAt)
	return i, err
}

const revokeConsent = `-- name: RevokeConsent :execrows
UPDATE consent_record SET revoked_at = $1
WHERE tenant_id = current_tenant_id()
  AND purpose = $2
  AND account_id IS NOT DISTINCT FROM $3
  AND granted
  AND revoked_at IS NULL
`

type RevokeConsentParams struct {
	RevokedAt pgtype.Timestamptz
	Purpose   string
	AccountID pgtype.UUID
}

// Ends every standing consent of one account for one purpose.
//
// The moment is only written where there is none: when the processing stopped is the fact being
// kept, and a second withdrawal must not move it.
func (q *Queries) RevokeConsent(ctx context.Context, arg RevokeConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeConsent, arg.RevokedAt, arg.Purpose, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountStatus = `-- name: SetAccountStatus :execrows
UPDATE account SET status = $1, updated_at = $2, version = version + 1
WHERE id = $3 AND tenant_id = current_tenant_id() AND deleted_at IS NULL
`

type SetAccountStatusParams struct {
	Status    AccountStatus
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

// One column, for the reason UpdateAccountPreferences writes three: the status decides whether an
// account may act at all, and a statement that could write anything else while setting it is one
// that can change what somebody may do by accident.
func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subjectTenants = `-- name: SubjectTenants :many
SELECT subject_tenants AS tenant_id FROM subject_tenants($1::text)
`

// The workspaces of this installation in which one person is a member.
//
// The one cross-tenant question in the system (data-protection.md §4), answered by a function that
// returns tenant identifiers and nothing else - never a name, never a row of anybody's data. What
// follows is one ordinary transaction per tenant, under that tenant's own context
// (db/migrations/0044_privacy_requests.sql).
func (q *Queries) SubjectTenants(ctx context.Context, subjectEmail string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, subjectTenants, subjectEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataSubjectRequest = `-- name: UpdateDataSubjectRequest :execrows
UPDATE data_subject_request SET
  status           = $1,
  erasure_mode     = $2,
  handled_by       = $3,
  rejection_reason = $4,
  completed_at     = $5,
  target_id        = $6,
  result_archive   = $7,
  subject_account_id = $8,
  notes            = $9
WHERE id = $10 AND tenant_id = current_tenant_id()
`

type UpdateDataSubjectRequestParams struct {
	Status           string
	ErasureMode      *string
	HandledBy        pgtype.UUID
	RejectionReason  *string
	CompletedAt      pgtype.Timestamptz
	TargetID         pgtype.UUID
	ResultArchive    *string
	SubjectAccountID pgtype.UUID
	Notes            *string
	ID               pgtype.UUID
}

// The whole case as the domain decided it, written back in one statement.
//
// Every column the state machine can move is here and no others: a case carries a person's request
// and the answer to it, and an update that could write `received_at` or the subject would be one
// that can rewrite what somebody asked for.
func (q *Queries) UpdateDataSubjectRequest(ctx context.Context, arg UpdateDataSubjectRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDataSubjectRequest,
		arg.Status,
		arg.ErasureMode,
		arg.HandledBy,
		arg.RejectionReason,
		arg.CompletedAt,
		arg.TargetID,
		arg.ResultArchive,
		arg.SubjectAccountID,
		arg.Notes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
