// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Suggestion.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpiredSuggestions = `-- name: CountExpiredSuggestions :one
SELECT count(*)::bigint FROM (
  SELECT 1 FROM ai_suggestion WHERE created_at < $1 LIMIT $2
) AS due
`

type CountExpiredSuggestionsParams struct {
	Cutoff  pgtype.Timestamptz
	Ceiling int32
}

// Counted no higher than the ceiling, the notification history's shape: the number is for a run
// log and an operator, and counting a million rows to write "a lot" into a log is a scan nobody
// asked for.
func (q *Queries) CountExpiredSuggestions(ctx context.Context, arg CountExpiredSuggestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiredSuggestions, arg.Cutoff, arg.Ceiling)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const decideSuggestion = `-- name: DecideSuggestion :execrows
UPDATE ai_suggestion
SET status = $1, decided_at = $2,
    decided_by = $3, version = version + 1
WHERE id = $4 AND version = $5
`

type DecideSuggestionParams struct {
	Status          string
	DecidedAt       pgtype.Timestamptz
	DecidedBy       pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Guarded on the version it was read at: two people answering one proposal is a conflict, and the
// second must be told rather than silently overwriting the first.
func (q *Queries) DecideSuggestion(ctx context.Context, arg DecideSuggestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideSuggestion,
		arg.Status,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSuggestions = `-- name: DeleteExpiredSuggestions :execrows
DELETE FROM ai_suggestion
WHERE id IN (
  SELECT id FROM ai_suggestion AS expired
  WHERE expired.created_at < $1
  ORDER BY expired.created_at
  LIMIT $2
)
`

type DeleteExpiredSuggestionsParams struct {
	Cutoff pgtype.Timestamptz
	Batch  int32
}

// Oldest first and in batches, so a long-neglected workspace catches up over several passes
// instead of holding one transaction over everything it owes.
func (q *Queries) DeleteExpiredSuggestions(ctx context.Context, arg DeleteExpiredSuggestionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSuggestions, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSuggestion = `-- name: FindSuggestion :one
SELECT id, target_type, target_id, kind, status, payload, source, model, prompt_id,
       prompt_version, produced_at, input_digest, created_at, decided_at, decided_by, version
FROM ai_suggestion
WHERE id = $1
`

type FindSuggestionRow struct {
	ID            pgtype.UUID
	TargetType    string
	TargetID      pgtype.UUID
	Kind          string
	Status        string
	Payload       []byte
	Source        string
	Model         string
	PromptID      string
	PromptVersion string
	ProducedAt    pgtype.Timestamptz
	InputDigest   []byte
	CreatedAt     pgtype.Timestamptz
	DecidedAt     pgtype.Timestamptz
	DecidedBy     pgtype.UUID
	Version       int32
}

func (q *Queries) FindSuggestion(ctx context.Context, id pgtype.UUID) (FindSuggestionRow, error) {
	row := q.db.QueryRow(ctx, findSuggestion, id)
	var i FindSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Kind,
		&i.Status,
		&i.Payload,
		&i.Source,
		&i.Model,
		&i.PromptID,
		&i.PromptVersion,
		&i.ProducedAt,
		&i.InputDigest,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Version,
	)
	return i, err
}

const listSuggestions = `-- name: ListSuggestions :many
SELECT id, target_type, target_id, kind, status, payload, source, model, prompt_id,
       prompt_version, produced_at, input_digest, created_at, decided_at, decided_by, version
FROM ai_suggestion
WHERE target_type = $1
  AND target_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND (
    $4::timestamptz IS NULL
    OR (created_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListSuggestionsParams struct {
	TargetType      string
	TargetID        pgtype.UUID
	Status          *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListSuggestionsRow struct {
	ID            pgtype.UUID
	TargetType    string
	TargetID      pgtype.UUID
	Kind          string
	Status        string
	Payload       []byte
	Source        string
	Model         string
	PromptID      string
	PromptVersion string
	ProducedAt    pgtype.Timestamptz
	InputDigest   []byte
	CreatedAt     pgtype.Timestamptz
	DecidedAt     pgtype.Timestamptz
	DecidedBy     pgtype.UUID
	Version       int32
}

// Keyset over (created_at, id) descending, the ordering every list in this schema uses: a page
// boundary that repeats a row or skips one is what an offset does when a suggestion is recorded
// while somebody is reading.
func (q *Queries) ListSuggestions(ctx context.Context, arg ListSuggestionsParams) ([]ListSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listSuggestions,
		arg.TargetType,
		arg.TargetID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuggestionsRow{}
	for rows.Next() {
		var i ListSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Kind,
			&i.Status,
			&i.Payload,
			&i.Source,
			&i.Model,
			&i.PromptID,
			&i.PromptVersion,
			&i.ProducedAt,
			&i.InputDigest,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSuggestion = `-- name: RecordSuggestion :exec

INSERT INTO ai_suggestion
  (id, tenant_id, target_type, target_id, kind, status, payload,
   source, model, prompt_id, prompt_version, produced_at, input_digest, created_at)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, 'PROPOSED', $5, $6, $7,
  $8, $9, $10,
  $11, $12
)
`

type RecordSuggestionParams struct {
	ID            pgtype.UUID
	TargetType    string
	TargetID      pgtype.UUID
	Kind          string
	Payload       []byte
	Source        string
	Model         string
	PromptID      string
	PromptVersion string
	ProducedAt    pgtype.Timestamptz
	InputDigest   []byte
	CreatedAt     pgtype.Timestamptz
}

// What AI proposed, and did not do (J-05).
//
// Every statement runs inside the transaction wrapper that sets `app.tenant_id`, so the policy
// underneath answers "which workspace" - `current_tenant_id()` is written on insert rather than
// passed in, the way every tenant-scoped insert in this schema is.
func (q *Queries) RecordSuggestion(ctx context.Context, arg RecordSuggestionParams) error {
	_, err := q.db.Exec(ctx, recordSuggestion,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.Kind,
		arg.Payload,
		arg.Source,
		arg.Model,
		arg.PromptID,
		arg.PromptVersion,
		arg.ProducedAt,
		arg.InputDigest,
		arg.CreatedAt,
	)
	return err
}
