// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Template.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletedTemplates = `-- name: DeletedTemplates :many
SELECT t.id, t.scope_type, t.scope_id, c.parent_id AS hub_id
FROM template t
LEFT JOIN container c ON c.tenant_id = t.tenant_id AND c.id = t.scope_id
WHERE t.tenant_id = current_tenant_id() AND t.deleted_at IS NOT NULL
  AND t.id > $1::uuid
ORDER BY t.id
LIMIT $2
`

type DeletedTemplatesParams struct {
	After pgtype.UUID
	Batch int32
}

type DeletedTemplatesRow struct {
	ID        pgtype.UUID
	ScopeType string
	ScopeID   pgtype.UUID
	HubID     pgtype.UUID
}

// The templates deleted under a legal hold, with what a hold is judged against: the scope and, for
// a collection, the hub above it. One page in identifier order; the retention pass walks every
// page, because a template still held stays in the set.
func (q *Queries) DeletedTemplates(ctx context.Context, arg DeletedTemplatesParams) ([]DeletedTemplatesRow, error) {
	rows, err := q.db.Query(ctx, deletedTemplates, arg.After, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeletedTemplatesRow{}
	for rows.Next() {
		var i DeletedTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeType,
			&i.ScopeID,
			&i.HubID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTemplate = `-- name: FindTemplate :one
SELECT id, tenant_id, scope_type, scope_id, name, description, root_type, nodes,
       created_at, updated_at, deleted_at, version
FROM template
WHERE id = $1
`

type FindTemplateRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
	Name        string
	Description *string
	RootType    ItemType
	Nodes       []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
}

// A deleted template is returned rather than filtered out: whether it may still be changed is the
// domain's question, and a query that hid one would turn "it was deleted" into "it never existed" -
// which is not what a client holding its identifier is asking.
func (q *Queries) FindTemplate(ctx context.Context, id pgtype.UUID) (FindTemplateRow, error) {
	row := q.db.QueryRow(ctx, findTemplate, id)
	var i FindTemplateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Name,
		&i.Description,
		&i.RootType,
		&i.Nodes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :exec

INSERT INTO template (
  id, tenant_id, scope_type, scope_id, name, description, root_type, nodes, created_at, version
) VALUES (
  $1, current_tenant_id(), $2, $3,
  normalize($4::text, NFC), $5,
  $6::item_type, $7::jsonb, $8, 1
)
`

type InsertTemplateParams struct {
	ID          pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
	Name        string
	Description *string
	RootType    ItemType
	Nodes       []byte
	CreatedAt   pgtype.Timestamptz
}

// The templates (domain-model.md §3.5).
//
// The tenant is never a parameter here: it comes from the transaction's own context through
// current_tenant_id(), which is the same value row level security compares against (ADR-0010).
//
// The tree is stored as the document it is. Nothing here interprets it: which type may sit under
// which is the hierarchy's answer and is decided before a row is written, and what a relative date
// means is decided when the template is stamped out.
func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) error {
	_, err := q.db.Exec(ctx, insertTemplate,
		arg.ID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Name,
		arg.Description,
		arg.RootType,
		arg.Nodes,
		arg.CreatedAt,
	)
	return err
}

const listTemplatesInScopes = `-- name: ListTemplatesInScopes :many
SELECT id, tenant_id, scope_type, scope_id, name, description, root_type, nodes,
       created_at, updated_at, deleted_at, version
FROM template
WHERE deleted_at IS NULL
  AND (
    scope_type = 'TENANT'
    OR scope_id = ANY ($1::uuid[])
  )
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTemplatesInScopesParams struct {
	ScopeIds        []pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListTemplatesInScopesRow struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	ScopeType   string
	ScopeID     pgtype.UUID
	Name        string
	Description *string
	RootType    ItemType
	Nodes       []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
}

// The templates a person picking one in a container can choose from: the ones defined on that
// container's path, plus the workspace-wide ones. The caller passes the identifiers the path names
// (the collection, its hub) and TENANT-scoped rows match by scope type alone, having no identifier
// to match - the shape the saved views' reachable list already has.
//
// Newest first: a template somebody has just written is the one they are looking for. The keyset
// is (created_at, id) for the reason every list in this schema takes the pair.
func (q *Queries) ListTemplatesInScopes(ctx context.Context, arg ListTemplatesInScopesParams) ([]ListTemplatesInScopesRow, error) {
	rows, err := q.db.Query(ctx, listTemplatesInScopes,
		arg.ScopeIds,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesInScopesRow{}
	for rows.Next() {
		var i ListTemplatesInScopesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Name,
			&i.Description,
			&i.RootType,
			&i.Nodes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDeletedTemplates = `-- name: RemoveDeletedTemplates :many
DELETE FROM template
WHERE tenant_id = current_tenant_id() AND deleted_at IS NOT NULL
  AND id = ANY($1::uuid[])
RETURNING id
`

// The held templates no hold covers any more, removed. The identifiers come back so that the
// journal names exactly the rows that went. A living template is never matched.
func (q *Queries) RemoveDeletedTemplates(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, removeDeletedTemplates, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTemplate = `-- name: RemoveTemplate :execrows
DELETE FROM template
WHERE id = $1::uuid
  AND version = $2
  AND deleted_at IS NULL
`

type RemoveTemplateParams struct {
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The deletion where no legal hold covers the template: the row goes at once (data-retention.md
// §4). Nothing shows a deleted template's name and nothing references one, so there is no
// tombstone row to keep; the journal and the tombstone the caller writes are the record. Under the
// same optimistic lock as the edit, and never on a row already deleted - that one is the hold's.
func (q *Queries) RemoveTemplate(ctx context.Context, arg RemoveTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTemplate, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTemplateDeleted = `-- name: SetTemplateDeleted :execrows
UPDATE template SET
  deleted_at = $1,
  version    = version + 1
WHERE id = $2::uuid
  AND version = $3
  AND deleted_at IS NULL
`

type SetTemplateDeletedParams struct {
	DeletedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The soft delete. The trees the template has stamped out are ordinary entries and are not
// touched; what goes is the ability to stamp out more - and the name, which the partial unique
// index frees for a template defined afterwards.
func (q *Queries) SetTemplateDeleted(ctx context.Context, arg SetTemplateDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTemplateDeleted, arg.DeletedAt, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTemplate = `-- name: UpdateTemplate :execrows
UPDATE template SET
  name        = normalize($1::text, NFC),
  description = $2,
  nodes       = $3::jsonb,
  updated_at  = $4,
  version     = version + 1
WHERE id = $5::uuid
  AND version = $6
  AND deleted_at IS NULL
`

type UpdateTemplateParams struct {
	Name            string
	Description     *string
	Nodes           []byte
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The whole document, under the same optimistic lock every other row takes (api-guidelines.md §5).
// The scope and the root type are not here on purpose: a template that changed scope would move
// out from under the people who could use it, and one whose root type changed would produce a
// different kind of thing under the same name.
func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTemplate,
		arg.Name,
		arg.Description,
		arg.Nodes,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
