// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Tenant.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTenantHost = `-- name: InsertTenantHost :exec
INSERT INTO tenant_host
  (tenant_id, host, state, verification, verified_at, is_canonical, created_at)
VALUES (
  current_tenant_id(), $1, $2, $3,
  $4, $5, $6
)
`

type InsertTenantHostParams struct {
	Host         string
	State        string
	Verification string
	VerifiedAt   pgtype.Timestamptz
	IsCanonical  bool
	CreatedAt    pgtype.Timestamptz
}

// A host a workspace answers at. `current_tenant_id()` rather than an argument, as every
// tenant-scoped insert here: the workspace is the transaction's, not the caller's to name.
func (q *Queries) InsertTenantHost(ctx context.Context, arg InsertTenantHostParams) error {
	_, err := q.db.Exec(ctx, insertTenantHost,
		arg.Host,
		arg.State,
		arg.Verification,
		arg.VerifiedAt,
		arg.IsCanonical,
		arg.CreatedAt,
	)
	return err
}

const listTenantHosts = `-- name: ListTenantHosts :many
SELECT host, state, verification, verified_at, is_canonical, created_at
FROM tenant_host
ORDER BY is_canonical DESC, host
`

type ListTenantHostsRow struct {
	Host         string
	State        string
	Verification string
	VerifiedAt   pgtype.Timestamptz
	IsCanonical  bool
	CreatedAt    pgtype.Timestamptz
}

// The hosts of this workspace, canonical first - what a reader needs to know which one a mail will
// name. Nothing resolves a request through this yet (migration 0104).
func (q *Queries) ListTenantHosts(ctx context.Context) ([]ListTenantHostsRow, error) {
	rows, err := q.db.Query(ctx, listTenantHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantHostsRow{}
	for rows.Next() {
		var i ListTenantHostsRow
		if err := rows.Scan(
			&i.Host,
			&i.State,
			&i.Verification,
			&i.VerifiedAt,
			&i.IsCanonical,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
