// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Webhook.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM webhook_subscription WHERE id = $1
`

// The deliveries go with it, by cascade (0001_init): a delivery log for a subscription nobody can
// reach any more is a record of attempts against an address the workspace no longer knows.
func (q *Queries) DeleteWebhookSubscription(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findWebhookDelivery = `-- name: FindWebhookDelivery :one
SELECT id, subscription_id, event_id, attempt, status, response_status, error_code,
       next_attempt_at, created_at
FROM webhook_delivery
WHERE id = $1
`

type FindWebhookDeliveryRow struct {
	ID             pgtype.UUID
	SubscriptionID pgtype.UUID
	EventID        pgtype.UUID
	Attempt        int32
	Status         string
	ResponseStatus *int32
	ErrorCode      *string
	NextAttemptAt  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) FindWebhookDelivery(ctx context.Context, id pgtype.UUID) (FindWebhookDeliveryRow, error) {
	row := q.db.QueryRow(ctx, findWebhookDelivery, id)
	var i FindWebhookDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventID,
		&i.Attempt,
		&i.Status,
		&i.ResponseStatus,
		&i.ErrorCode,
		&i.NextAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const findWebhookSubscription = `-- name: FindWebhookSubscription :one
SELECT id, target_url, event_types, filter_expr, secret_enc, secret_key_id,
       previous_secret_enc, previous_secret_key_id, previous_secret_until,
       state, failure_count, last_error, disabled_at, created_by, created_at, version
FROM webhook_subscription
WHERE id = $1
`

type FindWebhookSubscriptionRow struct {
	ID                  pgtype.UUID
	TargetUrl           string
	EventTypes          []string
	FilterExpr          *string
	SecretEnc           []byte
	SecretKeyID         *string
	PreviousSecretEnc   []byte
	PreviousSecretKeyID *string
	PreviousSecretUntil pgtype.Timestamptz
	State               string
	FailureCount        int32
	LastError           *string
	DisabledAt          pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	Version             int32
}

func (q *Queries) FindWebhookSubscription(ctx context.Context, id pgtype.UUID) (FindWebhookSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, findWebhookSubscription, id)
	var i FindWebhookSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.TargetUrl,
		&i.EventTypes,
		&i.FilterExpr,
		&i.SecretEnc,
		&i.SecretKeyID,
		&i.PreviousSecretEnc,
		&i.PreviousSecretKeyID,
		&i.PreviousSecretUntil,
		&i.State,
		&i.FailureCount,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec

INSERT INTO webhook_delivery (
  id, tenant_id, subscription_id, event_id, attempt, status, next_attempt_at, created_at
)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6, $7
)
`

type InsertWebhookDeliveryParams struct {
	ID             pgtype.UUID
	SubscriptionID pgtype.UUID
	EventID        pgtype.UUID
	Attempt        int32
	Status         string
	NextAttemptAt  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

// ============================== Deliveries ==============================
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.EventID,
		arg.Attempt,
		arg.Status,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const insertWebhookSubscription = `-- name: InsertWebhookSubscription :exec

INSERT INTO webhook_subscription (
  id, tenant_id, target_url, event_types, filter_expr,
  secret_enc, secret_key_id, state, created_by, created_at, version
)
VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  $7, $8, $9, 1
)
`

type InsertWebhookSubscriptionParams struct {
	ID          pgtype.UUID
	TargetUrl   string
	EventTypes  []string
	FilterExpr  *string
	SecretEnc   []byte
	SecretKeyID *string
	State       string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

// Webhook subscriptions and their deliveries (G-03, automation.md §3.1).
//
// The tenant is never a parameter: row level security bounds every statement to the tenant of the
// running transaction, which is what makes another workspace's subscription invisible rather than
// forbidden (ADR-0010, multi-tenancy.md §2).
//
// The sealed secrets travel as a ciphertext and a key identifier together. A sealed value is a
// pair - the envelope opens under whichever master key sealed it - and an installation that has
// rotated its keyring holds several (E-02).
func (q *Queries) InsertWebhookSubscription(ctx context.Context, arg InsertWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertWebhookSubscription,
		arg.ID,
		arg.TargetUrl,
		arg.EventTypes,
		arg.FilterExpr,
		arg.SecretEnc,
		arg.SecretKeyID,
		arg.State,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, target_url, event_types, filter_expr, secret_enc, secret_key_id,
       previous_secret_enc, previous_secret_key_id, previous_secret_until,
       state, failure_count, last_error, disabled_at, created_by, created_at, version
FROM webhook_subscription
ORDER BY id DESC
`

type ListWebhookSubscriptionsRow struct {
	ID                  pgtype.UUID
	TargetUrl           string
	EventTypes          []string
	FilterExpr          *string
	SecretEnc           []byte
	SecretKeyID         *string
	PreviousSecretEnc   []byte
	PreviousSecretKeyID *string
	PreviousSecretUntil pgtype.Timestamptz
	State               string
	FailureCount        int32
	LastError           *string
	DisabledAt          pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	Version             int32
}

// Newest first by identifier: UUIDv7 is time-ordered, so the primary key is the creation order.
// Not paged - a workspace has a handful of integrations, and a cursor over a handful is machinery
// nobody reads.
func (q *Queries) ListWebhookSubscriptions(ctx context.Context) ([]ListWebhookSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookSubscriptionsRow{}
	for rows.Next() {
		var i ListWebhookSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetUrl,
			&i.EventTypes,
			&i.FilterExpr,
			&i.SecretEnc,
			&i.SecretKeyID,
			&i.PreviousSecretEnc,
			&i.PreviousSecretKeyID,
			&i.PreviousSecretUntil,
			&i.State,
			&i.FailureCount,
			&i.LastError,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookDeliveryOutcome = `-- name: RecordWebhookDeliveryOutcome :execrows
UPDATE webhook_delivery SET
  status          = $1,
  response_status = $2,
  error_code      = $3,
  next_attempt_at = $4
WHERE id = $5
`

type RecordWebhookDeliveryOutcomeParams struct {
	Status         string
	ResponseStatus *int32
	ErrorCode      *string
	NextAttemptAt  pgtype.Timestamptz
	ID             pgtype.UUID
}

// What became of one attempt. The response status is the target's own; the error is a message code
// of ours, never the target's response body (rule 10).
func (q *Queries) RecordWebhookDeliveryOutcome(ctx context.Context, arg RecordWebhookDeliveryOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWebhookDeliveryOutcome,
		arg.Status,
		arg.ResponseStatus,
		arg.ErrorCode,
		arg.NextAttemptAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rewrapWebhookSecrets = `-- name: RewrapWebhookSecrets :execrows
UPDATE webhook_subscription SET
  secret_enc             = $1,
  secret_key_id          = $2,
  previous_secret_enc    = $3,
  previous_secret_key_id = $4
WHERE id = $5 AND version = $6
`

type RewrapWebhookSecretsParams struct {
	SecretEnc           []byte
	SecretKeyID         *string
	PreviousSecretEnc   []byte
	PreviousSecretKeyID *string
	ID                  pgtype.UUID
	ExpectedVersion     int32
}

// Both wrappings in one statement, guarded by the version and deliberately not bumping it: a
// re-seal is not an edit anybody made, and a rotation of the installation's keys must not turn
// into a conflict for the person editing their subscription at the same moment.
func (q *Queries) RewrapWebhookSecrets(ctx context.Context, arg RewrapWebhookSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewrapWebhookSecrets,
		arg.SecretEnc,
		arg.SecretKeyID,
		arg.PreviousSecretEnc,
		arg.PreviousSecretKeyID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :execrows
UPDATE webhook_subscription SET
  previous_secret_enc    = secret_enc,
  previous_secret_key_id = secret_key_id,
  previous_secret_until  = $1,
  secret_enc             = $2,
  secret_key_id          = $3,
  version                = version + 1
WHERE id = $4 AND version = $5
`

type RotateWebhookSecretParams struct {
	PreviousSecretUntil pgtype.Timestamptz
	SecretEnc           []byte
	SecretKeyID         *string
	ID                  pgtype.UUID
	ExpectedVersion     int32
}

// The rotation, as one statement: the new secret becomes current, the current one becomes previous
// with the moment it stops verifying, and the version moves. Two statements could leave a
// subscription with a new secret and no grace, which is the failure the grace exists to prevent.
func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateWebhookSecret,
		arg.PreviousSecretUntil,
		arg.SecretEnc,
		arg.SecretKeyID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionsForEventType = `-- name: SubscriptionsForEventType :many
SELECT id, target_url, event_types, filter_expr, secret_enc, secret_key_id,
       previous_secret_enc, previous_secret_key_id, previous_secret_until,
       state, failure_count, last_error, disabled_at, created_by, created_at, version
FROM webhook_subscription
WHERE state = 'ACTIVE' AND event_types @> ARRAY[$1::text]
ORDER BY id
`

type SubscriptionsForEventTypeRow struct {
	ID                  pgtype.UUID
	TargetUrl           string
	EventTypes          []string
	FilterExpr          *string
	SecretEnc           []byte
	SecretKeyID         *string
	PreviousSecretEnc   []byte
	PreviousSecretKeyID *string
	PreviousSecretUntil pgtype.Timestamptz
	State               string
	FailureCount        int32
	LastError           *string
	DisabledAt          pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	Version             int32
}

// What the dispatcher asks per event: the active subscriptions that named this type.
//
// Filtered in the database rather than in the process, because the alternative is reading every
// subscription of the tenant on every event. The array containment is what the whole shape of
// `event_types` is for.
func (q *Queries) SubscriptionsForEventType(ctx context.Context, eventType string) ([]SubscriptionsForEventTypeRow, error) {
	rows, err := q.db.Query(ctx, subscriptionsForEventType, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionsForEventTypeRow{}
	for rows.Next() {
		var i SubscriptionsForEventTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetUrl,
			&i.EventTypes,
			&i.FilterExpr,
			&i.SecretEnc,
			&i.SecretKeyID,
			&i.PreviousSecretEnc,
			&i.PreviousSecretKeyID,
			&i.PreviousSecretUntil,
			&i.State,
			&i.FailureCount,
			&i.LastError,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :execrows
UPDATE webhook_subscription SET
  target_url  = $1,
  event_types = $2,
  filter_expr = $3,
  state       = $4,
  failure_count = $5,
  last_error  = $6,
  disabled_at = $7,
  version     = version + 1
WHERE id = $8 AND version = $9
`

type UpdateWebhookSubscriptionParams struct {
	TargetUrl       string
	EventTypes      []string
	FilterExpr      *string
	State           string
	FailureCount    int32
	LastError       *string
	DisabledAt      pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Optimistic locking in the WHERE clause: the update matches nothing when somebody else has moved
// the row on, and the caller learns that rather than overwriting them (api-guidelines.md).
func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWebhookSubscription,
		arg.TargetUrl,
		arg.EventTypes,
		arg.FilterExpr,
		arg.State,
		arg.FailureCount,
		arg.LastError,
		arg.DisabledAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const webhookDeliveries = `-- name: WebhookDeliveries :many
SELECT id, subscription_id, event_id, attempt, status, response_status, error_code,
       next_attempt_at, created_at
FROM webhook_delivery
WHERE subscription_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR id < $3::uuid)
ORDER BY id DESC
LIMIT $4
`

type WebhookDeliveriesParams struct {
	SubscriptionID pgtype.UUID
	Status         *string
	Before         pgtype.UUID
	PageSize       int32
}

type WebhookDeliveriesRow struct {
	ID             pgtype.UUID
	SubscriptionID pgtype.UUID
	EventID        pgtype.UUID
	Attempt        int32
	Status         string
	ResponseStatus *int32
	ErrorCode      *string
	NextAttemptAt  pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

// One subscription's attempts, newest first, optionally narrowed to one outcome - DEAD_LETTER is
// the one an operator usually wants. The cursor is the identifier, which is time-ordered.
func (q *Queries) WebhookDeliveries(ctx context.Context, arg WebhookDeliveriesParams) ([]WebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, webhookDeliveries,
		arg.SubscriptionID,
		arg.Status,
		arg.Before,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDeliveriesRow{}
	for rows.Next() {
		var i WebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventID,
			&i.Attempt,
			&i.Status,
			&i.ResponseStatus,
			&i.ErrorCode,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webhookSubscriptionsSealedNotUnder = `-- name: WebhookSubscriptionsSealedNotUnder :many
SELECT id, target_url, event_types, filter_expr, secret_enc, secret_key_id,
       previous_secret_enc, previous_secret_key_id, previous_secret_until,
       state, failure_count, last_error, disabled_at, created_by, created_at, version
FROM webhook_subscription
WHERE (secret_key_id IS NOT NULL AND secret_key_id <> $1)
   OR (previous_secret_key_id IS NOT NULL AND previous_secret_key_id <> $1)
ORDER BY id
`

type WebhookSubscriptionsSealedNotUnderRow struct {
	ID                  pgtype.UUID
	TargetUrl           string
	EventTypes          []string
	FilterExpr          *string
	SecretEnc           []byte
	SecretKeyID         *string
	PreviousSecretEnc   []byte
	PreviousSecretKeyID *string
	PreviousSecretUntil pgtype.Timestamptz
	State               string
	FailureCount        int32
	LastError           *string
	DisabledAt          pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	Version             int32
}

// The rows a re-seal visits (ADR-0045): a subscription whose current or previous secret names a
// key other than the current one. Both, because a grace that outlives a rotation is still a
// secret the verifier has to open.
func (q *Queries) WebhookSubscriptionsSealedNotUnder(ctx context.Context, keyID *string) ([]WebhookSubscriptionsSealedNotUnderRow, error) {
	rows, err := q.db.Query(ctx, webhookSubscriptionsSealedNotUnder, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscriptionsSealedNotUnderRow{}
	for rows.Next() {
		var i WebhookSubscriptionsSealedNotUnderRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetUrl,
			&i.EventTypes,
			&i.FilterExpr,
			&i.SecretEnc,
			&i.SecretKeyID,
			&i.PreviousSecretEnc,
			&i.PreviousSecretKeyID,
			&i.PreviousSecretUntil,
			&i.State,
			&i.FailureCount,
			&i.LastError,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
