// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Work.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const childCompletion = `-- name: ChildCompletion :one
SELECT
  count(*)::int AS total,
  (count(*) FILTER (WHERE is_completed))::int AS completed
FROM work_item
WHERE parent_id = $1::uuid
  AND deleted_at IS NULL
`

type ChildCompletionRow struct {
	Total     int32
	Completed int32
}

// How many children an item has, and how many of them are done. The two numbers the roll-up decides
// from (I-W5), as counts rather than as rows: the question is "is anything still open down there", and
// reading a subtree to answer one boolean is the shape this avoids.
//
// Trashed children are excluded outright. They are deletions waiting out their retention period, and a
// work package whose last activity was deleted must not become done because of it. Archived children are
// counted as they stand - archiving is a decision to keep something quietly, not to disown it.
//
// Served by wi_parent_idx (tenant_id, parent_id, order_key): the tenant comes from row level security, so
// the leading column is satisfied without appearing here.
func (q *Queries) ChildCompletion(ctx context.Context, parentID pgtype.UUID) (ChildCompletionRow, error) {
	row := q.db.QueryRow(ctx, childCompletion, parentID)
	var i ChildCompletionRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const containerOrderKeyNeighbours = `-- name: ContainerOrderKeyNeighbours :one
WITH level AS (
  SELECT id, order_key
  FROM container
  WHERE parent_id IS NOT DISTINCT FROM $1::uuid
    AND deleted_at IS NULL
    AND id <> $2::uuid
), anchor AS (
  SELECT order_key FROM level WHERE id = $3::uuid
)
SELECT
  coalesce((SELECT order_key FROM anchor), '')::text AS next_key,
  coalesce((
    SELECT max(order_key COLLATE "C")
    FROM level
    WHERE (SELECT order_key FROM anchor) IS NULL
       OR order_key COLLATE "C" < (SELECT order_key FROM anchor) COLLATE "C"
  ), '')::text AS previous_key
`

type ContainerOrderKeyNeighboursParams struct {
	ParentID pgtype.UUID
	MovingID pgtype.UUID
	BeforeID pgtype.UUID
}

type ContainerOrderKeyNeighboursRow struct {
	NextKey     string
	PreviousKey string
}

// The two ranks a position sits between at one container level: the rank of the container to go
// before, and the greatest rank below it.
//
// The counterpart of OrderKeyNeighbours for items, and the same shape for the same reasons: both
// bounds in one row so that they are consistent as of the moment they are asked, the empty string for
// "nothing there", and COLLATE "C" wherever two ranks are compared - a fractional index rests on byte
// order, and a database created en_US.utf8 on glibc would order it differently from the domain that
// produced it.
//
// The level is the parent, compared with IS NOT DISTINCT FROM so that an absent one means the hubs
// rather than no filter at all. The moving container is excluded from its own level: a reorder would
// otherwise measure a position against the rank it is leaving.
func (q *Queries) ContainerOrderKeyNeighbours(ctx context.Context, arg ContainerOrderKeyNeighboursParams) (ContainerOrderKeyNeighboursRow, error) {
	row := q.db.QueryRow(ctx, containerOrderKeyNeighbours, arg.ParentID, arg.MovingID, arg.BeforeID)
	var i ContainerOrderKeyNeighboursRow
	err := row.Scan(&i.NextKey, &i.PreviousKey)
	return i, err
}

const countOpenItemsByAssignee = `-- name: CountOpenItemsByAssignee :many
SELECT assignee_id, COUNT(*) AS open_items
FROM work_item
WHERE assignee_id = ANY($1::uuid[])
  AND is_completed = false
  AND deleted_at IS NULL
  AND archived_at IS NULL
GROUP BY assignee_id
`

type CountOpenItemsByAssigneeRow struct {
	AssigneeID pgtype.UUID
	OpenItems  int64
}

// LEAST_LOADED's material (C-02): how many open entries each candidate carries, tenant-wide,
// because a person's load does not stop at a collection's edge. Open means not completed, not in
// the trash, and not archived by its own stamp - the inherited archive of an ancestor is not
// consulted, which overcounts a dormant subtree's entries rather than paying a recursive walk on
// every create. Candidates with no open entry are simply absent from the answer; the caller reads
// an absent key as zero.
func (q *Queries) CountOpenItemsByAssignee(ctx context.Context, accountIds []pgtype.UUID) ([]CountOpenItemsByAssigneeRow, error) {
	rows, err := q.db.Query(ctx, countOpenItemsByAssignee, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenItemsByAssigneeRow{}
	for rows.Next() {
		var i CountOpenItemsByAssigneeRow
		if err := rows.Scan(&i.AssigneeID, &i.OpenItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findContainer = `-- name: FindContainer :one

SELECT
  c.id, c.tenant_id, c.type, c.parent_id, c.name, c.description, c.icon, c.color_token, c.order_key,
  coalesce(c.policies->>'completion_policy', '')::text AS completion_policy,
  aap.strategy AS auto_assign_strategy,
  aap.candidates AS auto_assign_candidates,
  aap.enabled AS auto_assign_enabled,
  c.archived_at, parent.archived_at AS parent_archived_at,
  c.deleted_at, c.trash_batch_id, c.created_by, c.created_at, c.updated_at, c.version
FROM container c
LEFT JOIN container parent ON parent.id = c.parent_id
LEFT JOIN auto_assign_policy aap ON aap.scope_type = 'COLLECTION' AND aap.scope_id = c.id
WHERE c.id = $1
`

type FindContainerRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	Type                 ContainerType
	ParentID             pgtype.UUID
	Name                 string
	Description          *string
	Icon                 *string
	ColorToken           *string
	OrderKey             string
	CompletionPolicy     string
	AutoAssignStrategy   *string
	AutoAssignCandidates []byte
	AutoAssignEnabled    *bool
	ArchivedAt           pgtype.Timestamptz
	ParentArchivedAt     pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	TrashBatchID         pgtype.UUID
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Version              int32
}

// The tenant is never a parameter here: it comes from the transaction's own context through
// current_tenant_id(), which is the same value row level security compares against. A row can
// therefore not be written into the wrong tenant even by a caller that wanted to, and a read
// cannot reach one belonging to somebody else.
// Trashed and archived containers are returned rather than filtered out. The repository reports
// what is stored and judges none of it: whether a container may take children is a question the
// domain answers, and a query that hid a trashed parent would turn "it is in the trash" into
// "it does not exist" (I-C2, I-C3).
//
// One key of `policies` is read out, not the column: the completion policy has a reader (B-07) and the
// keys without a use case do not, and selecting a value nothing consumes is a promise nothing keeps.
// `->>` yields NULL for a collection that has never been configured, and coalesce turns that into the
// empty string - which the domain reads as the default. Coalescing here rather than mapping a nil
// pointer in the adapter keeps the generated field a plain string, and "unset" one concept instead of
// two.
//
// The auto_assign key of the same document lives in its own row (C-02, see Assignment.sql), and the
// second LEFT JOIN is how it travels with the container: NULL columns for a container without a
// policy, which the adapter reads as the key being absent. The join lands on migration 0011's unique
// index, so it costs an index lookup - the same price as the parent join beside it.
//
// The hub's own archive stamp travels with the row as `parent_archived_at`, which is invariant I-C3's
// second half: a collection in an archived hub is read-only without being archived itself. Read here
// rather than stored on the collection, so that archiving a hub writes one row and unarchiving it
// restores exactly what it covered - a collection archived in its own right stays archived. The join
// is a primary key lookup, and it is NULL for a hub, which sits under nothing.
func (q *Queries) FindContainer(ctx context.Context, id pgtype.UUID) (FindContainerRow, error) {
	row := q.db.QueryRow(ctx, findContainer, id)
	var i FindContainerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.ColorToken,
		&i.OrderKey,
		&i.CompletionPolicy,
		&i.AutoAssignStrategy,
		&i.AutoAssignCandidates,
		&i.AutoAssignEnabled,
		&i.ArchivedAt,
		&i.ParentArchivedAt,
		&i.DeletedAt,
		&i.TrashBatchID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findWorkItem = `-- name: FindWorkItem :one
SELECT
  id, tenant_id, collection_id, type, parent_id, path, depth, title, notes,
  is_completed, completed_at, completed_by, bucket_id, order_key, assignee_id,
  cover_kind, cover_color_token, cover_media_id,
  archived_at, deleted_at, trash_batch_id, created_by, created_at, updated_at, version
FROM work_item
WHERE id = $1
`

type FindWorkItemRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	CollectionID    pgtype.UUID
	Type            ItemType
	ParentID        pgtype.UUID
	Path            string
	Depth           int32
	Title           string
	Notes           *string
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CompletedBy     pgtype.UUID
	BucketID        pgtype.UUID
	OrderKey        string
	AssigneeID      pgtype.UUID
	CoverKind       *string
	CoverColorToken *string
	CoverMediaID    pgtype.UUID
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	TrashBatchID    pgtype.UUID
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int32
}

// Trashed and archived items are returned rather than filtered out, for the reason FindContainer
// returns them: the repository reports what is stored and judges none of it (I-W4).
func (q *Queries) FindWorkItem(ctx context.Context, id pgtype.UUID) (FindWorkItemRow, error) {
	row := q.db.QueryRow(ctx, findWorkItem, id)
	var i FindWorkItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CollectionID,
		&i.Type,
		&i.ParentID,
		&i.Path,
		&i.Depth,
		&i.Title,
		&i.Notes,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.BucketID,
		&i.OrderKey,
		&i.AssigneeID,
		&i.CoverKind,
		&i.CoverColorToken,
		&i.CoverMediaID,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.TrashBatchID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertContainer = `-- name: InsertContainer :exec
INSERT INTO container (
  id, tenant_id, type, parent_id, name, description, icon, color_token, order_key,
  created_by, created_at, updated_at, version
) VALUES (
  $1, current_tenant_id(), $2, $3,
  normalize($4::text, NFC),
  $5, $6, $7, $8,
  $9, $10, $10, 1
)
`

type InsertContainerParams struct {
	ID          pgtype.UUID
	Type        ContainerType
	ParentID    pgtype.UUID
	Name        string
	Description *string
	Icon        *string
	ColorToken  *string
	OrderKey    string
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

// The name is stored Unicode NFC normalised, in the database rather than in the application:
// "Übersicht" typed with a combining diaeresis and the same word composed are one name to a
// person, and the unique index has to see them as one name too. Doing it here also keeps the
// domain free of a Unicode library it is not allowed to import (ADR-0001).
func (q *Queries) InsertContainer(ctx context.Context, arg InsertContainerParams) error {
	_, err := q.db.Exec(ctx, insertContainer,
		arg.ID,
		arg.Type,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.ColorToken,
		arg.OrderKey,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertWorkItem = `-- name: InsertWorkItem :exec
INSERT INTO work_item (
  id, tenant_id, collection_id, type, parent_id, path, depth, title, notes,
  bucket_id, order_key, created_by, created_at, updated_at, version
) VALUES (
  $1, current_tenant_id(), $2, $3,
  $4, $5, $6,
  normalize($7::text, NFC),
  $8, $9, $10, $11,
  $12, $12, 1
)
`

type InsertWorkItemParams struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
	Type         ItemType
	ParentID     pgtype.UUID
	Path         string
	Depth        int32
	Title        string
	Notes        *string
	BucketID     pgtype.UUID
	OrderKey     string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

// The title is stored Unicode NFC normalised, in the database rather than in the application, for
// the reason the container's name is: two spellings of the same word have to be one value to
// every query that compares or searches them, and doing it here keeps a Unicode library out of
// the domain (ADR-0001, I-W7).
//
// The fields this use case does not own are absent rather than defaulted: labels, members,
// assignee, due date, cover, custom fields and the recurrence rule are written by the use cases
// that own them, and their columns carry NULL until then.
func (q *Queries) InsertWorkItem(ctx context.Context, arg InsertWorkItemParams) error {
	_, err := q.db.Exec(ctx, insertWorkItem,
		arg.ID,
		arg.CollectionID,
		arg.Type,
		arg.ParentID,
		arg.Path,
		arg.Depth,
		arg.Title,
		arg.Notes,
		arg.BucketID,
		arg.OrderKey,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const lastContainerOrderKey = `-- name: LastContainerOrderKey :one
SELECT order_key
FROM container
WHERE parent_id IS NOT DISTINCT FROM $1::uuid
ORDER BY order_key DESC
LIMIT 1
`

// The highest rank directly under a parent, or no row when the level is empty. A NULL parent is
// the hub level, which is why the comparison is IS NOT DISTINCT FROM rather than `=`: `NULL = NULL`
// is unknown, and the hubs would come back as no rows at all.
//
// Trashed containers count. Their rank is still occupied - a restore has to land where it was.
func (q *Queries) LastContainerOrderKey(ctx context.Context, parentID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastContainerOrderKey, parentID)
	var order_key string
	err := row.Scan(&order_key)
	return order_key, err
}

const lastWorkItemOrderKey = `-- name: LastWorkItemOrderKey :one
SELECT order_key
FROM work_item
WHERE collection_id = $1::uuid
  AND parent_id IS NOT DISTINCT FROM $2::uuid
ORDER BY order_key DESC
LIMIT 1
`

type LastWorkItemOrderKeyParams struct {
	CollectionID pgtype.UUID
	ParentID     pgtype.UUID
}

// The highest rank among the siblings of a new item: same collection, same parent. A NULL parent
// is the level directly under the collection, which is why the comparison is IS NOT DISTINCT FROM
// rather than `=` - `NULL = NULL` is unknown, and the tasks would come back as no rows at all.
//
// Trashed items count. Their rank is still occupied; a restore has to land where it was.
func (q *Queries) LastWorkItemOrderKey(ctx context.Context, arg LastWorkItemOrderKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, lastWorkItemOrderKey, arg.CollectionID, arg.ParentID)
	var order_key string
	err := row.Scan(&order_key)
	return order_key, err
}

const listContainers = `-- name: ListContainers :many
SELECT
  c.id, c.tenant_id, c.type, c.parent_id, c.name, c.description, c.icon, c.color_token, c.order_key,
  coalesce(c.policies->>'completion_policy', '')::text AS completion_policy,
  aap.strategy AS auto_assign_strategy,
  aap.candidates AS auto_assign_candidates,
  aap.enabled AS auto_assign_enabled,
  c.archived_at, parent.archived_at AS parent_archived_at,
  c.deleted_at, c.trash_batch_id, c.created_by, c.created_at, c.updated_at, c.version
FROM container c
LEFT JOIN container parent ON parent.id = c.parent_id
LEFT JOIN auto_assign_policy aap ON aap.scope_type = 'COLLECTION' AND aap.scope_id = c.id
WHERE c.parent_id IS NOT DISTINCT FROM $1::uuid
  AND c.deleted_at IS NULL
  AND ($2::container_type IS NULL OR c.type = $2::container_type)
  AND ($3::boolean OR c.archived_at IS NULL)
  AND (
    $4::text IS NULL
    OR (c.order_key COLLATE "C", c.id)
       > ($4::text COLLATE "C", $5::uuid)
  )
ORDER BY c.order_key COLLATE "C", c.id
LIMIT $6
`

type ListContainersParams struct {
	ParentID        pgtype.UUID
	Type            *ContainerType
	IncludeArchived bool
	CursorOrderKey  *string
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListContainersRow struct {
	ID                   pgtype.UUID
	TenantID             pgtype.UUID
	Type                 ContainerType
	ParentID             pgtype.UUID
	Name                 string
	Description          *string
	Icon                 *string
	ColorToken           *string
	OrderKey             string
	CompletionPolicy     string
	AutoAssignStrategy   *string
	AutoAssignCandidates []byte
	AutoAssignEnabled    *bool
	ArchivedAt           pgtype.Timestamptz
	ParentArchivedAt     pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	TrashBatchID         pgtype.UUID
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Version              int32
}

// One level of the container tree, in its manual order: the hubs when no parent is named, that
// hub's collections when one is. IS NOT DISTINCT FROM is what makes the absent parent mean the hub
// level rather than "no filter" - `parent_id = NULL` is unknown, and the hubs would come back as no
// rows at all.
//
// The type filter composes with it rather than replacing it, which means the two impossible
// combinations return an empty page: a collection always has a parent, and a hub never does. That is
// the filters agreeing, not a special case worth coding.
//
// Trashed rows are never here - the trash is its own view (B-10). Archived ones are, when the caller
// asks: an archived collection is still a collection, and hiding it would make it unreachable. The
// filter reads the row's own stamp rather than the effective one on purpose - a collection is not
// hidden from the level because the hub above it was archived, since the client asking for that hub's
// collections has just been told the hub is archived.
//
// The keyset is (order_key, id) rather than an offset, so a page boundary survives a concurrent
// insert (api-guidelines.md §4). `id` is the tiebreak the guidelines require, and it is what makes
// the boundary unambiguous should two siblings ever share a rank.
//
// COLLATE "C" on both the comparison and the order, for the reason migration 0007 gives: a rank key
// is a fractional index whose scheme rests on byte order, and a database created en_US.utf8 on glibc
// would order it differently from the domain that produced it.
//
// One row more than the page size is read, and the caller reports has_more from it: asking whether
// there is a next page is otherwise a second query, and a COUNT over the level is the expensive
// thing this endpoint exists to avoid.
func (q *Queries) ListContainers(ctx context.Context, arg ListContainersParams) ([]ListContainersRow, error) {
	rows, err := q.db.Query(ctx, listContainers,
		arg.ParentID,
		arg.Type,
		arg.IncludeArchived,
		arg.CursorOrderKey,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContainersRow{}
	for rows.Next() {
		var i ListContainersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.ColorToken,
			&i.OrderKey,
			&i.CompletionPolicy,
			&i.AutoAssignStrategy,
			&i.AutoAssignCandidates,
			&i.AutoAssignEnabled,
			&i.ArchivedAt,
			&i.ParentArchivedAt,
			&i.DeletedAt,
			&i.TrashBatchID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItems = `-- name: ListWorkItems :many
SELECT
  id, tenant_id, collection_id, type, parent_id, path, depth, title, notes,
  is_completed, completed_at, completed_by, bucket_id, order_key, assignee_id,
  cover_kind, cover_color_token, cover_media_id,
  archived_at, deleted_at, trash_batch_id, created_by, created_at, updated_at, version
FROM work_item
WHERE collection_id = $1::uuid
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND deleted_at IS NULL
  AND ($3::boolean OR archived_at IS NULL)
  -- The entries the caller may see, when that is fewer than the level: null is no restriction at
  -- all, which is what every caller holding a role on the collection passes (C-04).
  AND (
    $4::uuid[] IS NULL
    OR id = ANY($4::uuid[])
  )
  AND (
    $5::text IS NULL
    OR (order_key COLLATE "C", id)
       > ($5::text COLLATE "C", $6::uuid)
  )
ORDER BY order_key COLLATE "C", id
LIMIT $7
`

type ListWorkItemsParams struct {
	CollectionID    pgtype.UUID
	ParentID        pgtype.UUID
	IncludeArchived bool
	RestrictTo      []pgtype.UUID
	CursorOrderKey  *string
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListWorkItemsRow struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	CollectionID    pgtype.UUID
	Type            ItemType
	ParentID        pgtype.UUID
	Path            string
	Depth           int32
	Title           string
	Notes           *string
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CompletedBy     pgtype.UUID
	BucketID        pgtype.UUID
	OrderKey        string
	AssigneeID      pgtype.UUID
	CoverKind       *string
	CoverColorToken *string
	CoverMediaID    pgtype.UUID
	ArchivedAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	TrashBatchID    pgtype.UUID
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int32
}

// One level of one collection, in its manual order: the items directly in the collection when no
// parent is named, that item's children when one is. Anchored to a collection because an unanchored
// list of every item in a tenant is an unindexed scan, and every filter beyond one level is what
// POST /items:query exists for (B-12).
//
// The collection is compared as well as the parent, even when the parent decides the level on its
// own: it is the leading column of wi_level_order_idx, and a query that dropped it would fall back to
// wi_parent_idx and scan the whole tenant's tasks for the parent-IS-NULL case.
//
// Everything else - the keyset, the collation, the row read beyond the page - is as ListContainers,
// and for the same reasons.
func (q *Queries) ListWorkItems(ctx context.Context, arg ListWorkItemsParams) ([]ListWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listWorkItems,
		arg.CollectionID,
		arg.ParentID,
		arg.IncludeArchived,
		arg.RestrictTo,
		arg.CursorOrderKey,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkItemsRow{}
	for rows.Next() {
		var i ListWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CollectionID,
			&i.Type,
			&i.ParentID,
			&i.Path,
			&i.Depth,
			&i.Title,
			&i.Notes,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.BucketID,
			&i.OrderKey,
			&i.AssigneeID,
			&i.CoverKind,
			&i.CoverColorToken,
			&i.CoverMediaID,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.TrashBatchID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveWorkItemSubtree = `-- name: MoveWorkItemSubtree :execrows
UPDATE work_item SET
  collection_id = $1::uuid,
  path          = $2::text
                  || substring(path from length($3::text) + 1),
  depth         = depth + $4::int,
  updated_at    = $5,
  version       = version + 1
WHERE path LIKE $3::text || '%'
  AND id <> $6::uuid
`

type MoveWorkItemSubtreeParams struct {
	CollectionID pgtype.UUID
	NewPrefix    string
	OldPrefix    string
	DepthDelta   int32
	UpdatedAt    pgtype.Timestamptz
	ItemID       pgtype.UUID
}

// Rewrites the materialised path, the depth and the collection of an item and everything below it, in one
// statement (I-W2: the path and the depth stay consistent, and changes go through a move that updates the
// subtree within one transaction).
//
// The prefix swap is what makes this one statement rather than a walk: every descendant's new path is its old
// path with the old prefix replaced, and `substring(path from length(prefix) + 1)` is that suffix. The depth
// moves by a constant, because every row in a subtree shifts by the same number of levels.
//
// `LIKE prefix || '%'` rather than starts_with, because that is the form wi_path_idx
// (tenant_id, path text_pattern_ops) serves as an index scan. A path is built from UUIDs and separators, so
// it can contain no LIKE metacharacter - there is nothing here for a `%` or a `_` in the data to do.
//
// Trashed rows in the subtree are rewritten too, deliberately. Their path still has to describe where they
// would be restored to; leaving them behind would point a restore at an ancestor that has moved.
//
// The version moves on every row, because a descendant's path is part of its state and a client caching the
// subtree has to be able to tell that it changed.
//
// The moved item itself is excluded. Its own path begins with its own prefix, so it would match - and it is
// SetWorkItemPlacement that owns its row, which is where the optimistic lock is. Without the exclusion the
// moved item would have its version bumped twice by one move, which is not a design but an artefact of
// writing it in two statements.
func (q *Queries) MoveWorkItemSubtree(ctx context.Context, arg MoveWorkItemSubtreeParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveWorkItemSubtree,
		arg.CollectionID,
		arg.NewPrefix,
		arg.OldPrefix,
		arg.DepthDelta,
		arg.UpdatedAt,
		arg.ItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orderKeyNeighbours = `-- name: OrderKeyNeighbours :one
WITH level AS (
  SELECT id, order_key
  FROM work_item
  WHERE collection_id = $1::uuid
    AND parent_id IS NOT DISTINCT FROM $2::uuid
    AND deleted_at IS NULL
    AND id <> $3::uuid
), anchor AS (
  SELECT order_key FROM level WHERE id = $4::uuid
)
SELECT
  coalesce((SELECT order_key FROM anchor), '')::text AS next_key,
  coalesce((
    SELECT max(order_key COLLATE "C")
    FROM level
    WHERE (SELECT order_key FROM anchor) IS NULL
       OR order_key COLLATE "C" < (SELECT order_key FROM anchor) COLLATE "C"
  ), '')::text AS previous_key
`

type OrderKeyNeighboursParams struct {
	CollectionID pgtype.UUID
	ParentID     pgtype.UUID
	MovingID     pgtype.UUID
	BeforeID     pgtype.UUID
}

type OrderKeyNeighboursRow struct {
	NextKey     string
	PreviousKey string
}

// The two ranks a new position sits between: the rank of the item to go before, and the greatest rank below
// it in the same level.
//
// Both come back as the empty string when there is nothing there, which is what the ordering service reads as
// "no bound" - before everything, or after everything. Asking the database for both in one row rather than
// computing one from a list keeps the answer consistent with what is stored at the moment it is asked.
//
// COLLATE "C" on the comparison and nowhere else it could disagree: a rank key is a fractional index whose
// scheme rests on byte order, and a database created en_US.utf8 on glibc would order it differently from the
// domain that produced it.
//
// The level is (collection, parent), and the parent is compared with IS NOT DISTINCT FROM so that an absent
// one means the items directly in the collection rather than no filter at all.
func (q *Queries) OrderKeyNeighbours(ctx context.Context, arg OrderKeyNeighboursParams) (OrderKeyNeighboursRow, error) {
	row := q.db.QueryRow(ctx, orderKeyNeighbours,
		arg.CollectionID,
		arg.ParentID,
		arg.MovingID,
		arg.BeforeID,
	)
	var i OrderKeyNeighboursRow
	err := row.Scan(&i.NextKey, &i.PreviousKey)
	return i, err
}

const setContainerArchived = `-- name: SetContainerArchived :execrows
UPDATE container SET
  archived_at = $1,
  updated_at  = $2,
  version     = version + 1
WHERE id = $3::uuid AND version = $4
`

type SetContainerArchivedParams struct {
	ArchivedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The archive stamp, set or cleared. One statement for both directions, because they differ in the
// value and in nothing else.
//
// Only this row. A collection under an archived hub inherits the state through FindContainer's join
// rather than through a stamp of its own, so archiving a hub writes one row here however many
// collections sit in it - and unarchiving it restores exactly what it covered, leaving a collection
// that was archived in its own right archived (I-C3).
func (q *Queries) SetContainerArchived(ctx context.Context, arg SetContainerArchivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContainerArchived,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContainerAttributes = `-- name: SetContainerAttributes :execrows
UPDATE container SET
  name        = normalize($1::text, NFC),
  description = $2,
  icon        = $3,
  color_token = $4,
  updated_at  = $5,
  version     = version + 1
WHERE id = $6::uuid AND version = $7
`

type SetContainerAttributesParams struct {
	Name            string
	Description     *string
	Icon            *string
	ColorToken      *string
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// A container's own descriptive fields: what RenameContainer may change (B-06).
//
// Every column is written on every call, not only the ones that moved. The application has already
// decided what the row should say - it read the container, applied the update and refused what the
// lifecycle does not allow - so this writes that decision whole. `description = COALESCE($1,
// description)` would additionally make clearing a description unexpressible.
//
// The name is normalised here for the reason InsertContainer normalises it: the unique index has to
// see two spellings of the same word as one name, and the domain may not import a Unicode library
// (ADR-0001). A rename into a name already taken at this level therefore fails on `container_name_uq`
// exactly as an insert does, which is what keeps one answer for one condition.
//
// Optimistic locking in the WHERE clause, as everywhere: the update matches nothing when somebody
// else has moved the row on, and the caller learns that rather than overwriting them
// (api-guidelines.md §5).
func (q *Queries) SetContainerAttributes(ctx context.Context, arg SetContainerAttributesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContainerAttributes,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.ColorToken,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContainerPlacement = `-- name: SetContainerPlacement :execrows
UPDATE container SET
  parent_id  = $1::uuid,
  order_key  = $2,
  updated_at = $3,
  version    = version + 1
WHERE id = $4::uuid AND version = $5
`

type SetContainerPlacementParams struct {
	ParentID        pgtype.UUID
	OrderKey        string
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Where a collection sits and how it ranks there: the whole of what a move changes.
//
// No subtree statement beside it, unlike the item move. A container tree is two levels deep (I-C1), so
// a collection has no containers below it whose path would have to follow - and the items it holds
// reference their collection rather than a path through the hubs.
//
// A name already taken in the destination fails on `container_name_uq`, which is the same index that
// decides an insert. Checking beforehand would be two statements with a gap, and two moves arriving
// inside that gap would both pass the check (multi-tenancy.md §2.1).
func (q *Queries) SetContainerPlacement(ctx context.Context, arg SetContainerPlacementParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContainerPlacement,
		arg.ParentID,
		arg.OrderKey,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setContainerPolicies = `-- name: SetContainerPolicies :execrows
UPDATE container SET
  policies   = jsonb_set(policies, '{completion_policy}',
               to_jsonb($1::text), true),
  updated_at = $2,
  version    = version + 1
WHERE id = $3::uuid AND version = $4
`

type SetContainerPoliciesParams struct {
	CompletionPolicy string
	UpdatedAt        pgtype.Timestamptz
	ID               pgtype.UUID
	ExpectedVersion  int32
}

// One key of the policies document, set in place.
//
// `jsonb_set` rather than replacing the column, because the column holds four documented keys and this
// use case owns one of them. Overwriting the whole document would silently discard a default bucket or
// a capability override the moment either of those arrives - a data loss nobody would see until the
// feature that wrote them stopped working.
//
// The value is a parameter of the jsonb constructor rather than concatenated text: `to_jsonb` on a
// bound parameter is what keeps this a parameterised statement, which rule 9 requires of every query
// including the ones that build a document.
func (q *Queries) SetContainerPolicies(ctx context.Context, arg SetContainerPoliciesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setContainerPolicies,
		arg.CompletionPolicy,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemAssignee = `-- name: SetWorkItemAssignee :execrows
UPDATE work_item SET
  assignee_id = $1,
  updated_at  = $2,
  version     = version + 1
WHERE id = $3::uuid AND version = $4
`

type SetWorkItemAssigneeParams struct {
	AssigneeID      pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The one person an entry is on, set or cleared, under the same optimistic lock every write to
// this row takes: the update matches nothing when somebody else has moved the row on, and the
// caller learns that rather than overwriting them (api-guidelines.md §5).
//
// Its own statement rather than a column added to SetWorkItemAttributes. An assignment is one
// decision about one field, and a statement that wrote the title alongside it would make handing
// an entry to somebody spend the version of a rename nobody asked for - which is the same reason
// the completion has a statement of its own.
//
// Whether that account may be assigned at all is not asked here. It is a question about a
// membership somewhere above the entry, decided in the application layer before this runs
// (ADR-0005); the tenant-scoped foreign key is what stops the identifier pointing outside the
// tenant, and it is the database's rather than this statement's (ADR-0024).
func (q *Queries) SetWorkItemAssignee(ctx context.Context, arg SetWorkItemAssigneeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemAssignee,
		arg.AssigneeID,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemAttributes = `-- name: SetWorkItemAttributes :execrows
UPDATE work_item SET
  title      = $1,
  notes      = $2,
  bucket_id  = $3,
  updated_at = $4,
  version    = version + 1
WHERE id = $5::uuid AND version = $6
`

type SetWorkItemAttributesParams struct {
	Title           string
	Notes           *string
	BucketID        pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The item's own fields: what UpdateWorkItem may change in 0.2.0 (B-05).
//
// Both columns are written on every call, not only the ones that moved. The application has already
// decided what the row should say - it read the item, applied the update and refused what the capability
// profile does not allow - so this writes that decision whole. A statement that switched on which fields
// were sent would be the second place deciding it, in the layer that is not allowed to decide anything
// (ADR-0005), and `notes = COALESCE($1, notes)` would additionally make clearing the notes unexpressible.
//
// Optimistic locking in the WHERE clause, as everywhere: the update matches nothing when somebody else has
// moved the row on, and the caller learns that rather than overwriting them (api-guidelines.md §5).
//
// `search_vector` follows by itself. It is a generated column over title and notes, so the index behind
// full text search cannot fall behind a rename - which is exactly what a trigger somebody has to remember
// would eventually do.
func (q *Queries) SetWorkItemAttributes(ctx context.Context, arg SetWorkItemAttributesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemAttributes,
		arg.Title,
		arg.Notes,
		arg.BucketID,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemCompletion = `-- name: SetWorkItemCompletion :execrows
UPDATE work_item SET
  is_completed = $1,
  completed_at = $2,
  completed_by = $3,
  updated_at   = $4,
  version      = version + 1
WHERE id = $5::uuid AND version = $6
`

type SetWorkItemCompletionParams struct {
	IsCompleted     bool
	CompletedAt     pgtype.Timestamptz
	CompletedBy     pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// Optimistic locking in the WHERE clause: the update matches nothing when somebody else has moved the row
// on, and the caller learns that rather than overwriting them (api-guidelines.md §5).
//
// Both completion columns are written together, always. The table's own CHECK insists that
// `is_completed = (completed_at IS NOT NULL)`, so a statement that set one without the other would be
// refused by the database - which is the right place for that rule and the reason this query has no
// branch in it.
func (q *Queries) SetWorkItemCompletion(ctx context.Context, arg SetWorkItemCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemCompletion,
		arg.IsCompleted,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemCover = `-- name: SetWorkItemCover :execrows
UPDATE work_item SET
  cover_kind        = $1,
  cover_color_token = $2,
  cover_media_id    = $3,
  updated_at        = $4,
  version           = version + 1
WHERE id = $5::uuid AND version = $6
`

type SetWorkItemCoverParams struct {
	CoverKind       *string
	CoverColorToken *string
	CoverMediaID    pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The cover, set or cleared, under the same optimistic lock every write to this row takes. Its
// own statement for the reason the assignee has one: a cover is one decision about one field,
// and spending a rename's version on it would be a version nobody asked for. The consistency of
// the three columns is the table's CHECK (migration 0013), so a statement that half-set a cover
// would be refused by the database.
func (q *Queries) SetWorkItemCover(ctx context.Context, arg SetWorkItemCoverParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemCover,
		arg.CoverKind,
		arg.CoverColorToken,
		arg.CoverMediaID,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemOrderKey = `-- name: SetWorkItemOrderKey :execrows
UPDATE work_item SET
  order_key  = $1,
  updated_at = $2,
  version    = version + 1
WHERE id = $3::uuid AND version = $4
`

type SetWorkItemOrderKeyParams struct {
	OrderKey        string
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// A reorder within one level: the rank alone, which is the whole of what drag and drop changes.
func (q *Queries) SetWorkItemOrderKey(ctx context.Context, arg SetWorkItemOrderKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemOrderKey,
		arg.OrderKey,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkItemPlacement = `-- name: SetWorkItemPlacement :execrows
UPDATE work_item SET
  parent_id     = $1::uuid,
  collection_id = $2::uuid,
  path          = $3,
  depth         = $4,
  order_key     = $5,
  bucket_id     = $6::uuid,
  updated_at    = $7,
  version       = version + 1
WHERE id = $8::uuid AND version = $9
`

type SetWorkItemPlacementParams struct {
	ParentID        pgtype.UUID
	CollectionID    pgtype.UUID
	Path            string
	Depth           int32
	OrderKey        string
	BucketID        pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

// The moved item's own row: the parent it now sits under and the rank it takes among its new siblings.
//
// This row is written here in full and excluded from the subtree statement, so that one move moves one
// version. Only this row's parent changes - a descendant keeps the parent it had - and the optimistic lock
// belongs on the row the caller actually read, which is this one.
func (q *Queries) SetWorkItemPlacement(ctx context.Context, arg SetWorkItemPlacementParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkItemPlacement,
		arg.ParentID,
		arg.CollectionID,
		arg.Path,
		arg.Depth,
		arg.OrderKey,
		arg.BucketID,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
