// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Jérôme Bastian Winkel

// What `@hubtask/sync-engine` is.
//
// One entry point, so that a consumer imports the seam rather than a file inside it - and so that
// the day the queue lands behind `SyncEngine`, nothing outside this package has a path to change.

export {
  SyncEngine,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_CONNECT_TIMEOUT_MS,
  DEFAULT_IDLE_TIMEOUT_MS,
  RECONNECT_BASE_MS,
  RECONNECT_MAX_MS,
} from './SyncEngine.ts';
export type {
  Listener,
  ListenOptions,
  MutateOptions,
  ResourceRequest,
  ResourceState,
  SyncEngineOptions,
  Unsubscribe,
} from './SyncEngine.ts';

export { FetchTransport } from './FetchTransport.ts';
export type { FetchTransportOptions } from './FetchTransport.ts';

export { TransportError } from './errors.ts';
export type { FailureKind, FieldProblem } from './errors.ts';

export { systemClock } from './ports.ts';
export type {
  ByteTransfer,
  Clock,
  RequestOptions,
  Response,
  Storage,
  StreamConnection,
  StreamEvent,
  StreamOptions,
  Transport,
  TransportDocument,
} from './ports.ts';

export type {
  AccessToken,
  Account,
  AccountPreferences,
  AccountSummary,
  ActivityEntry,
  ActivityPage,
  Assignment,
  AutoAssignOutcome,
  AutoAssignStrategy,
  Bucket,
  BulkOperation,
  CalendarFeed,
  CalendarFeedCreate,
  CalendarFeedSecret,
  BulkResult,
  Capabilities,
  ChangeRecord,
  Collection,
  Comment,
  CommentPage,
  Container,
  ContainerPage,
  Cover,
  CoverInput,
  CustomFieldDefinition,
  CustomFieldDefinitionCreate,
  CustomFieldDefinitionUpdate,
  CustomFieldKind,
  CustomFieldValue,
  DroppedReference,
  DuplicateResult,
  FilterNode,
  Group,
  GroupDetail,
  GroupPage,
  HealthReport,
  IdentityProvider,
  IdentityProviderConfiguration,
  ItemQueryResult,
  ItemSearchQuery,
  ItemAttachments,
  ItemMembers,
  Label,
  Membership,
  MembershipGrant,
  MembershipPage,
  MembershipRole,
  MembershipScope,
  MediaObject,
  MediaPage,
  MediaTransfer,
  MediaUploadRequest,
  MoveResult,
  NotificationPreference,
  NotificationPreferenceList,
  NotificationPreferenceUpdate,
  PendingMutation,
  Problem,
  PurgeSummary,
  QueryField,
  Recurrence,
  RecurrenceInput,
  RecurrenceMode,
  Reminder,
  ReminderChannel,
  ReminderInput,
  ReminderState,
  ReminderUpdate,
  RetentionDataKind,
  RetentionPolicy,
  SavedView,
  SavedViewCreate,
  SavedViewShare,
  SavedViewUpdate,
  StoredRecord,
  SyncCursor,
  Template,
  TemplateInput,
  TemplateInstance,
  TemplateInstantiation,
  TemplateNode,
  TemplatePage,
  TemplateScope,
  TemplateUpdate,
  TrashEntry,
  TrashPage,
  ViewExport,
  ViewExportDocument,
  WorkItem,
  WorkItemPage,
} from './schema.ts';
