// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2026 Jérôme Bastian Winkel

// The local store's shape, as types and nothing else.
//
// ADR-0033 §2 names the store, the mutation queue, HLC generation and cursor handling as this
// package's work. F1 writes down the *shape* and builds none of the behaviour, and that is the
// honest split: the queue and the HLC implement `:pull` and `:push`, and writing a client for a
// protocol that has no server yet means writing it twice (`offline-sync.md` §9 arrives in F6).
//
// Types with no implementation are still worth having now. They are what the Storage port is
// parameterised over, they say what the collections are called before two people name them
// differently, and they make the one decision this file *does* carry visible: a record keeps the
// server's version and the server's timestamps, and nothing here computes either.

import type { components } from '@hubtask/api-client';

/** The collections the store holds. A string union rather than free strings: a typo is a silent
 *  empty collection, and an empty collection looks exactly like a synced-but-empty one. */
export type Collection = 'containers' | 'items' | 'buckets' | 'labels' | 'comments';

/**
 * How a record is held locally: the server's document, plus the little the client needs to know
 * about it that the document does not say.
 */
export interface StoredRecord<T> {
  readonly id: string;
  /** Exactly what the server sent. Never a merged version - merging is the server's (ADR-0021). */
  readonly document: T;
  /** The version the document was read at, for the `If-Match` of the next write. */
  readonly version: number;
  /** When this client last saw it, by the injected Clock rather than by the machine's. */
  readonly seenAt: number;
  /**
   * A record the server has told us is gone. Kept rather than removed until the next full pull
   * confirms it, because a deletion that arrives before the write that caused it would otherwise
   * resurrect the row (`offline-sync.md` §5).
   */
  readonly tombstone?: true;
}

/**
 * A write the client has made and the server has not yet acknowledged.
 *
 * F1 queues nothing - the engine is online-only, so a write either succeeds or fails in front of
 * the person who made it. The type exists because the *shape* is what F6 implements against, and
 * because two fields of it are decisions rather than details: `idempotencyKey` is minted once per
 * intent so a retry is the same operation rather than a second one, and `hlc` is the server's
 * ordering input, generated by the client and never interpreted by it.
 */
export interface PendingMutation {
  readonly id: string;
  readonly collection: Collection;
  readonly recordId: string;
  readonly method: 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  readonly path: string;
  readonly body: unknown;
  /** Minted once per intent, not once per attempt. */
  readonly idempotencyKey: string;
  /** The hybrid logical clock stamp. Generated here, ordered by the server (ADR-0021). */
  readonly hlc: string;
  readonly queuedAt: number;
  readonly attempts: number;
}

/** Where a collection's pull left off. Opaque to the client: it is the server's cursor. */
export interface SyncCursor {
  readonly collection: Collection;
  readonly cursor: string;
  readonly at: number;
}

// The documents themselves come from the contract rather than being described a second time
// (ADR-0004). Re-exported so a consumer imports one package rather than two.
export type Account = components['schemas']['Account'];
/** What the installation says about itself. The frame configures from it and hard-codes nothing. */
export type Capabilities = components['schemas']['Capabilities'];
/** The deep report of `/meta/health`, which only an actor with `admin:read` may read. */
export type HealthReport = components['schemas']['HealthReport'];
export type Container = components['schemas']['Container'];
export type WorkItem = components['schemas']['WorkItem'];
export type Problem = components['schemas']['Problem'];
